ci/mynewt_install.sh
Disable certificate verification for developer.arm.com to avoid certificate issues when installing arm embedded tools to build Mynewt.
=> ci: fix wget error downloading arm-gcc-embedded

boot/bootutil/src/loader.c
This commit fixes following issue:
One of parameters in comparison using fih_eq() was not of fih_int
type which caused build error when medium or higher FIH mode is enabled.
To trigger issue:
set MCUBOOT_FIH_PROFILE=MEDIUM  this should trigger the build failure
``` C
11:42:56  In file included from /home/buildslave/workspace/tf-m-build-config/mcuboot/boot/bootutil/include/bootutil/bootutil.h:33:0,
11:42:56                   from /home/buildslave/workspace/tf-m-build-config/mcuboot/boot/bootutil/src/loader.c:38:
11:42:56  /home/buildslave/workspace/tf-m-build-config/mcuboot/boot/bootutil/src/loader.c: In function 'boot_validate_slot':
11:42:56  /home/buildslave/workspace/tf-m-build-config/mcuboot/boot/bootutil/include/boot …
```
=> boot/bootutil/loader: fix comparison using fih_eq() in hook service

boot/boot_serial/src/boot_serial.c
Change increases BOOT_SERIAL_OUT_MAX. This is necessary to provide complete image list when multi-image DFU is enabled and four image slots are occupied.
=> boot_serial: Increase BOOT_SERIAL_OUT_MAX

ci/mynewt_install.sh
This reverts commit 34f68ed67c0d1b1172f500808f42966c7b7d724b.
Re-enable certificate checking when downloading the Arm toolchain.
Although, this is probably not all that great of a risk, the certificate
issue was transient, and was fixed shortly after it was noticed.
=> Revert "ci: fix wget error downloading arm-gcc-embedded"

boot/espressif/hal/CMakeLists.txt, boot/espressif/hal/include/esp32s2/sdkconfig.h, boot/espressif/hal/include/mcuboot_config/mcuboot_logging.h, boot/espressif/hal/src/esp32/bootloader_init.c, boot/espressif/hal/src/esp32s2/bootloader_init.c, boot/espressif/port/esp32s2/ld/bootloader.ld, boot/espressif/port/esp_loader.c, boot/espressif/port/esp_mcuboot.c, boot/espressif/tools/toolchain-esp32s2.cmake
This PR adds basic support for ESP32-S2 SoC from Espressif Systems.
**Notes:** 
- Both Zephyr and NuttX RTOSes for ESP32-S2 would be able to boot in the future, however the changes in their respective repositories still are WIP and aren't upstream yet. 
- `git submodule update --init --recursive` (Update ESP-IDF submodule)
- `unset IDF_PATH` (Clear IDF_PATH variable if it is already set)
- `./boot/espressif/hal/esp-idf/install.sh` (Installs toolchain required to build application for ESP32)
- `. ./boot/espressif/hal/esp-idf/export.sh` (Adds required directories to PATH)
- `cd boot/espressif`
- `cmake -DCMAKE_TOOLCHAIN_FILE=tools/toolchain-esp32s2.cmake -DMCUBOOT_TARGET=esp32s2 -DIDF_PATH=$IDF_PATH -B build -GNinja`
- `cmake --build build/`
- `export ESPPORT=your-esp32-serial-port`
- …
=> ESP32-S2: Basic MCUboot support

sim/mcuboot-sys/Cargo.toml, sim/mcuboot-sys/build.rs
Depending on configuration, the simulator's mcuboot-sys crate either pulls files from `ext/mbedtls` or from `ext/mbedtls-asn1`, which is a few files extracted from the full Mbed TLS tree. However, there are now some configurations where the simulator ends up bringing in both sets of these files. In the current tests, the linker ends up arbitrarily choosing one of these. This also causes the cargo tests to fail when run directly in the `sim/mcuboot-sys` directory, as they are linked directly instead of through a library, and the compiler complains of duplicates.
Fix this by not using the asn1 copy in the simulator.
In addition, add a dummy feature for `large-write` to the mcuboot-sys crate so that all of this can be tested using ptest and having `ci/sim_run.sh` run in the mcuboot-sys …
=> Eliminate duplicate C files in mcuboot-sys

boot/zephyr/boards/mimxrt1020_evk.conf, boot/zephyr/boards/mimxrt1050_evk_qspi.conf
The mimxrt1020_evk and mimxrt1050_evk_qspi boards have large
slots so we need to increase CONFIG_BOOT_MAX_IMG_SECTORS from
the default.
Signed-off-by: Xabier Marquiegui <xmarquiegui@ainguraiiot.com>
=> boot: zephyr: Config mimxrt1020_evk and mimxrt1050_evk_qspi

boot/bootutil/include/bootutil/sign_key.h
`mcuboot_config.h` was not included from `sign_key.h`,
causing the wrong declaration of `bootutil_keys[]` to be used.
This caused:
```C
extern const struct bootutil_key bootutil_keys[];
```
to be used for the `MCUBOOT_HW_KEY` case, instead of:
```C
extern struct bootutil_key bootutil_keys[];
```
In the `MCUBOOT_HW_KEY` case, `bootutil_keys[]` cannot be const, because the pubkey loaded from the image TLV has to be stored in slot 0, after validating its SHA256 hash.
=> Include mcuboot_config.h from sign_key.h to fix MCUBOOT_HW_KEY option

boot/mynewt/mcuboot_config/include/mcuboot_config/mcuboot_config.h
Allow building ec256 signature validation on Mynewt using Mbed TLS. Related to https://github.com/apache/mynewt-artifact/pull/33
=> mynewt: remove #error on ec256 with Mbed TLS

scripts/imgtool.nix, scripts/imgtool/boot_record.py, scripts/requirements.txt, scripts/setup.py
The cbor module is unmaintained, with the last release in 2016[1]. The
cbor2 module however is under active development and was last released
just last month[2].
As the APIs are identical, we can import cbor2 and if that fails fall
back to cbor.
[1] https://pypi.org/project/cbor/#history
[2] https://pypi.org/project/cbor2/#history
Closes #1189
Signed-off-by: Ross Burton <ross.burton@arm.com>
Change-Id: Iaf2d0df625a200a5cebf72dec4a89877a26194ea
=> imgtool: prefer cbor2 over cbor

boot/espressif/CMakeLists.txt
This PR intends to make the build system prioritize the usage of `imgtool` installed on the system.
If `imgtool` is not found, then CMake will fallback to the current behavior of using the one from the repository.
The motivation for this change is due to NuttX build system relying on the `imgtool` installed via `pip`.
=> espressif: Allow use of imgtool other than the one from repository

.github/workflows/espressif.yaml, ci/espressif_install.sh, ci/espressif_run.sh
This PR intends to enable the CI build of the `espressif` port of MCUboot for the currently supported chips:
- ESP32
- ESP32-S2
- ESP32-C3
=> ci: Enable build of espressif port for supported chips

boot/bootutil/include/bootutil/bootutil.h, boot/bootutil/src/bootutil_priv.h, boot/bootutil/src/loader.c, sim/mcuboot-sys/csupport/run.c, sim/mcuboot-sys/src/c.rs, sim/src/image.rs, sim/tests/core.rs
Add new public API function to perform RAM_LOADING on a specific image. Designed to be used when only a subset of the images need to be loaded, or images need to be loaded in multiple stages.
In order to do this, change how `context_boot_go` handles state. It now doesn't clear the context when called. Add a new API function to clear this state so that external callers can still use `context_boot_go`. The semantics of `boot_go` are unchanged.
Also moves slot_usage into the bootloader state.
=> Add support for partial RAM_LOADING

boot/espressif/main.c, boot/espressif/port/esp_loader.c, boot/espressif/port/esp_mcuboot.c
This PR intends to make the logging infra on the Espressif port uniform to the bootutil library.
This PR also refines the include directives, by removing unused headers and making the usage of brackets and quotes a bit more coherent.
This PR brings no functional changes, so it shouldn't bring any impact.
CI build pass.
Also tested in every board supported by the Espressif port:
- ESP32
- ESP32-S2
- ESP32-C3
=> espressif: Use BOOT_LOG_* macros instead of the MCUBOOT_LOG_*

boot/zephyr/Kconfig
Facilitate extending the kconfig definition by adding names to all
choices.
=> kconfig: add name to choice option

boot/bootutil/src/loader.c, boot/zephyr/CMakeLists.txt, boot/zephyr/os.c
boot_copy_region() was written so it assumes that the image header
must fit int the intermediary buffer of 1 KB size. A bigger header
will cause a overflow in calculation of size of data chunk to be
decrypted.
This patch allow to use header bigger than that buffer size and
mitigate the limitation described above.
This patch was tested on zephyr nrf52840dk_nrf52840 with image headed size increased to 0x600.
It was done by simple modification i zephyr's Kconfig.zephyr file:
```Kconfig
config ROM_START_OFFSET
hex
prompt "ROM start offset" if !BOOTLOADER_MCUBOOT
default 0x600 if BOOTLOADER_MCUBOOT # <-was 0x200
default 0
help
```
fixes #1191
fixes #1200
=> loader: Allow image header bigger than 1 KB for encrypted images

sim/mcuboot-sys/Cargo.toml, sim/mcuboot-sys/src/api.rs, sim/mcuboot-sys/src/area.rs, sim/mcuboot-sys/src/c.rs, sim/simflash/src/lib.rs, sim/simflash/src/pdump.rs, sim/src/caps.rs, sim/src/depends.rs, sim/src/image.rs, sim/src/tlv.rs, sim/tests/core.rs
This allows boundary condition testing within the simulator, to make sure we handle the cases when the image is a large as it can possibly be.
This enables maximal images in those configurations where we are able to accurately determine what that image size is. For overwrite-only+large-write, the calculation is incorrect (and results in a negative image size), and for swap-move, it doesn't account for the padding sector needed for the move. For those, we just leave the current image sizes.
=> Enhance simulator to generate maximally sized images

boot/nuttx/src/flash_map_backend/flash_map_backend.c
Signed-off-by: Andres Sanchez <tito97_sp@hotmail.com>
Solve:
For GCC 4.9:
error: argument to 'sizeof' in 'memset' call is the same expression as the destination; did you mean to dereference it? [-Werror=sizeof-pointer-memaccess]
=> nuttx: solve referenciation error in memset call

boot/bootutil/src/loader.c, boot/zephyr/Kconfig, boot/zephyr/include/mcuboot_config/mcuboot_config.h
In a multi image context it is possible for a user to upload an image
to the wrong secondary slot. As the same key is used for both images
MCUboot will overwrite image 0 with a variant of image 1.
If direct overwrite is enabled it is not trivial to recover from this.
To mitigate this issue we introduce a check of the reset address within
the vector table.
If the reset address in the new image is not contained within the
primary slot the image is deemed incorrect and is deleted from the
secondary slot
=> loader: add checking of reset address

boot/boot_serial/src/boot_serial.c, boot/zephyr/include/mcuboot_config/mcuboot_config.h
**Implements:**
- Support for the STM32 Independent watchdog.
- Feeding of watchdog during serial recovery mode.
**Tested:**
- Tested with custom STM32L431KC board with and without watchdog enabled. Watchdog successfully kicks bootloader when in `FIH_PANIC`.
- Tested with serial communication. Watchdog is being fed and does not reset bootloader when in `boot_serial_start`, or while uploading new image.
=> boot: zephyr: stm32: watchdog support

boot/nuttx/include/flash_map_backend/flash_map_backend.h, boot/nuttx/include/mcuboot_config/mcuboot_logging.h, boot/nuttx/src/flash_map_backend/flash_map_backend.c
Signed-off-by: Petro Karashchenko <petro.karashchenko@gmail.com>
Solve:
For GCC 10.3:
```
warning: data definition has no type or storage class
#define BOOT_LOG_MODULE_DECLARE(module)  MCUBOOT_LOG_MODULE_DECLARE(module)
warning: format '%d' expects argument of type 'int', but argument 5 has type 'int32_t' {aka 'long int'} [-Wformat=]
syslog(LOG_INFO, "%s: " format "\n", __FUNCTION__, ##__VA_ARGS__)
warning: format '%zu' expects argument of type 'size_t', but argument 4 has type 'long unsigned int' [-Wformat=]
syslog(LOG_DEBUG, "%s: " format "\n", __FUNCTION__, ##__VA_ARGS__)
```
=> nuttx: fix compilation warnings

boot/zephyr/boards/mimxrt1024_evk.conf
The mimxrt1024_evk board have a large slot so we need
to increase CONFIG_BOOT_MAX_IMG_SECTORS from the default.
Signed-off-by: Mikkel Jakobsen <mikkel.aunsbjerg@prevas.dk>
=> boot: zephyr: configure mimxrt1024_evk board

boot/mynewt/src/main.c, boot/mynewt/syscfg.yml
Custom boot_preboot() function can be used to start
DFU in similar way as is already done in zephyr.
Proposed function name can be discussed if someone thinks it's inappropriate.
=> mynewt: Add call to custom pre-boot function

docs/design.md
`image-trailer-size` should be mentioned instead
of `image-trailer-sectors-size` in the maximal-image-size
evaluation description.
=> doc/design: fix typo in swap-using-scratch description

boot/boot_serial/src/boot_serial.c, boot/bootutil/include/bootutil/bootutil.h, boot/bootutil/src/bootutil_priv.h
Calculation of BOOT_SERIAL_OUT_MAX was based on MCUBOOT_IMAGE_NUMBER
while in other places BOOT_IMAGE_NUMBER is taken int account as
images number. Let's align the calculation to use same literal value
as others.
=> boot_serial: cleanup max output size calculation

boot/zephyr/include/mcuboot_config/mcuboot_config.h
Kconfig macro was converted with typo to not a MCUboot's
internal macro switch. It was MCBOOT_ERASE_PROGRESSIVELY instead
of MCUBOOT_ERASE_PROGRESSIVELY.
Bug was introduced in
https://github.com/mcu-tools/mcuboot/commit/42c985ceadecb61f77db016ebb64b21099c45f4a
=> zephyr: fix typo in CONFIG_ERASE_PROGRESSIVELY conversion

boot/zephyr/main.c
The nRF53 mcu has moved RESETREAS register
(from POWER to RESET peripheral).
This fix uses nrfx helper to select the proper register.
=> zephyr: Fix serial recovery skipping on nrf53

boot/zephyr/boards/mimxrt685_evk_cm33.conf
The mimxrt685_evk board has large slots so we need to increase
CONFIG_BOOT_MAX_IMG_SECTORS from the default.
Signed-off-by: Maureen Helm <maureen.helm@nxp.com>
=> boot: zephyr: Configure mimxrt685_evk board

sim/src/image.rs
Change the flash layout of the stm32f4 simulated device to include sectors of different sizes inside both slots; both slots have been updated to still share the same layout. This layout changes allow for testing and validation that a swap with scratch is possible even if not all sectors inside a slot are the same size, as long as they all fit in scratch.
=> sim: define stm32f4 with non-linear sectors slots

boot/bootutil/src/swap_misc.c
This PR intends to fix a possible resource leak due to `flash_area` left open after a read failure during `swap_read_status` function.
Issue identified during code inspection.
=> bootutil: Close flash_area after failure to read swap information

samples/zephyr/overlay-ecdsa-p256.conf, samples/zephyr/overlay-rsa.conf, samples/zephyr/overlay-skip-primary-slot-validate.conf
Change the configs for the Zephyr tests to use move swap, as this is the
code intended for future use.
=> samples: zephyr: Use move swap for Zephyr tests

sim/src/lib.rs
Fix warning running the simulator due to variables that are not being used anymore.
=> sim: Remove unused variables

boot/boot_serial/src/boot_serial.c
=> boot_serial: Fix Zephyr include path for reboot.h

sim/mcuboot-sys/build.rs
This feature check was done statically instead of dynamically in the
build.rs file.  Change this to match the rest.  Perhaps we might want to
change all of them to be done at compile time, but that should be done
with all of the features.
=> sim: Homogenize max-align-32 feature check

.github/workflows/espressif.yaml, .github/workflows/fih_tests.yaml, .github/workflows/imgtool.yaml, .github/workflows/mynewt.yaml, .github/workflows/sim.yaml
This PR intends to add a new action to GitHub CI to force running jobs of a given PR to be cancelled once the same branch is updated, avoiding the CI wasting time testing outdated content.
https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/
https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
=> ci: Define concurrency groups for cancelling duplicate jobs

boot/nuttx/main.c
Use syslog in favor of printf function for print messages. The syslog ensure that all characters are corrected flushed. Syslog is already used when log is enabled and this only switch to same log interface.
Signed-off-by: Gerson Fernando Budke <nandojve@gmail.com>
=> boot/nuttx: Switch from printf to syslog

boot/espressif/hal/CMakeLists.txt, boot/espressif/hal/include/soc_log.h
This PR intends to make use of the TAG field from `SOC_LOG*` macros used by some IDF components.
Besides making the log messages more intuitive, it also brings the benefit of removing the need for passing `-Wno-unused-variable` compiler flag, since now TAG is being used as part of the log message.
=> espressif: Use "TAG" field from SOC_LOG* macros from IDF libraries

.github/workflows/espressif.yaml, ci/espressif_run.sh
This PR intends to improve the Espressif port CI script for enabling a quick local validation that the build passes for multiple Espressif targets.
No impact to actual code, just for CI infra
On the host PC, build the Espressif port for the currently supported chips with:
```bash
MCUBOOT_TARGETS="esp32,esp32c3,esp32s2" \
MCUBOOT_FEATURES="sign-rsa2048,sign-rsa3072,sign-ec256,sign-ed25519" \
./ci/espressif_run.sh
```
=> espressif: Improve CI script for easing local validation

boot/zephyr/boot_serial_extensions.c
Use MCUboot logging macros instead of zephyr-rtos native.
This fixes build failure on MCUBOOT_LOG_MODULE_DECLARE() when
LOG is disabled.
=> zephyr/boot_serial_extension: us BOOT_LOG instead of LOG_

scripts/imgtool/image.py, scripts/imgtool/main.py
Create an option to generate a clear image with encryption capability that can be installed on a primary slot. Since image has encryption capability image can be swap and encrypted in secondary slot
Signed-off-by: Michel Jaouen <michel.jaouen@st.com>
=> imgtool: Add clear image generation with encryption capability

boot/zephyr/single_loader.c
Fixes compilation when VALIDATE_PRIMARY_SLOT & SINGLE_APPlICATION_SLOT are enabled.
Introduced by #1255 
Signed-off-by: Wouter Cappelle <wouter.cappelle@crodeon.com>
=> single_loader: zephyr: Fix compilation with VALIDATE_PRIMARY_SLOT enabled

README.md
This change is to avoid misunderstanding as IDF is not supported
on top of MCUboot.
The Espressif port acts as a bare metal bootloader that can be
used on Espressif chips to boot supported OSes (like Zephyr or NuttX).
Signed-off-by: Almir Okato <almir.okato@espressif.com>
=> readme.md: remove "IDF" from Espressif reference

scripts/imgtool/image.py, scripts/imgtool/main.py
The value of `--max-align` parameter passed to imgtool can never be
less than the value of `--align` parameter. At present the default
value of `--max-align` is fixed at 8. This forces user to pass the
parameter even when its value can be safely inferred.
Change the default value of the `--max-align` parameter to the larger
of the two values: `--align` or 8. Consequently, the user is required
to pass the parameter only if the flash alignment of the primary and
secondary slot differ.
=> imgtool: change --max-align default value

scripts/imgtool/image.py
When generating an image with trailer (--pad or --confirm), the
imgtool also adds the erased values into that area. This is not
wanted for flash drivers which use ECC and treat writing erased
values as a real write action, which cannot be overwritten anymore.
See issue #1288
For now the change in implementation is always to skip these in the trailer, but i'm not sure if this suits another purpose to still add these? I always can make an option in the tool not to change the current image generation. 
image trailer before change:
```
$ tail -n 4 zephyr/zephyr.encrypted.confirmed.signed.hex.original 
:020000040807EB
:10FFE000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF21
:10FFF00077C295F360D2EF7F3552500F2CB67980DF
:00000001FF
```
image trailer after change:
```
$ tail -n 4 …
```
=> imgtool: skip erased values in trailer generation

boot/boot_serial/include/boot_serial/boot_serial.h, boot/boot_serial/src/boot_serial.c, boot/zephyr/Kconfig, boot/zephyr/include/mcuboot_config/mcuboot_config.h, boot/zephyr/main.c
This PR adds the possibility to only enter the bootloader's
serial recovery mode when a mcumgr command is received within a
given timeout.
Signed-off-by: Wouter Cappelle <wouter.cappelle@crodeon.com>
This PR is the last part of the split off PR #989. The work has been done for Zephyr only (although should be easy to integrate in others).
=> boot_serial: zephyr: Add optional timeout to enter serial recovery

docs/readme-espressif.md
esptool and imgtool require additional information that is not clear
to end user.
It also update ESP32 status for Zephyr porting a table text alignment
Signed-off-by: Sylvio Alves <sylvio.alves@espressif.com>
=> doc: espressif: add parameter details for esptool and imgtool

boot/zephyr/single_loader.c
Decryption buffer was fixed to 1024 which imposes failure
while attempting to decrypt bigger image chunks, which is
expected on memories of bigger erase-block-size.
This patch attempt to get teh proper buffer size basing on
SOC's nv flash node.
fixes #1310
=> zephyr/single_loader: make decription working flash

boot/boot_serial/src/boot_serial.c
The buf buffer set to collect total console payload consisting
of total size (two bytes), SMP header (eigth bytes), data payload
(bs_obuf, BOOT_SERIAL_OUT_MAX) and CRC (two bytes), pior to base64
encoding has been set to size of BOOT_SERIAL_OUT_MAX.
This means that if output data len, in bs_obuf, would be longer than
BOOT_SERIAL_OUT_MAX - 8 - 2 - 2, then composing of the output buffer
would overflow.
=> boot_serial: Fix buffer overflow in boot_serial_out

boot/boot_serial/src/boot_serial_priv.h
=> boot_serial: Correct MGMT_ERR_EUNKNOWN value

boot/boot_serial/src/boot_serial.c, boot/boot_serial/src/boot_serial_priv.h
In case when echo string would be too long to fit into buffer,
there would be no space left for container termination.
Due to lack of error checking such non-terminated container would
be sent out, where error response should be sent out instead.
Depends on:
https://github.com/mcu-tools/mcuboot/pull/1321
https://github.com/mcu-tools/mcuboot/pull/1320
=> boot_serial: Fix SMP echo sending incomplete CBOR container

boot/espressif/hal/src/flash_encrypt.c, docs/index.md, docs/readme-espressif.md
This PR adds instructions on the readme-espressif.md on how to encrypt data on the host.
Adds configuration and instructions for disabling/switch UART ROM Download Mode, needed by host data encryption.
Also fix Espressif information on the docs index page to reflect the main readme.md.
=>  espressif: update Espressif documentation regarding secure features

.github/workflows/zephyr_build.yaml
During the workflow a Zephyr repository is checked out (by default
main, but any version can be given when workflow is triggered
manually) and west update is run according to Zephyr's manifest.
However, the MCUboot version is then replaced by checking out
MCUboot main (triggered by push or cron), PR's head (triggered by
a PR to MCUboot) or custom SHA (manual trigger). Next, twister is
called for tests/builds in locations given in the workflow
(test_paths).
Signed-off-by: Maciej Perkowski <Maciej.Perkowski@nordicsemi.no>
=> workflow: Add workflow verifing integration with the upstream Zephyr

docs/index.md
Documentation index fix for Espressif readme.
=> index.md: fix readme-espressif.md link

boot/zephyr/flash_map_extended.c, boot/zephyr/include/target.h, boot/zephyr/main.c
DT_CHOSEN_ZEPHYR_FLASH_CONTROLLER_LABEL is going to be deprecated, so
remove its usages from the Zephyr port. Definition checks have been
replaced with DT_HAS_CHOSEN(zephyr_flash_controller), and the macro
itself has been replaced by
DT_LABEL(DT_CHOSEN(zephyr_flash_controller)). Note that the code could
likely be refactored to make use of compile time device references, ie
use DEVICE_DT_GET, but that task has been left for the maintainers.
Ref. https://github.com/zephyrproject-rtos/zephyr/pull/44129
=> zephyr: remove deprecated DT_CHOSEN_ZEPHYR_FLASH_CONTROLLER_LABEL

boot/zephyr/main.c
see [issue #1330](https://github.com/mcu-tools/mcuboot/issues/1330)
Signed-off-by: Jim Tan <KuoChun.Tan@ite.com.tw>
=> zephyr: fix booting address incorrect in ram-load mode

scripts/imgtool/image.py, scripts/imgtool/main.py
The sign command was extended so it now allow to provide the signature
as base64 formatted RAW file using --fix-sig along with relevant public key
--fix-sig-pubkey.
This patch is added for support the case where the party which produces
the image dose not have access to the signing image key but must request
third party for the signature.
Possible steps for get an image sign are:
1. Generate the public key form the private key using openssl:
``` Console
openssl rsa -in ./bootloader/mcuboot/root-rsa-2048.pem -pubout -out root-rsa-2048-priv.pem -outform PEM -RSAPublicKey_out
```
2. Get the payload against to which the  signature should be generated:
``` console
./bootloader/mcuboot/scripts/imgtool.py sign -v 1.0.0 -H 0x200 -S 0x67000 --align 8  --fix-sig-pubkey ./root-rsa-2048-priv.pem …
```
=> imgtool: Added support for providing the signature by 3rd party

boot/espressif/include/esp_loader.h, boot/espressif/main.c, boot/espressif/port/esp32/ld/bootloader.ld, boot/espressif/port/esp_loader.c
Entry point call was moved back from main to esp_loader, so it is called from iram_loader_seg memory region.
=> espressif:esp32: Move app entry point call back to iram_loader_seg region

boot/bootutil/src/bootutil_public.c
Hi!
Thank you for your work!
While working with the project I found that `boot_enc_key_off`function is not used in boot/bootutil/src/bootutil_public.c. It seems code was move to bootutil_misc.c but this function was forgotten.
=> Remove unused function

README.md, docs/index.md
Fix the case of the cypress readme to fix dead links in the docs.
=> docs: Fix case of Cypress readme file

scripts/imgtool/image.py
Using imgtool sign command without a key was resulting the following error:
`Error: Can not sign using key and provide fixed-signature at the same time`
Neither a key nor fixed signature were being used.
The fix adds a condition that checks if either `key` or `fixed_sig` are `not None` before payload signing and TLV addition.
=> imgtool: Fix imgtool sign command without key

boot/zephyr/boards/tlsr9518adk80d.conf
Add support for TLSR9518ADK80D board, which have large flash
sizes and require an increase to the value of BOOT_MAX_IMG_SECTORS
Signed-off-by: Alex Kolosov <rikorsev@gmail.com>
=> zephyr: boards: add support for Telink tlsr9518adk80d board

boot/bootutil/zephyr/CMakeLists.txt
This fixes a build issue when building mcuboot for zephyr with image
encryption support enabled using tinycrypt.
Fixes https://github.com/mcu-tools/mcuboot/issues/1356
Note that the build will not succeed after this due to the `boot_nv_security_counter_update` function being unresolved, but it fixes the compilation error when searching for tinycrypt files.
=> bootutil: zephyr: Fix not including tinycrypt path when needed

boot/zephyr/main.c
The Cache is an optional configuration of both the ARM Cortex-M7 and
Cortex-M55. Previously, it was just checking that it was just an M7
rather than knowing that the CPU actually was built with the cache.
This just follows the pull request into zephyr https://github.com/zephyrproject-rtos/zephyr/pull/44815
Signed-off-by: Ryan McClelland ryanmcclelland@fb.com
=> boot: zephyr: add Kconfig for arm cortex-m that implements a cache

boot/bootutil/zephyr/CMakeLists.txt
This fixes a build issue when building mcuboot for zephyr with RSA
image encryption support enabled using mbedtls.
Fixes https://github.com/mcu-tools/mcuboot/issues/1355
=> bootutil: zephyr: Fix not linking with mbedtls when needed

boot/zephyr/boards/tlsr9518adk80d.conf
License header has been written in wrong format. It is fixed in this commit.
Signed-off-by: Alexandr Kolosov <rikorsev@gmail.com>
=> zephyr: boards: fix license header for tlsr9518adk80d board

scripts/imgtool/main.py
When I do command ``./imgtool.py sign -h``, there are some sentences display as below:
So I add space and dot to suit the display as:
=> add extra space or dot symbol to suite display.

boot/zephyr/main.c
bootloader-led0 alias will be deprecated and replaced by dedicated
mcuboot-led0 alias.
This is in response to suggestion for making MCUboot's DT aliases naming more consistient.
see: https://github.com/zephyrproject-rtos/zephyr/pull/44741#pullrequestreview-985471844
PR which introduces the `mcuboot-led0` alias: https://github.com/zephyrproject-rtos/zephyr/pull/44741
=> zephyr: prefer DTS mcuboot-led0 alias over bootloader-led0 alias

boot/bootutil/src/boot_record.c
Add a check for the size of the TLV entry for the boot record.
Although, this is in the protected area, and should be protected by a
signature, check that we don't induce an integer underflow if that entry
is somehow too short.
=> boot: Check that hash TLV is sufficiently large

boot/zephyr/Kconfig, boot/zephyr/Kconfig.serial_recovery, boot/zephyr/main.c
Added support for configure GPIO-pin used for triggering the
recovery DFU using DTS. That pin is assigned thanks to
`mcuboot-button0` pin-allias.
DTS configuration takes precedence over the Kconfig pin configurations.
Kconfig hw pin properties get deprecated.
This patch reduces technical debt against zephyr-rtos we have.
fixes #965
~~[PR for introduce bootloader-button0 alias to the zephyr-rtos](https://github.com/zephyrproject-rtos/zephyr/pull/44741)~~ [Merged]
=> zephyr/main: configure DFU detection GPIO-pin using DTS

boot/mynewt/syscfg.yml
BOOT_CUSTOM_START is defined by APP package (here).
This changes default value from 0 to empty
to allow for constructing packege that provides function
boot_custom_start() and automatically sets BOOT_CUSTOM_START to 1
for easy setup.
Signed-off-by: Jerzy Kasenberg <jerzy.kasenberg@codecoup.pl>
=> mynewt: Allow custom boot to be provided by pkg

boot/mynewt/mcuboot_config/include/mcuboot_config/mcuboot_config.h, boot/mynewt/mcuboot_config/syscfg.yml
There is code for sharing data between booloader and application.
So far only zephyr had config flags to enable this.
This adds configuration that allows to turn on data sharing code
in mynewt version.
Signed-off-by: Jerzy Kasenberg <jerzy.kasenberg@codecoup.pl>
=> boot: mynewt: Add boot data sharing config

boot/zephyr/include/config-ec.h, boot/zephyr/include/config-ed25519.h, boot/zephyr/include/config-rsa-kw.h, boot/zephyr/include/config-rsa.h
According to mbedTLS' Changelog "Mbed TLS 3.0.0 branch released
2021-07-07" -> "Removals":
```
MBEDTLS_ECP_MAX_BITS is no longer a configuration option because it
is now determined automatically based on supported curves.
```
Link: https://github.com/Mbed-TLS/mbedtls/blob/4ccd226cbf087ee78b443e452200dd0486527658/ChangeLog#L435
Hence remove MBEDTLS_ECP_MAX_BITS from configuration files to fix build
issues with Zephyr when there is unfortunate order of include
statements, like:
```
/__w/zephyr/zephyr/modules/mbedtls/zephyr_init.c
In file included from /__w/zephyr/modules/crypto/mbedtls/include/mbedtls/ssl.h:30,
from /__w/zephyr/modules/crypto/mbedtls/include/mbedtls/debug.h:27,
from /__w/zephyr/zephyr/modules/mbedtls/zephyr_init.c:16: …
```
=> zephyr: remove MBEDTLS_ECP_MAX_BITS from mbedTLS configs

boot/boot_serial/test/src/testcases/boot_serial_upload_bigger_image.c
repos/mcuboot/boot/boot_serial/test/src/testcases/
boot_serial_upload_bigger_image.c: In function
‘TEST_CASE_boot_serial_upload_bigger_image’:
repos/mcuboot/boot/boot_serial/test/src/testcases/
boot_serial_upload_bigger_image.c:91:42: error:
‘Value8Bit’ undeclared (first use in this function)
91 | buf[payload_off + len - 2] = Value8Bit;
| ^~~~~~~~~
=> boot_serial: Fix Mynewt tests compilation

boot/boot_serial/src/zcbor_decode.c
repos/mcuboot/boot/boot_serial/src/zcbor_decode.c:341:52: error:
dangling pointer ‘result’ to ‘dummy’ may be used
[-Werror=dangling-pointer=]
341 |         state->payload_end = result->value + result->len;
|                                              ~~~~~~^~~~~
repos/mcuboot/boot/boot_serial/src/zcbor_decode.c:325:37: note: ‘dummy’
declared here
325 |                 struct zcbor_string dummy = {};
|                                     ^~~~~
repos/mcuboot/boot/boot_serial/src/zcbor_decode.c:341:36: error:
dangling pointer ‘result’ to ‘dummy’ may be used
[-Werror=dangling-pointer=]
341 |         state->payload_end = result->value + result->len;
|                              ~~~~~~^~~~~~~
repos/mcuboot/boot/boot_serial/src/zcbor_decode.c:325:37: note: ‘dummy’
declared here
325 | …
=> boot_serial: Fix compilation due to danling pointer

boot/zephyr/boards/mimxrt1160_evk_cm7.conf, boot/zephyr/boards/mimxrt1170_evk_cm7.conf
add support for RT1170 and RT1160 CM7 cores, which have large flash
sizes and require an increase to the value of BOOT_MAX_IMG_SECTORS
Signed-off-by: Daniel DeGrasse <daniel.degrasse@nxp.com>
=> zephyr: boards: add support for RT1160 and RT1170 CM7 cores

boot/boot_serial/src/boot_serial.c, boot/boot_serial/src/serial_recovery_cbor.c, boot/espressif/CMakeLists.txt, boot/espressif/hal/CMakeLists.txt, boot/espressif/hal/include/mcuboot_config/mcuboot_config.h, boot/espressif/hal/src/esp32/bootloader_init.c, boot/espressif/include/serial_adapter/serial_adapter.h, boot/espressif/main.c, boot/espressif/port/esp32/bootloader.conf, boot/espressif/port/esp_mcuboot.c, boot/espressif/serial_adapter.c, docs/readme-espressif.md
This MR adds the serial adapter for ESP32 for boot recovery and MCUMGR communication.
The serial mode feature also demanded changes on flash_area_write for aligned writing.
=>  boot_serial: espressif: ESP32 serial recovery mode interface

boot/boot_serial/src/boot_serial.c
Hi, the Zephyr project moved all the headers into a "zephyr/" subdirectory some time ago, right now both works but we are in the process of deprecating the old format. This change makes mcuboot works with the new one.
--- 8< ---
Add relevant "zephyr/" prefixes to allow building with the Zephyr
option CONFIG_LEGACY_INCLUDE_PATH=n.
=> boot_serial: add "zephyr/" prefix to __ZEPHYR__ includes

boot/zephyr/main.c
Zephyr upstream removed its legacy v1 logging framework in https://github.com/zephyrproject-rtos/zephyr/commit/c5f2cde and removed the parameter in `log_process`.
This PR aims to make MCUboot compatible with most recent Zephyr again, maintaining compatibility with previous releases.
The first commit only fixes some indentation.
=> zephyr: fix logging compatibility

boot/zephyr/flash_map_extended.c, boot/zephyr/include/flash_map_backend/flash_map_backend.h, boot/zephyr/include/target.h, boot/zephyr/main.c
remove flash_device_get_binding as we can utilizes DEVICE_DT_GET to
get the flash_dev pointer set at build time.  This removes usage of
device_get_binding and handles the lack of 'label' properties in
the devicetree better.
Signed-off-by: Kumar Gala <galak@kernel.org>
=> zephyr: remove flash_device_get_binding

boot/zephyr/include/mcuboot_config/mcuboot_config.h
Add possibility to pass generic watchdog alias no matter what vendor is used.
Signed-off-by: Bartosz Bilas <b.bilas@grinn-global.com>
=> boot: zephyr: add support for generic watchdog alias

boot/boot_serial/src/boot_serial.c
The `BOOT_LOG_INF` function, which uses the format specifiers defined
by the C standard, was incorrectly printing a variable with the type of
`off_t` using the `%x` format specifier, which is intended to be used
with the `int` type.
The `off_t` type, specified by the POSIX standard, is not guaranteed to
be `int`, and it may be defined as `long` or `long long` depending on
the toolchain and the target architecture.
This commit updates the print routine such that it casts the arguments
of the `off_t` type to `intmax_t` and prints them out using the
corresponding `%jx` format specifier.
Signed-off-by: Stephanos Ioannidis <root@stephanos.io>
=> boot_serial: Fix incorrect format specifier for off_t

boot/zephyr/include/mcuboot_config/mcuboot_config.h
Replace the `device_get_binding` usage with a `DEVICE_DT_GET` which is being deprecated in the upstream zephyr.
Signed-off-by: Bartosz Bilas <b.bilas@grinn-global.com>
=> boot: zephyr: get rid of device_get_binding for stm32 watchdog

boot/zephyr/boards/nrf52840_big.overlay, boot/zephyr/usb_cdc_acm.overlay
zephyr is transition away from devicetree label property for nodes
that are associated with devices.  So remove it from
"zephyr,cdc-acm-uart" nodes.
Signed-off-by: Kumar Gala <galak@kernel.org>
=> zephyr: Remove devicetree 'label' property

boot/boot_serial/src/boot_serial.c
If `BOOT_SERIAL_WAIT_FOR_DFU` is selected, the CPU shouldn't enter idle state, waiting for interrupt from the console because we expect booting if no mcumgr command is received within a configured timeout (with the `CONFIG_BOOT_SERIAL_WAIT_FOR_DFU_TIMEOUT`). Without this fix, when using `BOOT_SERIAL_WAIT_FOR_DFU` the boot process hangs forever, waiting for input from console.
This fixes original commit where optional timeout support in serial recovery was included: e3822f8180ed.
=> boot_serial: fix serial recovery mode with timeout

boot/boot_serial/src/boot_serial.c
This is continuation of #1433 and only adds short explanation (in form of a comment) why CPU shouldn't enter idle state in timeout based serial recovery.
References:
- 3942e9bf8f60 ("boot_serial: fix serial recovery mode with timeout")
- #1433
- https://github.com/mcu-tools/mcuboot/pull/1433#issuecomment-1213043842
CC: @nvlsianpu
=> boot_serial: explain disabled idle state in timeout based recovery

boot/zephyr/boards/nrf52840dk_ram.overlay, boot/zephyr/boards/nrf52840dk_ram_multi.overlay
zephyr is transition away from devicetree label property for nodes
that are associated with devices.  So remove it from flash nodes.
Signed-off-by: Kumar Gala <galak@kernel.org>
=> zephyr: Remove devicetree 'label' property from flash nodes

scripts/imgtool/image.py
This PR fixes https://github.com/mcu-tools/mcuboot/issues/1444
=> imgtool: Fix output of confirmed image in HEX format

boot/nuttx/include/flash_map_backend/flash_map_backend.h
Update flash_map_backend.h to be compatible with a C++ compiler
Signed-off-by: Andrés Sánchez Pascual <tito97_sp@hotmail.com>
Signed-off-by: GitHub <noreply@github.com>
=> Update for C++ compiler compatibility

boot/zephyr/include/mcuboot_config/mcuboot_config.h
This PR adds support STM32 devices with 32byte flash write alignment. Possible after [#1217](https://github.com/mcu-tools/mcuboot/pull/1217)
**Does it work**
Why yes! I tested with a `nucleo_h743zi` with the following steps:
- Built and flashed the adapted bootloader. Built two
- Built two demo applciations with bootloader support. Signed them by omitting `--align` so it automatically detects to use `32`.
- Flash two demo applications. 
- MCUBoot detects the correct magic in the second slot, and does a succesful swap.
**Old Behaviour:**
The STM32H7 device only supports writing to flash at a 32byte alignment. However, currently `BOOT_MAX_ALIGN` will always be set to `8` for a Zephyr build. This means the bootloader will not find the correctly signed image's magic number, because it's …
=> zephyr: flash: support 32byte block write size

.github/workflows/zephyr_build.yaml
Updates the CI workflows to use the Zephyr SDK 0.15.0 and CI image 0.24.2 for building and testing Zephyr in the CI.
Signed-off-by: Bartosz Bilas <bartosz.bilas@hotmail.com>
=> ci: bump zephyr ci image and sdk

boot/zephyr/include/mcuboot_config/mcuboot_config.h
Return the device pointer if the node identifier refers to a watchdog node with status “okay”, otherwise return NULL.
Signed-off-by: Bartosz Bilas <bartosz.bilas@hotmail.com>
=> boot: zephyr: return NULL if stm32 watchdog is not enabled

boot/bootutil/src/loader.c
boot_remove_image_from_flash has been missing flash_area_close.
=> bootutil: Add missing flash_area_close

boot/zephyr/Kconfig, boot/zephyr/include/mcuboot_config/mcuboot_config.h
Since we have support for nRF and STM32 families, and non-vendor watchdog implementation let's enable this functionality by default. Imply NRFX_WDT && NRFX_WDT0 && NRFX_WDT1 only when SOC_FAMILY_NRF is being used.
Signed-off-by: Bartosz Bilas <bartosz.bilas@hotmail.com>
=> boot: zephyr: enable watchdog feed by default

boot/zephyr/flash_map_extended.c
Adds missing bracket to the xtensa node exists condition.
=> boot: zephyr: fix xtensa define condition

boot/zephyr/sample.yaml
Building sample.bootloader.mcuboot for many platforms is not possible (for instance a qemu). The limit is need as otherwise zephyr-rtos/zephyr CI is failing on any push to main branch or nightly CI run.
This patch is mirror of what went into `zephyr-rtos/mcuboot` yet. It is needed for consistency.
=> zephyr/sample.yaml Limit allowed build platforms

boot/bootutil/src/loader.c
Currently the post copy hook is only called from the `copy_region` function. However when another update method than `BOOT_UPGRADE_ONLY` is selected this function is not called. This adds post copy hook to the end of `boot_swap_image` when we know the swap is complete.
Signed-off-by: Sigvart Hovland <sigvart.hovland@nordicsemi.no>
=> bootutil: loader: Add post copy hook to swap function

docs/encrypted_images.md, scripts/imgtool/keys/ecdsa.py, scripts/imgtool/keys/general.py, scripts/imgtool/keys/rsa.py, scripts/imgtool/keys/x25519.py, scripts/imgtool/main.py
Update `getpub` with new `lang` option, "pem", which allows exporting a public key as a PEM file. This can later be distributed to be used for encrypting an image, and gets away with having to use openssl for this step.
=> imgtool: add option to export public PEM

boot/zephyr/Kconfig
This property should be enabled by default only when watchdog driver is available.
This fixed build with pristine configuration on targets with CONFIG_WATCHDOG=n.
mirror PR https://github.com/zephyrproject-rtos/mcuboot/pull/92
=> zephyr/Kconfig: fixed BOOT_WATCHDOG_FEED default value

docs/encrypted_images.md, scripts/imgtool/main.py
Update a previous PR were PEM exporting was added to the `--lang` parameter, even though PEM is not a source code language per se.
This PR adds `--encoding/-e` to `getpub` command, for exporting in formats other than a language source code. `--lang` is left with a deprecation message, so it could be removed in a future version. The default behavior of exporting source code in C was preserved.
=> [RFC] imgtool: change getpub exporting format parameter

boot/zephyr/main.c
main.c uses CMSIS functions such as __set_MSP, which require
cmsis.h to be included. Up until now, that file was included
indirectly through other ARM headers. This patch explicitly
includes cmsis.h, for platforms on which those indirect includes
do not work.
Signed-off-by: Yonatan Schachter <yonatan.schachter@gmail.com>
=> zephyr: Explicitly include cmsis.h

boot/bootutil/src/bootutil_misc.c, boot/bootutil/src/bootutil_priv.h, boot/bootutil/src/image_validate.c, sim/src/image.rs, sim/tests/core.rs
It is possible that image in the slot is so big
that MCUboot swap metadata will interfere with
its content during the swap operation.
This patch introduces additional check to the image
validation procedure.
added `oversized_bootstrap` test for ensure that too big image will be rejected while bootsraping
added `oversized_secondary_slot` test for ensure that too big image upgrade attempt will be rejected. I doesn't work for `max-align-32` feature due to not precise operations on flash image in sim code. Fixing of this problem is out of scope for this PR.
Objective is to fix issue signaled by #1146
this patch is also successor of #1140
=> boot: add precise check of the image size

boot/zephyr/main.c
Enable ram loading for ARM, with correct handling of vector table when
code has moved to RAM.
Signed-off-by: Daniel DeGrasse <daniel.degrasse@nxp.com>
=> boot: zephyr: enable ram load for ARM

boot/boot_serial/src/boot_serial.c
boot_serial.c is using Zephyr Kernel APIs without including kernel.h.
Signed-off-by: Gerard Marull-Paretas <gerard.marull@nordicsemi.no>
=> boot: serial: add missing Zephyr kernel.h include

docs/readme-zephyr.md
Zephyr-port has switched to use DT node labels instead of label properties for partition assignment.
Also usage of west is recommended way to work with the project.
Documentation was actualized to reflect these principles.
=> doc/readme-zephyr:

zephyr/module.yml
Follow Zephyr v3.2.0 new recommendation to explicitly set module names to enable usage of ZEPHYR_<module-name-upper>_MODULE_DIR by other modules.
Verification:
1. (Pass) west build -p always -b nrf52840dk_nrf52840 bootloader/mcuboot/boot/zephyr/
2. (Pass) ./zephyr/scripts/twister --testsuite-root zephyr/tests/subsys/dfu/
3. (Pass) ./zephyr/scripts/twister --testsuite-root zephyr/samples/subsys/mgmt/mcumgr/smp_svr/
4. (Pass) ./zephyr/scripts/twister --testsuite-root bootloader/mcuboot/boot/zephyr/
Fixes #1491
Signed-off-by: Gregory Shue <gregory.shue@legrand.com>
=> Explicitly set module name in `zephyr/module.yml`

west.yml
Extending mcuboot to be a Zephyr manifest-module enables mcuboot integration consistent with Zephyr's example-application.
Fixes #1496
Signed-off-by: Gregory Shue <gregory.shue@legrand.com>
=> Add west.yml to make manifest-module.

boot/nuttx/src/flash_map_backend/flash_map_backend.c
Signed-off-by: Andrés Sánchez Pascual <tito97_sp@hotmail.com>
Fix compiler error: comparison of integer expressions of different signedness: 'off_t' {aka 'long int'} and 'uint32_t' {aka 'long unsigned int'} [-Werror=sign-compare]
492 |   if (seekpos != off)
=> boot:nuttx: Fix sign-comparsion issue

boot/nuttx/include/mcuboot_config/mcuboot_config.h, boot/nuttx/include/watchdog/watchdog.h, boot/nuttx/main.c, boot/nuttx/src/watchdog/watchdog.c
Signed-off-by: Andrés Sánchez Pascual <tito97_sp@hotmail.com>
**Rationale:**
Wdg timer set up and starting is an application specific action that should be performed at application level inside the main() funcion.
**Tested**
Tested on target.
=> boot: nuttx: Support application specific wdg initialization.

boot/boot_serial/src/boot_serial.c, boot/espressif/hal/include/esp32s2/esp32s2.cmake, boot/espressif/hal/src/esp32s2/bootloader_init.c, boot/espressif/hal/src/esp32s3/bootloader_init.c, boot/espressif/port/esp32s2/bootloader.conf, boot/espressif/port/esp32s2/ld/bootloader.ld, boot/espressif/port/esp32s2/serial_adapter.c, boot/espressif/port/esp32s3/bootloader.conf, boot/espressif/port/esp32s3/ld/bootloader.ld, boot/espressif/port/esp32s3/serial_adapter.c, docs/readme-espressif.md
This MR adds the serial adapter for ESP32-S2 and ESP32-S3 for boot recovery and MCUMGR communication.
Note: the Espressif CRC call on boot_serial.c was changed due to chip compatibility (ESP32-S2 needed a different implementation).
=> boot_serial: espressif: add serial recovery mode to ESP32-S2 and ESP32-S3 

boot/zephyr/Kconfig
With the exception of nrf targets `BOOT_SWAP_USING_SCRATCH` mode was still the preferred algorithm.
Changing the preferred mode in cases where no `scratch_partition` is defined will allow successfully building mcuboot for such boards without the need for any board specific overlays.
=> boot: zephyr: prefer swap move if scratch_partition not enabled

boot/nuttx/src/flash_map_backend/flash_map_backend.c
Fix the warning reported here:
https://github.com/apache/incubator-nuttx-apps/actions/runs/3455216080/jobs/5767096531
=> Fix error: format '%u' expects argument of type 'unsigned int', but argument 5 has type 'uint32_t'

scripts/imgtool/image.py
`--vector-to-sign` only exports the image payload, or digest, to be signed externally; it doesn't require any keys to be provided. This commit moves the code outside a key required block, after the payload and digest were already calculated from "image + headers + protected TLVs".
=> imgtool: fix --vector-to-sign usage

boot/bootutil/src/image_validate.c
The return value of bootutil_find_key is used as the key_id in the bootutil_img_validate function, and negative key_id value used in case of errors. If MCUBOOT_HW_KEY is set, than the key hash is read by boot_retrieve_public_key_hash function, but the exceptation is only to return nonzero on failure, so its error code should not be propagated up to the caller. Instead, bootutil_find_key should return -1 in case of a platform error.
Change-Id: I8e2bd12a5cf53787e10ae45c2ab556e8a856692d
Signed-off-by: Mark Horvath <mark.horvath@arm.com>
=> bootutil: Fix bootutil_find_key return value

boot/boot_serial/src/boot_serial.c
Fixes an issue whereby rc is a signed variable but is returned as an unsigned variable in the zcbor functions.
Fixes #1537
=> boot_serial: Fix rc not being returned as a signed value

boot/boot_serial/src/boot_serial.c, boot/zephyr/Kconfig.serial_recovery, boot/zephyr/include/mcuboot_config/mcuboot_config.h
There are 3 levels of buffers and only the first one seems to be configurable, this fixes that issue.
Fixes #1535
I don't know if 512 is a minimum so have only allowed changing the size if a larger value is set
=> boot_serial: Allow using a buffer larger than 512 bytes

ext/nrf/cc310_glue.c, ext/nrf/cc310_glue.h
Nordic had changed its license identifier to new more accurate id: LicenseRef-Nordic-5-Clause.
Old identifiers should be updated.
=> boot: Update Nordic's license identifier tag

boot/espressif/hal/include/mcuboot_config/mcuboot_config.h, boot/espressif/port/esp32/bootloader.conf, boot/espressif/port/esp32c3/bootloader.conf, boot/espressif/port/esp32s2/bootloader.conf, boot/espressif/port/esp32s3/bootloader.conf, docs/readme-espressif.md
This PR adds MCUboot downgrade prevention feature to Espressif chip's config files.
=> espressif: add downgrade prevention feature

boot/zephyr/boards/nrf52840dk_qspi_nor_secondary.overlay
Fixes an issue with a node which has been removed from zephyr.
Zephyr PR: https://github.com/zephyrproject-rtos/zephyr/pull/52028
Scratch partitions have been removed from upstream nordic boards, therefore the area no longer needs to be removed by the nrf52840dk overlay because it no longer exists
=> boot: zephyr: boards: nrf52840dk: Fix overlay

boot/boot_serial/src/boot_serial.c, boot/zephyr/Kconfig.serial_recovery, boot/zephyr/include/mcuboot_config/mcuboot_config.h
Fixes a bug when writing to devices which have memory alignment requirements with data being using directly from a zcbor-response whereby the alignment of the buffer data does not meet the requirements of the flash driver.
Fixes #1532
=> serial recovery: Add unaligned stack buffer writing

boot/mynewt/flash_map_backend/include/flash_map_backend/flash_map_backend.h, boot/mynewt/flash_map_backend/src/flash_map_extended.c, ci/mynewt_targets/swap_move/pkg.yml, ci/mynewt_targets/swap_move/syscfg.yml, ci/mynewt_targets/swap_move/target.yml
Add Mynewt build configuration with swap move enabled to the CI. Fixes the Mynewt build using swap move, by adding the `flash_sector` struct and functions used to calculate the maximum image size.
The implementation was tested on nrf52840dk and b-l475e-iot01a.
Fixes #1567
=> Fix Mynewt with swap move

scripts/imgtool/keys/ecdsa.py, scripts/imgtool/keys/ed25519.py, scripts/imgtool/keys/privatebytes.py, scripts/imgtool/keys/rsa.py, scripts/imgtool/keys/x25519.py, scripts/imgtool/main.py
A previous change was added to allow the `getpriv` command to dump ec256 keys in both openssl and pkcs8. That PR did not touch other key file types which resulted in errors using that command with RSA, X25519, etc.
This commit generalizes the passing of the `format` parameter, so each key type can decide which format it allows a dump to be produced in, and what default to use.
Fixes #1529
=> imgtool: fix getpriv format type for keys

boot/zephyr/main.c
Only call sys_clock_disable when the system clock driver support this feature.
Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>
=> boot: zephyr: Only call sys_clock_disable when supported

boot/zephyr/Kconfig.serial_recovery
This makes it possible to enable timeout (`BOOT_SERIAL_WAIT_FOR_DFU`) mode for the serial recovery when using `CDC ACM` based serial device. This was runtime tested on `nRF52840-Dongle`.
=> boot: zephyr: allow timeout based recovery with CDC ACM

boot/espressif/hal/include/esp32s3/esp32s3.cmake, boot/espressif/hal/src/esp32s3/app_cpu_start.c, boot/espressif/port/esp32s3/ld/bootloader.ld
Add missing function for starting the APP CPU when booting the second image (multi image).
=> espressif:ESP32-S3: Fix multiboot APP CPU start

boot/bootutil/src/swap_move.c
Fix a swap corruption which occurs on the swap move algorithm when a reset happens exactly at the point after the last move up, and its status update. On restart the image headers should be read at the 2nd sector of the primary slot, but due to lacking initialization it is read on the first sector, and then fails. This error was masked on the simulator because of the use of a global variable, which retained its value on a "reset simulation".
Fixes #1588
=> bootutil: fix swap with move reset issue

boot/zephyr/boards/mimxrt595_evk_cm33.conf
Add support for RT595 to MCUBoot. A larger number of max sectors is required due to the large flash size present on the RT595 EVK.
Signed-off-by: Daniel DeGrasse <daniel.degrasse@nxp.com>
=> boot: zephyr: add support for RT595

boot/bootutil/src/bootutil_misc.c, boot/bootutil/src/bootutil_priv.h, boot/zephyr/include/sysflash/sysflash.h
Scratch is not used when MCUBOOT_SINGLE_APPLICATION_SLOT  is used but definition of FLASH_AREA_IMAGE_SCRATCH has been required anyway because it would be default algorithm if nothing else has been selected.
=> Remove MCUBOOT_SWAP_USING_SCRATCH being set when MCUBOOT_SINGLE_APPLICATION_SLOT has been selected

docs/index.md
The relative links do not work on the docs website due to the files not living in the docs/ directory. This updates to link directly to the GitHub source so that users are not dropped onto a 404 page.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
=> Use full links for Cypress and Sim usage instructions

boot/cypress/cy_flash_pal/cy_flash_map.c, boot/cypress/cy_flash_pal/include/flash_map_backend/flash_map_backend.h, boot/mbed/include/flash_map_backend/flash_map_backend.h, boot/mbed/src/flash_map_backend.cpp, boot/zephyr/flash_map_extended.c, boot/zephyr/include/flash_map_backend/flash_map_backend.h, sim/mcuboot-sys/csupport/storage/flash_map.h
The function has not been in use and some ports have not been implementing it anyway.
=> flash_map_backend: Remove flash_area_id_to_image_slot

boot/zephyr/Kconfig.serial_recovery, boot/zephyr/serial_adapter.c
This allows making the number of receive buffers configurable instead of being fixed at 2.
Fixes some confusing Kconfig values to have values that make sense for the underlying SMP transport.
With this configuration, upload speeds of 17.7KiBps have been observed with USB-CDC recovery on an nRF52833 device with `CONFIG_BOOT_LINE_BUFS` set to 16 and `CONFIG_BOOT_SERIAL_MAX_RECEIVE_SIZE` set to 2048 with a custom MCUmgr application - which is over twice as fast as was possible without a configurable number of receive buffers.
=> zephyr: serial_recovery: Make receive buffers configurable

ci/fih-tests_run.sh
So far the FIH CI job was fetching a WIP change from TF-M Gerrit to align the MCUboot and TF-M from the FIH library point of view. This change is replacing to fetch the final version instead of the WIP change.
=> ci: Update TF-M version to be aligned with FIH library changes

boot/bootutil/src/bootutil_misc.c, boot/bootutil/src/bootutil_misc.h, boot/bootutil/src/bootutil_public.c
The commit moves static common functions that have duplicate definitions in bootutil_public.c and bootutil_misc.c to header file to be included by both files.
=> bootutil: Move duplicate static inline functions to one header

ci/check-signed-off-by.sh
Dependabot uses different e-mails for signoff and commit.
=> ci: Skip sign-off checks for dependabot

scripts/imgtool/keys/ed25519.py
Verify mode already works for the public halves of RSA and ECDSA keypairs. This patch corrects an apparent oversight, enabling that functionality in the Ed25519 and X25519 family.
=> imgtool: allow verify mode to use public ed25519 & x25519 keys

boot/bootutil/include/bootutil/fault_injection_hardening.h
The current FIH_DECLARE macro would cause static check failure if the variable is reassigned in the code before using the initial value.
=> FIH: Fix possible static check error caused by FIH_DECLARE

boot/zephyr/Kconfig
This changes the default mcuboot configuration for zephyr applications to clean up before booting the user application. The reason for this change is that mcuboot may configure protection (e.g. MPU stack guard) which is then used by the user application during its startup code prior to cleaning the configuration up, this can lead to a unbootable application and potentially irrecoverable module, therefore cleaning up is now being enabled by default.
Fixes #1634
=> boot: zephyr: Clean up before chainloading by default

boot/bootutil/src/bootutil_misc.c, boot/bootutil/src/bootutil_priv.h, boot/bootutil/src/loader.c, boot/bootutil/src/swap_move.c
Modifies boot_read_swap_size and boot_read_enc_key to use
flash_area object pointer instead of image index.
Depends on https://github.com/mcu-tools/mcuboot/pull/1601
=> bootutil: Pass flash_area to boot_read_swap_size

ext/nrf/cc310_glue.c, ext/nrf/cc310_glue.h
This fixes the issue: #1624 by changing the license to Apache-2. There isn't a need to have these files nordic licensed.
=> nrf: cc310: Change license to Apache-2

boot/zephyr/include/sysflash/sysflash.h
The sysflash.h defines FLASH_AREA_ macros using FIXED_PARTITION macros that are provided by flash_map.h, but it does not include the required header.
=> zephyr: Add missing flash_map.h to sysflash.h

boot/zephyr/Kconfig.serial_recovery
Fixes an issue whereby the unaligned memory buffer does not have limits applied to it.
Fixes #1612
=> zephyr: serial_recovery: Fix missing limit on buffer size

.github/workflows/fih_tests.yaml, ci/fih_test_docker/execute_test.sh, ci/fih_test_docker/generate_test_report.py, ci/fih_test_docker/utils.py, ci/fih_test_docker/validate_output.py
This pull request modifies the FIH CI job to fail in case a successful boot happens.
The CI should fail if a successful boot is achieved by bypassing one or two instructions as it would defeat the purpose of the FIH mechanisms. The relevant workflow has also been modified to disable the auto-cancel feature if one of the configs fail.
relevant issue: #1584
=> CI: Improve FIH job result assesment

boot/zephyr/CMakeLists.txt, boot/zephyr/Kconfig.serial_recovery
Switches from using the zcbor files in-tree to using the ones that are part of the zephyr manifest, this prevents using old and potentially buggy versions of the zcbor library.
=> zephyr: serial_recovery: Use Zephyr manifest zcbor files

boot/boot_serial/src/boot_serial.c, boot/bootutil/src/bootutil_misc.c, boot/espressif/include/flash_map_backend/flash_map_backend.h, boot/espressif/port/esp_mcuboot.c, boot/zephyr/flash_map_extended.c, boot/zephyr/include/flash_map_backend/flash_map_backend.h, boot/zephyr/single_loader.c, sim/mcuboot-sys/csupport/run.c, sim/mcuboot-sys/csupport/storage/flash_map.h
The flash_area_sector_from_off  uses hardcoded flash_area object pointer, the flash_area_get_sector takes flash_area pointer.
Commits for:
1.  Zephyr implementation;
2. sim implementation;
3. espressif implementation;
4. general code switch;
5. zephyr/single_loader switch.
=> Replace flash_area_sector_from_off with flash_area_get_sector

boot/bootutil/src/swap_scratch.c
Trailer is temporary located in scratch when data of image goes up to last sector of primary slot. At the end of the swap procedure, the temporary trailer in scratch must be erased to prevent mcuboot from reading a stale status from the scratch area. The erase tentative was not correct, this is fixed.Issue is easily reproduced with an image size of one sector.
=> bootutil: Fix erase of trailer when located in scratch area

boot/boot_serial/src/boot_serial_priv.h
__packed is Zephyr specific macro and it may not be available in all environments. Use more generic __attribute__((packed)) instead.
=> boot_serial: Fix Mynewt tests build

boot/zephyr/Kconfig.serial_recovery, boot/zephyr/serial_adapter.c
The commit modifies selection of boot serial UART by first checking
the Zephyr chosen zephyr,uart-mcumgr and then reverting to the
zephyr,console, as a secondary candidate.
In case when both nodes are present and point to the same device,
error will be reported.
=> zephyr: Check zephyr,uart-mcumgr as candidate for serial recovery

docs/SubmittingPatches.md, docs/release-notes.d/00readme.md, docs/release.md
This PR documents the process whereby devs are required to write release note snippets as part of their changes. These notes will be reviewed together with the code.
I would like to merge this immediately after the 1.10.0 release, and start enforcing the release notes for PRs after this release.
=> Require devs to write release note snippets

boot/boot_serial/src/boot_serial.c, boot/zephyr/Kconfig.serial_recovery, boot/zephyr/include/mcuboot_config/mcuboot_config.h
Adds support for outputting the image hash TLV in serial recovery mode, which is needed to comply with the img_mgmt MCUmgr group requirements.
Fixes #1581
Test file upload and listing from mcuboot:
```
Images:
image=0 slot=0
version: 0.0.0.0
bootable: false
flags: 
hash: 73fc86f2aee87d13620ca718b851e524a01cd6d20aede1672ed3e31457b35d24
Split status: N/A (0)
```
And checking from actual booted image:
```
Images:
image=0 slot=0
version: 0.0.0
bootable: true
flags: active confirmed
hash: 73fc86f2aee87d13620ca718b851e524a01cd6d20aede1672ed3e31457b35d24
Split status: N/A (0)
```
=> boot: serial_recovery: Add image hash support

boot/bootutil/include/bootutil/crypto/ecdsa_p256.h, boot/bootutil/src/image_ec256.c
The current ECDSA-P256 implementation contains a lot of code that is tied to a specific condition being met. The aim of this PR is to cleanup the main verification logic to be unified between crypto backends and move the conditional code where it is relevant.
=> bootutil: Refactor ECDSA signature verification

boot/zephyr/Kconfig.serial_recovery, boot/zephyr/main.c
Adds an optional entrance method for mcuboot's serial recovery by using Zephyr's boot mode data retention system, this allows for an application to set the retained data and reboot into the bootloader.
=> boot: zephyr: serial_recovery: Add boot mode enter ability

boot/bootutil/include/bootutil/bootutil_public.h, boot/bootutil/src/bootutil_public.c
Commit provides boot_set_next function that allows to set next application slot to boot by flash area object pointer, describing the slot.
The function also takes active which is supposed to indicate whether running application is being set for next boot and confirm parameter that allows to confirm the image.
=> bootutil: Provide boot_set_next function

boot/zephyr/serial_adapter.c
When using CDC only and CONFIG_SERIAL is not enabled in Zephyr, but there is chosen zephyr,mcumgr-uart, the chosen takes precedence over CDC and directs MCUmgr to that uart. This causes two issues: first the CDC is ignored if chosen exists, and makes build fail because drivers are not built.
=> zephyr: serial_recovery: Fix broken CDC device selection

boot/bootutil/src/image_ec256.c, boot/bootutil/src/image_ed25519.c
There was an issue with bootutil_verify_sig for EC256 when the return type was not correct when FIH was enabled. ED25519 FIH support has also been added.
=> fix FIH return value for EC256 and add FIH for ED25519

boot/boot_serial/src/boot_serial.c, boot/boot_serial/src/serial_recovery_cbor.c, boot/boot_serial/src/serial_recovery_cbor.h, boot/boot_serial/src/serial_recovery_cbor_types.h, boot/boot_serial/src/serial_recovery_echo.c, boot/boot_serial/src/serial_recovery_echo.h, boot/boot_serial/src/serial_recovery_echo_types.h
Fixes include paths for zephyr builds to use the system zcbor_* files rather than the local files.
=> boot_serial: Fix include paths for zephyr builds

boot/zephyr/include/mcuboot_config/mcuboot_config.h, boot/zephyr/main.c
The Zephyr watchdog API defines a setup function. This function needs to be executed before the watchdog is functional in some cases. This commit adds MCUBOOT_WATCHDOG_SETUP when using the generic watchdog0 alias otherwise it is an empty define.
Fixes https://github.com/mcu-tools/mcuboot/issues/1659
=> boot: zephyr: setup watchdog

boot/bootutil/include/bootutil/image.h, boot/bootutil/src/image_validate.c, docs/design.md, docs/release-notes.d/ecdsa-tlv-p384.md, scripts/imgtool/image.py, scripts/imgtool/keys/__init__.py, scripts/imgtool/keys/ecdsa.py, scripts/imgtool/main.py, sim/src/image.rs, sim/src/tlv.rs
This pull request removes the current curve specific signature TLV types (ECDSAP224, ECDSAP256) and introduces a new generic one (ECDSASIG) that is not tied a curve, and adds P384 curve support to the imgtool.
Even in the current implementation the way the signature parsing happens is not relevant from a TLV standpoint as the curve to use is encoded in the signature itself (as per RFC 5820) and all the current crypto backends parse the signature the same way. The curve independent TLV would be beneficial later if a new crypto backend or new curve type would be introduced, such as P384.
Relevant issue: #1596
=> Add generic ECDSA TLV Signature type & P384 to imgtool

boot/zephyr/main.c
Adapt to Zephyr's change requiring main to return int.
=> boot/zephyr: switch main return type to 'int'

boot/bootutil/include/bootutil/crypto/ecdsa.h
Follow up on #1666 . A variable name has been changed during code review, but not in all the code branches, and was not caught by automated tests, which are not merged yet, so this was caught only when running the tests locally. This kind of issues can be covered by automation only when the simulator changes will be merged in with #1668 .
=> bootutil/crypto: Fix local variable name typo for PSA Crypto key parse

ci/mynewt_install.sh
ci: mynewt: Download nrfx from separate repository
Mynewt used to have copy of nrfx.
Now nrfx is taken from original repository and since some CI targets want to build for NRF MCUs nrfx repository nees to be downloaded.
=> Fix CI after mynewt update

samples/zephyr/hello-world/CMakeLists.txt
Updates a broken link to Zephyr application docs in the hello-world example.
=> zephyr: fix link to Zephyr application docs

boot/bootutil/src/loader.c
Memset could have been out optimized by compiler and also
not called in error path.
=> bootutil: Fixing memset not beeing called

boot/zephyr/Kconfig
bootloader-led0 is deprecated. Replace with mcuboot-led0 in MCUBOOT_INDICATION_LED help.
=> boot: zephyr: Use mcuboot-led0 in MCUBOOT_INDICATION_LED help section

boot/zephyr/Kconfig
Fix typo in Kconfig help text by `s/junping/jumping/`.
=> boot: zephyr: fix s/junping/jumping/ typo

boot/boot_serial/src/boot_serial.c, docs/release-notes.d/zcbor-fix.md
Fix usage of zcbor_new_encode_state API, to correctly pass the payload length. The previous usage was passing a pointer to the end of the payload, which resulted in the ZCBOR structure being initialized with an invalid `payload_end` field. On some platforms, this breaks MCUBoot serial recovery, as the ZCBOR structures required to send response data are invalid and can no longer be populated with response data.
=> boot: boot_serial: fix usage of zcbor_new_encode_state API

boot/boot_serial/src/boot_serial.c, boot/boot_serial/src/boot_serial_priv.h, boot/zephyr/Kconfig.serial_recovery, boot/zephyr/include/mcuboot_config/mcuboot_config.h, docs/release-notes.d/img-state.md
Adds support for marking images for test or confirmed in serial recovery mode, and also for listing flags/status of images on the device.
=> serial recovery: Add image status/flag listing and set image status command handler

boot/zephyr/single_loader.c
Fixes a typo with a variable name.
=> zephyr: single_loader: Fix typo

boot/zephyr/prj.conf
The default log level has changed to "default", restore it back to info.
=> zephyr: Restore default log level of info

boot/bootutil/include/bootutil/crypto/common.h, boot/bootutil/include/bootutil/crypto/rsa.h, boot/bootutil/include/bootutil/crypto/sha256.h, boot/bootutil/src/bootutil_public.c, boot/bootutil/src/encrypted.c, boot/bootutil/src/image_rsa.c, boot/bootutil/src/loader.c, boot/espressif/include/crypto_config/rsa.cmake, ext/mbedtls-asn1/include/mbedtls/version.h, sim/mcuboot-sys/build.rs
With this PR, we want to add optional support for a new backend to implement cryptographic APIs based on the [ PSA Crypto APIs](https://armmbed.github.io/mbed-crypto/html/). We start by adding support for it in the RSA encryption/signing APIs and in the SHA256 hashing APIs. A follow up PR enabling this new backend with the existing simulator tests will be opened later. This PR covers only:
* The cryptographic changes by adding a generic backend option called `MCUBOOT_USE_PSA_CRYPTO` for RSA and SHA256
* Refactors the RSA module which in the current implementation is strongly coupled with mbed TLS APIs, separating it similarly to other modules in a generic abstraction layer (rsa.h) that allows interfacing with arbitrary crypto libraries that follow the interface.
An additional small change …
=> Add support for a PSA Crypto APIs backend for RSA and SHA

docs/SECURITY.md
Hackerone hasn't turned out to be particularly useful.  Fortunately, github now has a mechanism to directly report security vulnerabilities within the project's pages.  Update the docs to show this as the preferred vulnerability reporting mechanism.
=> docs: Update security to use github reporting

boot/zephyr/boot_serial_extensions.c
Include directory path is now set by CMake.
=> zephyr/boot_serial_extension: Fix zcbor header path

.github/workflows/sim.yaml, boot/bootutil/include/bootutil/caps.h, boot/bootutil/src/caps.c, boot/bootutil/src/image_validate.c, sim/Cargo.toml, sim/mcuboot-sys/Cargo.toml, sim/mcuboot-sys/build.rs, sim/mcuboot-sys/csupport/security_cnt.c, sim/mcuboot-sys/src/api.rs, sim/mcuboot-sys/src/c.rs, sim/src/caps.rs, sim/src/image.rs, sim/src/tlv.rs, sim/tests/core.rs
This PR adds testing capabilities to the hw-rollback-protection feature of MCUboot. The non-volatile storage for the security counters is implemented on Rust's side due to the parallel nature of the tests. There is also a fix for a build error when comparing the security counter values during the simulator build.
=> sim: Add hw rollback protection tests

sim/Cargo.toml, sim/mcuboot-sys/Cargo.toml, sim/mcuboot-sys/build.rs, sim/mcuboot-sys/csupport/config-add-psa-crypto.h, sim/mcuboot-sys/csupport/config-rsa-kw.h, sim/mcuboot-sys/csupport/config-rsa.h, sim/mcuboot-sys/csupport/psa_crypto_init_stub.c, sim/mcuboot-sys/src/c.rs
In this PR, code is introduced to allow the simulator to interface with PSA Crypto functionality. When enabled with `--features psa-crypto-api`, the simulator will use all possible PSA enabled functions, and where PSA functionality is not available, will continue to use MBed TLS functions.
=> Enable PSA Crypto API tests in the simulator

.github/workflows/sim.yaml, sim/src/image.rs, sim/src/lib.rs, sim/src/tlv.rs, sim/tests/core.rs
This PR adds new test cases to the simulator to test the ram-load feature of MCUboot. New test variations have also been added for the simulator CI.
=> sim: Increase test coverage for ram-load

boot/boot_serial/src/boot_serial.c
Fixes an issue which was introduced in commit
fac2cabe98d81b4416052990a22e9698d39267a3 which would show all images, including those with invalid headers in the output of images being listed.
Fixes #1731
=> boot_serial: Fix showing images that are not valid

boot/boot_serial/src/boot_serial.c
The `matched` param in `zcbor_map_decode_bulk()` function is `pointer to the counter of matched keys`, not length of payload buffer. Reference: https://github.com/mcu-tools/mcuboot/blob/main/boot/boot_serial/src/zcbor_bulk.h#L96, fixes: fac2cabe98d8.
=> boot_serial: fix misuse of 'matched' param from zcbor_map_decode_bulk()

boot/nuttx/include/flash_map_backend/flash_map_backend.h, boot/nuttx/include/mcuboot_config/mcuboot_config.h, boot/nuttx/src/flash_map_backend/flash_map_backend.c
Definition of MCUBOOT_SWAP_USING_MOVE in case swap without scratch area is configured in NuttX was missing from mcuboot_config.h file.
Also necessary function `flash_area_sector_from_off()` is defined and declared in order to support swap without scratch.
=> nuttx: add support for swap without scratch area

boot/mynewt/src/main.c, boot/mynewt/syscfg.yml
In same cases (loging, hash, crypto) main function called newt tool generated sysinit() function to create
uart device and crypto.
Now user can specify that sysinit should be called for other cases if needed. This can be useful if some other package should be included in the build and it has package initialization function.
=> mynewt: Make sysinit() call configurable

boot/boot_serial/src/boot_serial.c
Fixes the wrong variable type being used for the confirm element.
=> boot: boot_serial: Fix wrong cbor type for confirm

scripts/imgtool/keys/ecdsa.py
=> imgtool: Fix getpriv error return with private key

boot/bootutil/include/bootutil/image.h
Fixes an issue with missing packed attributes on image.h's structures which would lead to faults on some devices e.g. ARM Cortex M0, and adds a define for the SHA256 hash size.
=> boot: bootutil: Fix missing packed attributes, add hash size define

boot/boot_serial/src/boot_serial.c
Typecasting pointer variables to uint32_t
instead of uintptr_t was causing build error
on 64-bit architecture.
This is useful, because I am currently working
on implementing support for 64-bit native target
in Apache Mynewt. There is unit test for boot_serial and it cannot be compiled without this changes.
=> boot_serial: Fix build for 64-bit architectures

boot/zephyr/Kconfig
Makes indication LED Kconfig select GPIO so that it can work.
=> boot: zephyr: Fix indication LED not selecting GPIO

boot/boot_serial/src/boot_serial_priv.h
Adds missing fields which were wrongly treated as part of the operation value, which they were not, and adds a big/little endian check.
Fixes #1748
=> boot: boot_serial: Add updated SMP header

boot/nuttx/include/flash_map_backend/flash_map_backend.h, boot/nuttx/src/flash_map_backend/flash_map_backend.c
Function `flash_area_sector_from_off` is replaced with newly used `flash_area_get_sector` to cope with calls in bootutil_misc.c file.
This is required for CONFIG_MCUBOOT_SWAP_USING_MOVE to work correctly.
This is basically a follow up to #1727 that worked but with older version of mcuboot as `flash_area_sector_from_off` was
replaced with `flash_area_get_sector` few months ago and I was not aware of this change.
=> nuttx: switch to flash_area_get_sector

docs/readme-zephyr.md
Updates the zephyr CONFIG_BOOTLOADER_MCUBOOT documentation link to target the new location.
=> fix: update zephyr CONFIG_BOOTLOADER_MCUBOOT

boot/bootutil/src/bootutil_public.c
The commit fixes boot_set_next always passing image 0 to boot_write_swap_info, instead of the proper image number. This has been affecting applications that tried to call boot_set_next in multi-image MCUboot configuration using scratch-swap algorithm.
Fixes #1762
~~Currently blocked by: https://github.com/mcu-tools/mcuboot/issues/1761 as it can not be properly tested.~~
**Update 2023-08-02 11:31 UTC**
Tested with swap-scratch algorithm and works ok.
=> bootutil: Fix boot_set_next passing wrong image number

boot/bootutil/src/bootutil_public.c
The function was incorrectly identifying partition of secondary slot of image 0 as belonging to image 1, at the same time failing to identify partition of primary slot of image 1.
=> bootutil: Fix for flash_area_id_to_image

boot/bootutil/include/bootutil/boot_record.h, boot/bootutil/include/bootutil/boot_status.h, boot/bootutil/src/boot_record.c, boot/bootutil/src/loader.c, boot/bootutil/src/swap_move.c, boot/bootutil/src/swap_priv.h, boot/bootutil/src/swap_scratch.c, boot/zephyr/include/mcuboot_config/mcuboot_config.h, docs/design.md, docs/release-notes.d/data-sharing.md
Adds TLV defines and optional function for use with the bootloader shared data feature.
=> boot: bootutil: Add boot information

boot/bootutil/src/loader.c
Downgrade prevention check moved to secure both TEST and PERMANENT upgrade modes. Downgrade can still be performed during REVERT.
Fixes #1708
PS: By doing some clean-up is mistakenly deleted the previous repo and thus the attached pull request which was still not merged...
=> bootutil: fix downgrade prevention bypass

ci/mynewt_install.sh
Update after recent removal of Mbed-TLS from Mynewt tree; now using upstream from Mbed-TLS github repo.
=> ci: mynewt: Update to install upstream Mbed-TLS

boot/bootutil/src/bootutil_misc.c, boot/bootutil/src/bootutil_public.c, boot/zephyr/include/mcuboot_config/mcuboot_config.h
bootutil: Add DirectXIP version of boot_set_next
The commit adds DirectXIP version of bootutil boot_set_next
function.
The function is enabled by configuration option:
MCUBOOT_BOOTUTIL_LIB_FOR_DIRECT_XIP.
Note that testing/confirming DirectXIP images only works when DIRECT_XIP_REVERT is enabled.
=> Boot set next direct xip

boot/bootutil/src/bootutil_public.c
The commit moves the flash_area_id_to_image to section compiled only when not in DirectXIP mode, to prevent warnings about unused static functions.
Marking as Hotfix in case this causes some CI to get grumpy.
=> bootutil: Move flash_area_id_to_image under ifdef

boot/zephyr/include/sysflash/sysflash.h
Support for three pairs of slots.
=> zephyr: Provide slot definitions for three images

boot/zephyr/boot_serial_extensions.c
Fixes building the bootloader with serial recovery mode and boot serial extensions enabled due to changes in Zephyr's MCUmgr file and naming changes.
Fixes #1786
=> zephyr: Fix boot serial extensions

docs/readme-espressif.md
Fix documentation issues for the rendering of the Espressif README page. No content is changed with this commit, but formatting and line breaks are set to approximately 100 columns.
=> docs: espressif: fix formatting of markdown

boot/zephyr/main.c
Guards the inclusion of cmsis_core header for
ARM targets only.
Fixes #1799
=> zephyr: Fix build for non-arm archs

boot/zephyr/main.c
This adds support for indication LED option (`MCUBOOT_INDICATION_LED`) in the timeout based recovery. Configured LED will be enabled when entering the recovery and disabled after selected timeout (if no mcumgr command was received).
=> boot: zephyr: use indication LED also in timeout based recovery

boot/boot_serial/src/boot_serial.c
Adds missing point in version when snprintf is used
=> boot_serial: Fix missing point if using snprintf

boot/boot_serial/src/boot_serial.c
Fixes an include which is needed for multiple options by just always including it, and fixing the path so it can be included.
=> boot_serial: Fix include

boot/zephyr/prj.conf
Changes back to the minimal C library instead of picolibc to reduce flash usage
(Test using nrf52840dk_nrf52840)
Flash usage without this: 34198
RAM usage without this: 23808
Flash usage with this: 32022
RAM usage with this: 23820
Flash change: -2.125KiB
RAM change: +12B
=> zephyr: Fall back to minimal C library

boot/boot_serial/src/boot_serial.c, docs/release-notes.d/serial-timeoout-fix.md
Fixes an issue whereby multiple commands are received and some
are still being processed. This generally arises when a response
takes a long time (e.g. when image decryption is required),
duplicate commands will now send multiple responses but avoids
the bug of future commands being sent to which previous responses
are received.
Fixes #1812
=> boot_serial: Fix issue with queued commands

boot/boot_serial/src/boot_serial.c, docs/release-notes.d/bs-encrypted-list.md
Fixes 2 issues, one whereby multiple slots were checked despite operating in single slot mode, and another whereby decrypted images would not appear on serial recovery image listing, due to assuming that the images were still encrypted.
=> boot_serial: Fix issues with single slot mode/encrypted images

boot/espressif/hal/CMakeLists.txt, boot/espressif/hal/include/esp32c6/esp32c6.cmake, boot/espressif/hal/include/esp32h2/esp32h2.cmake, boot/espressif/hal/src/flash_encrypt.c, boot/espressif/hal/src/secure_boot.c, boot/espressif/main.c, boot/espressif/port/esp32c2/bootloader.conf, boot/espressif/port/esp32c3/ld/bootloader.ld, docs/readme-espressif.md
Adjust secure boot and flash encryption after IDF v5.x updates. It also allows to enable secure boot on ESP32-C2.
Note: changes on secure_boot.c and some of flash_encryption.c functions were mostly copied "as is" from IDF.
=> espressif: update secure boot and flash encryption

boot/bootutil/include/bootutil/crypto/ecdsa.h
This fixes a build error when PSA Crypto API is being used as it has no need for bootutil_import_key but it's included currently since it's allowed to have both Mbed TLS and PSA defined.
=> bootutil/crypto: Do not include import key with PSA

boot/zephyr/CMakeLists.txt, boot/zephyr/Kconfig.serial_recovery, boot/zephyr/boot_serial_extension_zephyr_basic.c, boot/zephyr/boot_serial_extensions.c, boot/zephyr/include/boot_serial/boot_serial.ld, boot/zephyr/include/boot_serial/boot_serial_extensions.h, docs/release-notes.d/zephyr-bs-extensions.md
This allows for out-of-tree modules to define their own boot serial
functions by using iterable sections
+106 byte flash increase with this change and both in-tree handlers enabled
=> zephyr: Allow user-defined boot serial extensions

boot/bootutil/src/loader.c, docs/release-notes.d/boot-open-failure.md
Shows an error if a particular flash area fails to open and panics the bootloader
=> bootutii: Show error if flash area open fails (and panic)

boot/bootutil/include/bootutil/bootutil_public.h
- Assert should be checked only for SWAP update modes.
- Allow platforms with page size >32 Bytes (e.g. LPC) to use MCUBoot, at least for non-SWAP update modes.
=> bootutil: Disable MCUBOOT_BOOT_MAX_ALIGN assert for non-swap modes

boot/zephyr/boards/lpcxpresso55s06.conf, boot/zephyr/boards/lpcxpresso55s16.conf, boot/zephyr/boards/lpcxpresso55s36.conf, boot/zephyr/boards/lpcxpresso55s69_cpu0.conf
Add configuration for LPC55Sxx to MCUBoot.
It supports the upgrade only mode.
=> boot: zephyr: add support for LPC55Sxx

scripts/imgtool/main.py
"Align" parameter should be optional:
- it has a default value.
- it is not used for non-swap update modes.
=> imgtool: make "align" command line parameter optional

samples/zephyr/hello-world/prj.conf
Use the default MCUBoot PEM key file in hello-world project settings.
Without it the application is not verified by MCUBoot.
=> samples: zephyr: Use the default MCUBoot PEM key file.

boot/boot_serial/src/boot_serial.c
Fixes an issue whereby when an echo command is sent in serial recovery mode, if it is disabled, there would just be no response at all, which is invalid operation
=> boot_serial: Fix missing response if echo command disabled

docs/release-notes.d/boot-serial-echo.md, docs/release-notes.d/zephyr-usb.md
Adds 3 notes, 2 for zephyr USB CDC ACM fixes and 1 for a boot serial echo fix
=> docs: release: Add notes on Zephyr USB fixes and boot serial echo

boot/zephyr/boards/lpcxpresso55s28.conf
Add default configuration for lpcxpresso55s28.
=> boot: zephyr: add support for lpcxpresso55s28

boot/zephyr/Kconfig
Prevents an issue which occurs when the MCUboot configuration is changed which then selects multiple conflicting symbols
=> zephyr: kconfig: Prevent MBEDTLS selection when tinycrypt is used

boot/zephyr/boards/mimxrt1010_evk.conf, boot/zephyr/boards/mimxrt1015_evk.conf
Add the default configuration for mimxrt1010_evk and mimxrt1015_evk.
=> boot: zephyr: add support for mimxrt101x_evk

boot/zephyr/include/io/io.h, boot/zephyr/io.c, boot/zephyr/main.c
This short series includes 3 warning/error fixes found when building with `MCUBOOT_INDICATION_LED` and `LOG` enabled:
- `zephyr: rename 'led_init()' to 'io_led_init()'`
- `zephyr: io: include 'bootutil_log.h' and declare log module membership`
- `zephyr: io: add 'io_led_set()'`
All issues were introduced in 433b8480f760bdf40381e7543e358185a1006a2b.
The last fix (`zephyr: io: add 'io_led_set()'`) should be treated as more a proposal as there might be other solutions/approaches preferred.
=> zephyr: io: trivial fixes after I/O functions separation (if MCUBOOT_INDICATION_LED enabled)

boot/zephyr/firmware_loader.c, boot/zephyr/include/sysflash/sysflash.h, boot/zephyr/single_loader.c
zephyr: sysflash: Fix if condition for zephyr applications
Fixes an issue when sysflash is included by zephyr (non-mcuboot)
applications
zephyr: firmware/single_loader: Fix compile warning
Fixes an issue of an unused function calling an undefined function
=> zephyr: Fix sysflash and undefined function warning

boot/zephyr/CMakeLists.txt, boot/zephyr/Kconfig, boot/zephyr/sysbuild/CMakeLists.txt, zephyr/module.yml
Adds MCUboot's estimated overhead footer size to the application's cache when using sysbuild, this allows that information to be propagated to applications which can use the information to reduce the available size for an application, preventing the MCUboot error of image too large to swap.
=> zephyr: Add estimated image footer size to cache in sysbuild

boot/zephyr/Kconfig
This addresses compilation error when MBEDTLS module is not present.
=> zephyr: kconfig: make MBEDTLS_PROMPTLESS depend on MBEDTLS

boot/bootutil/src/loader.c, boot/bootutil/src/swap_move.c, docs/release-notes.d/bootutil-sector.md
bootutil: Add debug logging for boot status write
Adds debug level logging which shows the offset of where a
sector swap status write is occurring at
bootutil: Fix compatible sector checking
Fixes an issue whereby slot sizes were checked but the check was
not done properly. This also adds debug log messages to show the
sector configuration including if slot sizes are not optimal
docs: release: Add release notes on changes
Adds release notes on bootutil changes
=> bootutil: Fix compatible sector check

boot/zephyr/CMakeLists.txt, boot/zephyr/sysbuild/CMakeLists.txt
Adds a new field which is set to the estimated size of the upgrade slot data, this is used to know how much space should be reserved in an update image to determine if an update will fit or not
=> zephyr: Add estimated size of update trailer to sysbuild

scripts/imgtool/image.py
Currently imgtool --verify fails for hex files with:
Invalid image magic; is this an MCUboot image?
Added support for hex files by converting hex to bin using IntelHex::tobinstr().
Reusing image.load() needs a bit of rework, maybe a common load method will be done in the future.
=> scripts: imgtool: Fix img verify for hex file format

boot/zephyr/boards/nrf54l15dk_nrf54l15_cpuapp.conf
Adds default Kconfig configuration that allows to build MCUboot for NRF54L.
Currently this configuration turns off WDT and FPROTECT, which is TODO to fix.
=> zephyr: Add NRF54L configuration

boot/bootutil/src/loader.c
In multi image swap validation of images could fail due to headers being incorrectly re-read from storage.
Fixes #1768
=> boot: Fix swap-move algorithm failing to validate multi-image

boot/zephyr/include/sysflash/sysflash.h
The defines have been taken from the Zephyr flash_map.h but as they are provided there for MCUboot only, they can be just defined here.
=> boot/zephyr: Define SOC_FLASH_0_ID and SPI_FLASH_0_ID

boot/zephyr/Kconfig, boot/zephyr/Kconfig.serial_recovery, boot/zephyr/include/io/io.h
Updates a Kconfig that was renamed
=> boot: zephyr: Update changed Nordic family Kconfig

boot/zephyr/boards/nrf54l15pdk_nrf54l15_cpuapp.conf
CONFIG_FPROTECT is defined only in NRF repository, it should not be added here.
=> zephyr: boards: Remove CONFIG_FPROTECT from nrf54l15

boot/bootutil/src/loader.c
There have been duplicate functions:
boot_verify_dependencies
boot_verify_slot_dependencies
boot_verify_slot_dependency
with, very similar internals, scattered around unit. The commit have moved them on top and squashed where possible.
=> boot: Refactoring image dependency functions to reduce code size

boot/zephyr/boards/rd_rw612_bga.conf
MX25UM flash on rd_rw612_bga is very large (8MB), so we must increase the number of max sectors when targeting this board with MCUboot
Note- this support depends on https://github.com/zephyrproject-rtos/zephyr/pull/70186
=> zephyr: boards: set BOOT_MAX_IMG_SECTORS value for rd_rw612_bga

boot/zephyr/Kconfig, boot/zephyr/main.c, docs/release-notes.d/zephyr-cache.md
Fixes an issue whereby the instruction and data caches being
disabled before booting code had bit-rotted and no longer worked,
adds a new Kconfig that allows this option to be turned off if
wanted.
=> boot: zephyr: Fix disabling I/D caches

boot/bootutil/src/loader.c
I needed to create s solution based on OVERWRITE_ONLY mode that would keep a backup of the active image in the secondary slot. The main motivation was a use of MCU that doesn't support available swap modes due to its flash features. The code modification was very simple, however, I'm not 100% sure these changes don't clash with something else.
I needed to cover these scenarios:
- Both primary and secondary images are valid -> boot
- Primary image invalid -> do a recovery from the backup in the secondary slot -> boot
- Secondary image invalid -> do a backup recovery from the primary slot -> boot
The commit message explains further:
It builds on top of OVERWRITE_ONLY mode and uses secondary slot as a backup of the primary slot. The main difference is that after image copy to the primary …
=> New OVERWRITE_ONLY_KEEP_BACKUP option

boot/bootutil/include/bootutil/crypto/ecdsa.h, boot/bootutil/src/image_ecdsa.c, boot/bootutil/src/image_validate.c, docs/design.md, docs/release-notes.d/bootutil-builtin-keys.md, samples/mcuboot_config/mcuboot_config.template.h
Introduce a new MCUBOOT_BUILTIN_KEY option to enable the usage of
builtin keys for signature verification. This way the details of the key
handling mechanism are abstracted away from the boot code and this
responsibility is delegated to the given crypto library.
This is an alternative option to the existing MCUBOOT_HW_KEY feature,
however in this case we can entirely rely on key IDs and not only the
code, but also the image metadata does not contain any public key data.
Enable the usage of builtin keys in the ECDSA verification module with
the PSA Crypto API based cryptographic backend.
This way parsing and importing the verification keys can also be avoided.
=> Allow the usage of builtin keys in verification

boot/boot_serial/src/boot_serial.c
Removes unnecessary if-statement in boot_serial.c
Closes #1940
=> Removed unnecessary if-statement

docs/release-notes.d/ptest.md, ptest/Cargo.lock, ptest/Cargo.toml, ptest/src/main.rs, sim/src/image.rs
The ptest command runs multiple tests, based on the `sim.yaml` file that CI uses.  Enhance this command to support listing the tests that would be run, and selecting a subset of those tests.
=> Add some options to ptest to allow limit sets of tests to be run.

boot/zephyr/CMakeLists.txt, boot/zephyr/Kconfig, boot/zephyr/kernel/banner.c, docs/release-notes.d/zephyr-boot-banner.md
Adds an optional MCUboot boot banner which displays the MCUboot version and zephyr version
=> boot: zephyr: Add optional MCUboot boot banner

boot/zephyr/flash_map_extended.c, boot/zephyr/main.c
This change uses the flash functions to read the applications reset vector. This allows flexibility on where the application image is programmed.
The current implementation in Zephyr for ARM does not allow the use-case where the application is programmed to a different flash device than where mcuboot is programmed and running from.
This was tested on NXP ARM platforms for the case where the Zephyr and mcuboot are in the same flash device and for the case where Zephyr and mcuboot are on different flash devices.
=> zephyr: arm: Update reading the flash image reset vector

boot/bootutil/src/fault_injection_hardening_delay_rng_mbedtls.c, boot/cypress/MCUBootApp/config/mcuboot_crypto_config.h, boot/zephyr/include/config-asn1.h, boot/zephyr/include/config-ec.h, boot/zephyr/include/config-ed25519.h, boot/zephyr/include/config-kw.h, boot/zephyr/include/config-rsa-kw.h, boot/zephyr/include/config-rsa.h, sim/mcuboot-sys/csupport/config-asn1.h, sim/mcuboot-sys/csupport/config-ec-psa.h, sim/mcuboot-sys/csupport/config-ec.h, sim/mcuboot-sys/csupport/config-ed25519.h, sim/mcuboot-sys/csupport/config-kw.h, sim/mcuboot-sys/csupport/config-rsa-kw.h, sim/mcuboot-sys/csupport/config-rsa.h
check_config.h was included manually by custom configuration files. This caused compilation errors when updating MbedTLS to 3.6.0 because check_config.h was processed too early, before the whole configuration is defined, effectively causing configuration check errors.
MbedTLS already takes care of including check_config.h at the right time. Remove those erroneous manual check_config.h includes.
=> mbedtls config: fix too early check_config.h includes

README.md, repository.yml, scripts/imgtool/__init__.py
Update version information for 2.1.0 release.
=> Preps for 2.1.0 release

boot/bootutil/pkg.yml, boot/mynewt/pkg.yml
swap_scratch.c requires definition of SLOT1, in single application slot build it's not needed and file would not be used anyway so now it is removed from mynewt build
=> mynewt: Igore swap_scratch.c for single application slot

boot/zephyr/boards/frdm_mcxn947_mcxn947_cpu0_qspi.conf, boot/zephyr/boards/frdm_mcxn947_mcxn947_cpu0_qspi.overlay
1. set BOOT_MAX_IMG_SECTORS value for frmd_mcxn947_qspi. W25Q64 flash on the board is very large (8MB), so we must increase the number of max sectors when targeting this board with MCUboot.
2. Set the zephyr,flash chosen node to point to internal flash as this board supports booting from internal flash only.
=> zephyr: boards: Add files needed for NXP FRDM MCXN947 QSPI variant

boot/bootutil/include/bootutil/enc_key.h, boot/bootutil/src/encrypted.c, boot/cypress/MCUBootApp/keys.c, boot/mbed/app_enc_keys.c, boot/zephyr/keys.c, ci/mynewt_keys/enc_kw/src/keys.c, ci/mynewt_keys/enc_rsa/src/keys.c, docs/release-notes.d/bootutil-enc-hw-keys.md, sim/mcuboot-sys/csupport/keys.c
Currently encryption supports only private key embed in mcuboot itself. To support MCUBOOT_HW_KEY for image encryption boot_retrieve_private_key() hook is added.
This hook helps retrieving private key from trusted sources like OTP, TPM.
=> boot: Add MCUBOOT_HW_KEY support for image encryption

scripts/imgtool/boot_record.py, scripts/imgtool/dumpinfo.py, scripts/imgtool/image.py, scripts/imgtool/main.py, scripts/imgtool/version.py, scripts/requirements.txt
Fix and improve verify command 
Improve readability and reliability of boot_record.py 
Fix bugs and add missing features for dumpinfo command
Enable decode_version() to work with command line
Linting and other readability fixes
=> imgtool: Bugfixes and improvements for various imgtool commands

README.md, docs/index.md
Replace Slack channel links with MCUboot Discord channel as the discussions have moved there.
=> docs: Replace Slack channel links with Discord

ext/fiat/src/curve25519.c
By defining `MCUBOOT_HAVE_ASSERT_H`, a user can configure MCUboot to use a custom definition of the `assert` macro, defined in `mcuboot_config/mcuboot_assert.h` instead of the one coming from the C standard library.
However, the libc's `assert` macro was used in `curve25519.c` even if `MCUBOOT_HAVE_ASSERT_H` is defined. This PR fixes this issue by removing `#include <assert.h>` from `curve25519.c` to rely instead of the `assert` definition from `bootutil/bootutil_public.h`.
=> ext: fiat: Use user-defined assert macro

boot/bootutil/include/bootutil/crypto/common.h, boot/bootutil/include/bootutil/crypto/ecdsa.h, boot/bootutil/src/encrypted.c, boot/bootutil/src/image_ed25519.c
In Mbed TLS 3.1, the private fields in the ASN.1 structure were made private. This breaks code that accesses these private macros.
Fix this by changing the ASN.1 specific code to use a new field accessor `ASN1_CONTEXT_MEMBER` that will be conditionally defined based on the version of Mbed TLS that is present.
=> boot: Fix ASN.1 for mbedtls >= 3.1

boot/bootutil/include/bootutil/enc_key.h, boot/bootutil/src/encrypted.c, boot/cypress/MCUBootApp/keys.c, boot/mbed/app_enc_keys.c, boot/zephyr/keys.c, ci/mynewt_keys/enc_kw/src/keys.c, ci/mynewt_keys/enc_rsa/src/keys.c, sim/mcuboot-sys/csupport/keys.c
This reverts commit 0fa46270c0b52b371a094042731c69e100478cbb.
This breaks:
samples/synchronization/sample.kernel.synchronization on
b_u585i_iot02a/stm32u585xx/ns error
as this TF-M configuration uses its own keys.  This change is an API change that needs to be coordinated with TF-M changes.
Before this revert, compiling this test results in:
.../encrypted.c:447: undefined reference to
`boot_enc_retrieve_private_key`
=> Revert "boot: Add MCUBOOT_HW_KEY support for image encryption"

boot/boot_serial/src/boot_serial_encryption.c
In the boot_image_validate_encrypted there was call to flash_area_id_to_multi_image_slot, which tries to figure out slot index from flash area and image index, and the result of the call was not used for anything as slot index is hardcoded in the next call to be 1 (secondary).
=> boot: Remove pointless slot identification

boot/bootutil/src/loader.c
The boot_enc_set_key in boot_swap_image, when recovering from reset, has been caled on AES context that has not been initialized.
=> boot: Add missing boot_enc_init

boot/boot_serial/src/boot_serial.c
When working with MCUboot it is useful to check `INFO` messages, but when using together with serial recovery the `boot_uart` clutters the serial interface logs with not so critical information. Changed to `DEBUG` level.
=> boot: boot_serial: change logging to debug level

docs/readme-zephyr.md
It tells about adding the 24KB scratch partition,
not about storage partition.
=> doc: readme-zephyr: fix scratch partition

boot/bootutil/src/encrypted.c
The enc_key_data.valid had been set to true when key has been added to the encryption context, but in case when boot_enc_drop was called, on the same context, the flag remained true, even though the context may no longer hold any valid context nor key.
The commit moves the enc_key_data invalidation to enc_key_drop.
=> boot: Move encryption context invalidation to boot_enc_drop.

scripts/requirements.txt, scripts/setup.py
Update requirements.txt to support PrivateKeyType and PublicKeyType which are available in cryptography library since version 40.0.0 and prevent failing CI jobs in upcoming changes.
=> imgtool: Bump cryptography library version

boot/zephyr/main.c, docs/release-notes.d/fix-ram-load-zephyr-address.md
Fixes showing the wrong address when booting a RAM load image
=> boot: zephyr: Fix RAM load chain load address

boot/boot_serial/src/boot_serial_encryption.c, boot/bootutil/include/bootutil/enc_key.h, boot/bootutil/src/encrypted.c, boot/bootutil/src/loader.c
In all cases where boot_enc_load is called it is known what slot is addressed, so it is better to just pass the slot number instead of making the boot_enc_load figure out slot number from image index and provided flash area object.
=> boot: Change boot_enc_load to take slot number instead of image

boot/bootutil/src/loader.c
There was not really needed repetition of code in if-else block; common code has been moved out and the block has been reduced.
=> boot: Reduce repeating code in boot_decrypt_and_copy_image_to_sram

scripts/imgtool/keys/ecdsa_test.py, scripts/imgtool/keys/ed25519_test.py
Addressing this request: https://github.com/mcu-tools/mcuboot/pull/2020#issuecomment-2254006661
=> imgtool: Add missing encodings to emitter tests

boot/zephyr/boards/frdm_mcxn947_mcxn947_cpu0.conf
Add default configuration for frdm-mcxn947.
=> boot: zephyr: add support for frdm-mcxn947

boot/bootutil/include/bootutil/boot_record.h
Fixes a missing include in the header
=> bootutil: Fix missing include

boot/espressif/hal/include/esp32c6/esp32c6.cmake, boot/espressif/hal/include/esp32h2/esp32h2.cmake
The new Espressif HAL is based on ESP-IDF v5.1.4 and this PR updates the required files to compile MCUboot using this HAL version.
=> espressif: Update the references for using the new Espressif HAL

boot/zephyr/main.c
Rename the header file after upstream change.
=> boot: zephyr: Fix included header

boot/zephyr/main.c
In case ESP32 SoC is used, *start will get
build warning as it is not used.
=> boot: main: avoid unused build warning

boot/zephyr/include/mcuboot_config/mcuboot_config.h, boot/zephyr/kernel/banner.c
Update the include path of generated headers.
See:
- https://github.com/zephyrproject-rtos/zephyr/pull/63973
=> zephyr: prefix generated header path with `zephyr/`

scripts/imgtool/image.py, scripts/imgtool/main.py
One of the allowed flags in the image header is `IMAGE_F_NON_BOOTABLE`. This adds the ability to set this flag via the CLI tool.
=> imgtool: Add --non-bootable flag

boot/bootutil/src/swap_scratch.c
Fixes where this function is defined, to prevent build failures when building TF-M
=> bootutil: Fix wrong definition of find_swap_count

boot/bootutil/src/loader.c, docs/release-notes.d/bootutil-image-verification.md
bootutil: loader: Add state to boot_is_header_valid() function
Adds the state object to this function so it can be referenced
bootutil: loader: Verify image header before checking image
Changes the order of operations to validate the image header
before checking the image, it does not make sense to check the
image if the header itself is invalid
=> bootutil: Fix image verification and add state to is header valid function

boot/boot_serial/src/boot_serial.c
Clears a `format` and an `incompatible-pointer-types` warnings when building on 64 bits.
=> boot_serial: Fix `incompatible-pointer-types` and `format` warnings

boot/zephyr/boards/nrf54l15dk_nrf54l15_cpuapp.conf, boot/zephyr/boards/nrf54l15pdk_nrf54l15_cpuapp.conf
Adds the configuration for this board
=> boot: zephyr: boards: Add nrf54l15dk configuration

boot/bootutil/include/bootutil/enc_key.h, boot/bootutil/src/encrypted.c, boot/bootutil/src/image_validate.c
There is no point for boot_enc_valid to take image index and flash area and use these to figure out slot number.
=> boot: Make boot_enc_valid take slot instead of image index

boot/bootutil/src/bootutil_priv.h, boot/bootutil/src/swap_scratch.c
Improves the mode selection checks to prevent selecting multiple
conflicting modes as has been seen in TFM
Also reverts a change that was not needed
=> bootutil: Add better mode selection checks

boot/zephyr/Kconfig, boot/zephyr/main.c
Allow bootloader to fallback to USB DFU if no application is present, that can be booted from. Similar to config BOOT_SERIAL_NO_APPLICATION.
=> boot: zephyr: Add fallback to USB DFU

boot/bootutil/include/bootutil/crypto/aes_ctr.h, boot/bootutil/include/bootutil/crypto/aes_kw.h, boot/bootutil/include/bootutil/crypto/sha.h
For some reason, the calls to `mbedtls_aes_free`, `mbedtls_nist_kw_free` and `mbedtls_sha256_free_drop` were commented out which means the AES and SHA-256 contexts were not properly de-initialized after usage when mbedTLS is used. In the case of AES-KW it seems that might lead to a memory leak depending on the mbedTLS configuration, but in any case and independently of the mbedTLS configuration, this leads to the contexts not be zeroized after usage.
Not zeroizing a context means it stays in RAM an undefined amount of time, which might enable an attacker to access it and to dump the sensitive data it contains. For example, for SHA-256, knowing the value of the context might make possible to obtain part of sensitive data that was hashed. For AES, it might make possible to infer the AES …
=> bootutil: Fix AES and SHA-256 contexts not zeroized (mbedTLS)

boot/zephyr/CMakeLists.txt
CMake's message function was mistakenly called with ERROR but the correct correct argument to use is FATAL_ERROR.
=> cmake: zephyr: change ERROR into FATAL_ERROR

boot/bootutil/include/bootutil/crypto/sha.h, boot/bootutil/include/bootutil/image.h, boot/bootutil/src/image_validate.c, boot/zephyr/Kconfig, boot/zephyr/include/mcuboot_config/mcuboot_config.h
adds TLV and Kconfig to decouple verification from other options.
=> boot: SHA512 verification

boot/zephyr/Kconfig, boot/zephyr/include/mcuboot_config/mcuboot_config.h
Allow disabling feeding the watchdog on nrf devices directly using the nrfx_wdt functions.
The imply on NRFX_WDT cannot be disabled since NRFX_WDT is a promptless symbol and cannot be assigned in a config fragment. Not even deleting the wdt0 node in a devicetree overlay works since the configuration takes predence and ends in a #error without any nrfx_wdt instances.
To fix this create new Kconfig option with prompt and change the imply to this option. That way the option can be assigned to off by the user.
This is needed to support the use case of an external watchdog controlled using the zephyr watchdog API instead of the wdt peripheral.
=> boot: zephyr: Allow disabling NRFX_WDT on nRF devices

scripts/imgtool/image.py, scripts/imgtool/main.py
imgtool changes to support the SHA512 and proper ED25519 signare.
This PR is alternative to https://github.com/mcu-tools/mcuboot/pull/2029 where new TLV is introduced.
While working on image changes I have decided that it is not needed to provide new TLV  for signature, because:
- the SHA512 is newly support hash and there is no logic for it yet so no possible mismatch of SHA and key
- it is enough to decide by key and hash TLV whether the ED25519 is double or single hashing.
Depends on https://github.com/mcu-tools/mcuboot/pull/1967
=> imgtool: Support for SHA512 for ED25519 usage

boot/boot_serial/src/boot_serial_encryption.c, boot/bootutil/include/bootutil/enc_key.h, boot/bootutil/src/encrypted.c, boot/bootutil/src/image_validate.c, boot/bootutil/src/loader.c
To be able to implement encryption with API that requires different
calls for encryption and encryption, the boot_encrypt
needs to be replaced with encryption/decryption specific functions.
Depends on:
=>  boot: Replace boot_encrypt by boot_enc_encrypt and boot_enc_decrypt

boot/bootutil/include/bootutil/image.h, scripts/imgtool/image.py
The commit reserves IMAGE_TLV_SIG_PURE == 0x25 as indicator that the signature attached to image is calculated over image rather than its digest (pure, by the name of PureEdDSA). The indicator/flag is provided so that no special TLV is designated to one signature type, because, in theory, any signature algorithm that can be used over image rather than digest can be marked as "Pure".
The PureEdDSA ED25519 signature should be done directly over message, so image in our case. The current implementation is not really PureEdDSA nor HashEdDSA, as we basically pass sha256 as a message to PureEdDSA. ~~Not perfect.~~
**Why is this added?**
This PR adds TLV that indicates that PureEdDSA has been run over image rather than sha has been calculated and passed to ed25519 for signature/verification. …
=> RFC: bootutil: Add TLV for  Pure (over image) signature

scripts/imgtool/image.py, scripts/imgtool/main.py
filters with conjunction with proper container not working at this point
=> imgtool compression support

boot/zephyr/main.c
Fix possible warning "boot_serial_enter defined but not used".
=> boot: zephyr: Fix Warning 'boot_serial_enter defined but not used'

boot/zephyr/Kconfig.serial_recovery
Serial recovery failed for NXP IMX.RT platforms unless BOOT_ERASE_PROGRESSIVELY is set.
=> boot: zephyr: Fix serial recovery for NXP IMX.RT platforms

samples/zephyr/hello-world/sample.yaml, samples/zephyr/hello-world/sysbuild.conf
Enable the MCUBoot when building with sysbuild.
=> samples: zephyr: add sysbuild to the hello-world sample

boot/zephyr/sample.yaml, samples/zephyr/Makefile
Use EXTRA_CONF_FILE that replaced OVERLAY_CONFIG since the Zephyr v3.4 release.
=> boot: zephyr: use EXTRA_CONF_FILE instead of deprecated OVERLAY_CONFIG

boot/zephyr/Kconfig
The SHA512_ALLOW Kconfig has been added to allow signature algorithms to select which SHA they support. Unfortunately it has been given dependency on PSA crypto, which now is problematic because if signature algorithm wants to indicate that it allows SHA512 it immediately becomes dependent on PSA crypto.
The commit removes the dependency.
=> zephyr: Fixing Kconfig dependency for SHA512

boot/bootutil/include/bootutil/crypto/sha.h, boot/bootutil/src/image_ed25519.c
This MR adds in the bootloader support for Ed25519 using SHA-512 with mbedTLS. To do so, this MR:
* Adds support for SHA-512 with mbedTLS.
* Adds support for images hashed with SHA-512 in the Ed25519 verification routine.
The changes were tested on an STM32F4 MCU, with both SHA-256 and SHA-512 configuration.
Relates to https://github.com/mcu-tools/mcuboot/pull/2048.
=> bootutil: Add support for Ed25519 using SHA-512 with mbedTLS

scripts/imgtool/image.py, scripts/imgtool/main.py
Adds ARM thumb filter to imgtool's LZMA2 compression.
=> imgtool's compression ARM thumb filter

boot/zephyr/main.c
Before booting, It might be handy to see the version of the image we boot into.
=> zephyr: print version number before boot

scripts/imgtool/main.py
fixing broken encryption caused by shift in function parameters.
Fixes #2096
=> imgtool: bugfix #2096

boot/boot_serial/src/boot_serial.c, boot/zephyr/Kconfig.serial_recovery
- Increases the unaligned buffer default value for LPC55x and MCXNx.
- Fixes the serial recovery for LPC55x and MCXNx.
=> boot_serial: Fix serial recovery for LPC55x and MCXNx

scripts/imgtool/image.py
After #2048 the signing with `--fix-sig <sig> --fix-sig-pubkey <key>` for RSA 256 fails with error:
`Error: Colud not find allowed hash algorithms for <class 'imgtool.keys.rsa.RSAPublic'>`
Addition of `keys.RSAPublic` to allowed SHA dictionary fixes the problem.
=> imgtool: fix signing for fix-sig-pubkey public rsa

docs/design.md
=> doc: remove repetition

CODEOWNERS
Fixes the format of the CODEOWNERS file by putting slashes on the end of directories. Also add the missed top level zephyr directory to the list
=> codeowners: Fix format

boot/zephyr/boards/frdm_mcxn947_mcxn947_cpu0_qspi.overlay
- Fixes MCUBoot partition allocation for frdm_mcxn947_mcxn947_cpu0_qspi
- Assign "zephyr,code-partition" in the frdm_mcxn947_mcxn947_cpu0_qspi overlay, as app.overlay is ignored if a board overlay is present.
=> boards: mcxn947_qspi: fix mcuboot partition allocation

CODEOWNERS
The wildcard entry needs moving to the top so other entries override it
@utzig Now that this seems to sort of work (the action fails, I have no idea why but I've given up trying to work that out), should any folders/files be added to you?
=> codeowners: Move wildcard entry to top

boot/boot_serial/src/boot_serial.c
Add support for reporting various sha in image list. There is always only one sha compiled in, but serial recovery has been previously hardcoded to support sha256 only.
=> boot_serial: Support sha256, sha384 and sha512

boot/bootutil/src/loader.c
Bootstrapping is currently not allowed for more than one image. But that seems to be unintentional according to https://github.com/mcu-tools/mcuboot/pull/826#issuecomment-707939624
I ran into the same issue trying to boot two images (for M7 and M4) on a i.MX RT1170 using zephyr. We solved this using the suggested change and hope it could be added to main.
With this it's possible to enable MCUmgr SMP within MCUBoot and update a device that only has the bootloader in flash.
=> boot: Support bootstrapping for multiple images

scripts/tests/test_compression.py
Simply end2end test which check if an image is compressed with lzma2.
=> Add a test to verify if lzma2 compression works

.github/workflows/imgtool.yaml
v3 of actions/upload-artifact and
actions/download-artifact becomes obsolete.
=> ci: Upgrade artifact actions

boot/zephyr/Kconfig, boot/zephyr/main.c
Add Kconfig option to cleanup RAM in MCUboot before passing control to an application.
=> zephyr: Add CONFIG_MCUBOOT_CLEANUP_RAM

boot/zephyr/sample.yaml
Twister now expects a yaml list of plaforms.
Signed-off-by: Anas Nashif <anas.nashif@intel.com>
=> zephyr: convert platform_allow to a list

boot/bootutil/src/boot_record.c, boot/zephyr/single_loader.c
Ensure that bootloader info and measurements are saved to retained memory when using mcuboot in single-image mode.
=> boot: zephyr: boot_record: Save boot data with single image

boot/zephyr/boards/frdm_mcxa156.conf
Adds default configuration for the frdm-mcxa156 board.
=> boot: zephyr: boards: Add frdm-mcxa156 configuration

boot/bootutil/src/loader.c
Since the introduction of 4cab08e32b7d0d9956edded2cd8d238690a6c435, an interrupted upgrade might fail at next boot when swap-scratch is used. This is due to the fact the image header are not properly reloaded from flash memory after the upgrade completion, leading to erroneous behaviors such an image validation failure if the images in the primary and secondary slots haven't exactly the same size. The issue is only temporary and disappear at next boot, but would cause a revert process to be triggered if `BOOT_SWAP_TYPE_TEST` is used.
The problem is that after a partial upgrade has been resumed and completed, the image headers are reloaded using `boot_read_image_headers(state, false, bs);` (see [this line](https://github.com/mcu-tools/mcuboot/blob/f74b77cf7808919837c0ed14c2ead3918c546349/bo …
=> bootutil: Fix upgrade might fail after power-failure if swap-scratch is used

boot/bootutil/src/bootutil_public.c, docs/design.md
This PR proposes a fix to https://github.com/mcu-tools/mcuboot/issues/1966, which describes a scenario where a device can be bricked if a revert process is interrupted when using swap-move.
As suggested in [this message](https://github.com/mcu-tools/mcuboot/issues/1966#issuecomment-2200541322), a very straightforward fix might be enough. The latter is implemented in this PR.
The idea is to perform a revert no matter the state of the magic number in the secondary slot's trailer, provided the `copy-done`
flag is set in the primary slot but the `image-ok` flag is not. The `copy-done` flag is set only after having completed an upgrade or
revert process so if the `copy-done` flag is set but the `image-ok` is unset, it is guaranteed an upgrade has been performed but the new image has not been …
=> bootutil: Fix device bricked after power failure during swap-move revert

.github/workflows/imgtool.yaml
GitHub recently announced that [actions/cache](https://github.com/actions/cache) v1 and v2 are deprecated. Jobs using them will start failing in February. In this repo, only the imgtool action uses actions/cache.
This PR updates the imgtool.yaml workflow to use actions/cache@v4.
- Announcement: https://github.blog/changelog/2024-09-16-notice-of-upcoming-deprecations-and-changes-in-github-actions-services/
- Discussion: https://github.com/actions/cache/discussions/1510
=> ci: actions/cache v1 has been deprecated, use v4

boot/bootutil/src/loader.c
Before pushing MCUBOOT_STATUS_UPGRADING, check if has_upgrade is true to ensure this is not pushed at every boot and only when needed.
=> boot: bootutil: loader.c: Add check if has upgrade before pushing state change

boot/zephyr/sample.yaml
These boards' original names have changed and now use variants.
=> zephyr: update mimx1050 and 1060 platform_allow entries

boot/zephyr/boards/m5stack_cores3_esp32s3_procpu.overlay, boot/zephyr/boards/m5stack_cores3_esp32s3_procpu_se.overlay
Add m5stack_cores3/esp32s3/procpu and m5stack_cores3/esp32s3/procpu/se board targets.
Adds an overlay to disable devices that cause dependency conflicts.
=> boot: zephyr: boards: add support for M5stack CoreS3/CoreS3SE

scripts/imgtool/image.py, scripts/imgtool/main.py
The PR adds --pure switch to imgtool that allows to run ED25519 over entire image calculating the PureEdDSA signature.
The imgtool will add SIG_PURE TLV as indicator that whatever signature is used is calculated directly over image.
The PR also provides different output for signature verification, where there is signature reported on verification, rather than digest ~~as digest is no longer available~~, but will provide digest if key is not provided during verification.
Depends on https://github.com/mcu-tools/mcuboot/pull/2029 -- that reserves the SIG_PURE in MCUboot code
Based on https://github.com/mcu-tools/mcuboot/pull/2048
=> imgtool: Add --pure switch to allow calculating signatures over entire images

boot/bootutil/include/bootutil/image.h
This TLV is needed in order to know what the data length provided to the decompression system is to remove the padding that is a resultant of the encryption block size
=> boot: bootutil: Add TLV for size of compressed but decrypted image

scripts/imgtool/image.py, scripts/imgtool/main.py
adds TLV which stores compressed image size in case encryption is on. This is to avoid wrong streaam size due to encryption padding.
=> scripts: imgtool: fix compression with encryption

boot/boot_serial/src/boot_serial.c, docs/release-notes.d/serial-recovery-var.md
Fixes some issues whereby some variables were not initialised,
and undefined values were wrongly used instead
Fixes #2177
=> boot: boot_serial: Fix uninitialised variables for upload

boot/espressif/hal/include/esp_mcuboot_image.h, boot/espressif/port/esp32s2/ld/bootloader.ld, boot/espressif/port/esp_loader.c, docs/release-notes.d/espressif-idf-version-checking.md
Add additional regions in loader to include
RTC, LP, IROM and DROM information.
=> espressif: extend loader data

boot/zephyr/flash_map_extended.c
The mapping does not seem to be needed as scratch is opened directly, and there is only one for all images anyway.
Simulator seems to error out when asked to identify scratch with this function.
=> zephyr: Remove scratch from flash_area_id_from_multi_image_slot

boot/bootutil/src/image_ed25519.c
Need to define MBEDTLS_ASN1_PARSE_C to be able to see ASN1 functions declarations from mbedTLS.
=> bootutil: Add missing MBEDTLS_ASN1_PARSE_C

boot/zephyr/CMakeLists.txt, boot/zephyr/Kconfig
This commit fixes issue where even if Zephyr provided mbedTLS module was used, ASN1 decoding procedures have been taken from MCUboot own version of mbedTLS extracted sources for these functions.
To be able to do that this commit changes config file used with mbedTLS with the one provided from Zephyr (the generic one), which allows to select required mbedTLS features via Kconfig options exposed by Zephyr.
Depends on https://github.com/zephyrproject-rtos/zephyr/pull/84390
=> zephyr: Fix usage of CONFIG_MBEDTLS_BUILTIN and ASN1

boot/bootutil/src/swap_offset.c
Only erases and copies sectors where there is data present
=> boot: bootutil: swap_offset: Skip erasing/copying empty sectors

boot/bootutil/src/loader.c, docs/release-notes.d/fix-stuck-revert.md
Fixes an issue (only for swap using move, unsure if it affects
other modes) whereby a device can get into a state that there is
a valid primary image, no secondary image but the primary image
flag is still set to revert, which then makes loading a firmware
update from the application impossible due to it assuming that a
revert will happen upon device reboot
=> boot: bootutil: loader: Fix issue with stuck revert

boot/bootutil/src/bootutil_priv.h, boot/bootutil/src/loader.c
There have been invocations of BOOT_IMG(...).area used where BOOT_IMG_AREA could be used to obtain the same result.
=> boot: bootutil: Use BOOT_IMG_AREA to get boot_loader_state area

boot/bootutil/include/bootutil/crypto/aes_ctr.h, boot/bootutil/pkg.yml, boot/bootutil/src/ed25519_psa.c, boot/bootutil/src/encrypted.c, boot/bootutil/src/encrypted_psa.c, boot/bootutil/src/image_ed25519.c, boot/bootutil/zephyr/CMakeLists.txt, boot/zephyr/CMakeLists.txt, boot/zephyr/Kconfig
The commit provides implementation of image verification with ed25519 and encryption/decryption support where random key is encrypted using x25519.
=> bootutil: PSA implementation of x25519 and ed25519 verification

boot/bootutil/src/image_ed25519.c, boot/zephyr/Kconfig, boot/zephyr/include/mcuboot_config/mcuboot_config.h
Add conditional compilation of ASN.1 decoding of ED25519 key.
This allows to cut out the ASN.1 encoding, which results in reduced flash size.
Comparison on nrf52840dk/nrf52840 build of MCUboot with the ED25519 enabled 
```
west build -p -d builds/nrf52_mcuboot_ed25519_no_asn -b nrf52840dk/nrf52840 bootloader/mcuboot/boot/zephyr/ -DCONFIG_BOOT_SIGNATURE_TYPE_ED25519=y
```
Reduces code from 40422 bytes to 39918 bytes, when  `-DCONFIG_BOOT_KEY_IMPORT_BYPASS_ASN=y` is added.
Another benefit of the option is that it is no longer needed to have portion of the mbedTLS, that does the ASN.1 support, enabled when compiling MCUboot with ED25519 for TinyCrypt.
=> Allow bypassing ASN.1 processing of public key for ED25519

boot/bootutil/src/swap_offset.c
I'm currently trying to modify the simulator to test upgrades with the largest possible images for all possible upgrade strategies (currently this is not made for some strategies such as swap-offset). While playing with the simulator I noticed the swap-offset upgrade was failing if an image is large enough to use all the available sectors.
Let's consider this very simple scenario, with slots containing a single sector for the firmware image:
```
PRIMARY                               SECONDARY
+-----------------------+              +-----------------------+
|        Firmware       |   Sector 0   |        (empty)        |
+-----------------------+              +-----------------------+
|        Trailer        |   Sector 1   |        Firmware       |
+-----------------------+ …
```
=> boot: bootutil: Fix last sector index computation for swap-offset

boot/bootutil/src/swap_scratch.c, sim/src/image.rs, sim/src/lib.rs
At the beginning of a swap-scratch upgrade, the index of the last sector in the primary slot that needs to be swapped is computed using the `find_last_sector_idx` routine. However, if the primary slot is composed of larger sectors than the secondary slot, this routine could return a wrong sector index for the primary slot. The index might even be outside the primary slot, which would lead to at best a simple failure of the upgrade and at worst a corruption of the flash memory bricking the device.
The issue hasn't be detected in the simulator until now since among the tested configurations, none used a primary slot composed of larger sectors than the secondary slot. This MR adds such a configuration, which as expected lead to the tests to fail:
```
$ cargo test --features …
```
=> boot: bootutil: Fix invalid last sector computation for swap-scratch 

boot/bootutil/src/bootutil_misc.c, boot/bootutil/src/bootutil_priv.h, boot/bootutil/src/image_validate.c, boot/bootutil/src/swap_scratch.c, sim/mcuboot-sys/src/area.rs, sim/src/image.rs
When swap-scratch is used and the trailer is larger than the last sector of the primary and/or the secondary slot, the upgrade would fail and a potential flash memory corruption could occur due to an underflow in case a sector contains both part of the firmware image and part of the trailer.
This issue was not shown by the simulator since when `max-align-32` is not selected, the trailer fit in a single sector in all tested configuration, and when `max-align-32` is selected, the firmware image size is chosen so that no sector contain both part of the firmware image and part of the trailer. So, perhaps that's a known limitation and it is expected the users ensure their firmware images are small enough so that this issue doesn't occur, but since I didn't find any documentation mentioning …
=> boot: bootutil: Fix swap-scratch when the trailer is larger than the last sector

boot/bootutil/src/bootutil_misc.c, boot/bootutil/src/bootutil_priv.h, boot/bootutil/src/loader.c, boot/bootutil/src/ram_load.c, boot/bootutil/src/swap_misc.c, boot/bootutil/src/swap_move.c, boot/bootutil/src/swap_offset.c, boot/bootutil/src/swap_scratch.c
Reduce flash_area_open/flash_area_close calls by re-using pointers to flash_area objects stored in boot_loader_state, that should be populated by context_boot_go.
=> boot: Reuse pointers for flash_area objects from state

boot/zephyr/boards/frdm_mcxn236.conf
Adds default configuration for the frdm-mcxn236 board.
=> boot: zephyr: boards: Add frdm-mcxn236 configuration

boot/zephyr/Kconfig, boot/zephyr/Kconfig.serial_recovery
Removes lines that have never done anything because this is already the default
=> boot: zephyr: kconfig: Remove superflous default n lines

boot/zephyr/flash_map_extended.c
This resolves a warning when building with `-Wsign-compare`.
`struct flash_area.fa_size` is declared as `size_t` in the Zephyr source tree ([in `include/zephyr/storage/flash_map.h`](https://github.com/zephyrproject-rtos/zephyr/blob/v4.1.0/include/zephyr/storage/flash_map.h#L48-L68)).
=> zephyr: flash map: fix comparison signedness

sim/src/image.rs, sim/src/tlv.rs
To generate largest possible and oversized images, the simulator needs to determine first the maximum size of an image. When signing the images using ECDSA, the actual size of the generated image was not exactly always the desired size. Indeed, in that case, the size of the TLV area estimated during the computation of the maximum image size might not be always equal to the actual TLV area size. This is because the ECDSA signatures are encoded as ASN.1 and the size of the ASN.1 representation can vary depending on the value of the two integers the signature is composed of.
This was not a big deal but was adding a bit of randomness in the simulation and was for example making difficult to generate reliably an oversized image, possibly leading to occasional false failures of the tests using …
=> sim: Ensure the estimated TLV area size is always equal to the actual size

scripts/imgtool/dumpinfo.py, scripts/imgtool/main.py
Hi,
I'm using `dump_imginfo` to export image info in a yaml file from another python source code. I don't want that this script stop when calling this function with `silent=True`.
Regards,
GG
=> imgtool: dumpinfo avoid exit

boot/zephyr/flash_map_extended.c
Clang wrongly throws a warning, which will be treated as an error in twister builds, add pointless workaround to set variable that is already set by the hook function to avoid this
=> boot: zephyr: flash_map_extended: Add pointless workaround for clang

boot/bootutil/src/swap_scratch.c
Before the PR #2206 fixing issues in the swap-scratch logic when the trailer is larger than the last sector was merged, the PR #2114 was reverted (see #2211). This changes made by #2211 were then reapplied (see #2216) after #2206 was merged, leading to some conflicts: a call to `swap_erase_trailer_sectors` was moved by #2206 but the old call to that function was added back by #2216 and a new call to `swap_erase_trailer_sectors` was added by #2206 but not converted to a call to swap_scramble_trailer_sectors by #2216.
=> bootutil: swap-scratch: Fix conflicts after support of device without erase

boot/bootutil/src/swap_move.c, docs/design.md
app_max_sectors() is always off by one in its calculation. This corrects that calculation as well as the warning which should only be comparing the two slot sector counts and checking to see if they are different by one sector for the swap sector. The size of the application is not relevant in that warning for optimal sector distribution.
Additionally app_max_size() suffers similarly in that it is not taking into account the fact that the secondary slot does also contain a trailer.
Finally makes a minor addition to the design document which further clarifies the primary and secondary partition size differences.
=> swap_move: correct appsize calcs and warning

boot/zephyr/boards/nrf7002dk_nrf5340_cpuapp.conf
The change allows to build MCUboot for nrf7002dk/nrf5340/cpuapp with default configuration.
=> zephyr: Disable SPI_NOR by default for nrf7002dk/nrf5340/cpuapp

boot/zephyr/boards/nrf54h20dk_nrf54h20_cpuapp_iron.conf
Added configuration for the nRF54H20 DK 'iron' board variant.
=> boot/zephyr/boards: nrf54h20dk 'iron' board configuration

boot/bootutil/src/loader.c
Adds an include which provides a definition for the flash_area_get_sector() function
=> boot: bootutil: loader: Add include for flash function

boot/bootutil/src/swap_move.c
Fixes this function as it was not updated after an earlier fix
=> boot: bootutil: swap_move: Fix maximum application size

boot/boot_serial/src/boot_serial.c
Fixes an issue with swap using offser with serial recovery by changing an #ifdef
=> boot: boot_serial: Fix swap using offset

boot/zephyr/CMakeLists.txt
When computing the maximum image size, the Zephyr build system was wrongly considering the trailers have to be sector-aligned for swap-scratch. This is not the case, as swap-scratch support having a sector containing both firmware and trailer data. This issue was preventing e.g. to build an application using swap-scratch with single-sector slots.
Additionally, this PR also fix a minor fix for swap-move and swap-offset: the TLV area size was added to trailer size before rounding up to the next multiple of the sector size. The TLV area is not part of the trailer so shouldn't be considered when rounding up the trailer size.
This MR was tested with Zephyr v4.1.0 on a STM32H747 MCU.
=> zephyr: Fix trailer size computation for swap-scratch

boot/bootutil/src/swap_offset.c
Fixes this functionality to have the maximum allowable application size
=> boot: bootutil: swap_offset: Fix maximum application size

boot/zephyr/flash_map_extended.c, boot/zephyr/main.c
This reverts commit 453096b17ddc3aac7bf6afb97c40591d5ea3aa9c.
Comment from @de-nordic 
> This is revert of commit which was supposed to allow picking interrupt vector table from flash area but the whole modification unfortunately misunderstood difference between flash device ID and flash area ID.
=> Revert "zephyr: arm: Update reading the flash image reset vector"

boot/boot_serial/src/boot_serial.c
Fixes an issue whereby when canonical mode for ZCBOR was enabled, the state variables were not increased to handle the backup states, and a bug whereby only secondary slots were checked for status when setting image state, whilst generally this is the intended outcome, a user should also be able to mark a primary image as confirmed too for other modes such as direct-xip
=> boot: boot_serial: Fix issue with CBOR and setting image state

boot/zephyr/Kconfig
Fixes typo in the BOOT_SWAP_USING_MOVE configuration description.
=> boot: zephyr: kconfig: Fix BOOT_SWAP_USING_MOVE description

boot/zephyr/Kconfig
Fixes issues with Kconfigs being placed outside of the MCUboot group and not selecting experimental symbols. Also fixes ordering to place USB DFU into a menu rather than being all over the place
=> boot: zephyr: kconfig: Fix issues and re-order

boot/boot_serial/src/boot_serial.c, boot/boot_serial/src/boot_serial_encryption.c, boot/bootutil/src/bootutil_misc.c, boot/bootutil/src/bootutil_priv.h, boot/bootutil/src/loader.c, boot/bootutil/src/swap_misc.c, boot/bootutil/src/swap_move.c, boot/bootutil/src/swap_offset.c, boot/bootutil/src/swap_scratch.c, docs/release-notes.md
Refactors the erase functionality in bootutil so that it can be used alongside feeding the watchdog. This has also optimised some functions out.
Also fixes a serious issue with swap using scratch that would leave primary slot images unbootable and potentially brick devices
=> boot: bootutil: Refactor erase functionality to fix watchdog feeding, also fix swap scratch corrupt image issue

boot/bootutil/src/swap_offset.c
Assert on the pointer validity in debug builds and make sure that an initialised value of 0 is always returned even in case of errors.
This is useful to silence _potentially uninitialised_ warnings.
=> Bootutil: always initialise the size returned by boot_util_image_size()

boot/boot_serial/src/boot_serial_encryption.c, boot/bootutil/include/bootutil/crypto/aes_ctr.h, boot/bootutil/src/encrypted.c, boot/bootutil/src/encrypted_psa.c
Fixes in encrypted_psa.
BOOTUTIL_CRYPTO_AES_CTR_KEY_SIZE has been replaced with BOOT_ENC_KEY_SIZE
BOOTUTIL_CRYPTO_AES_CTR_BLOCK_SIZE has been replaced with BOOT_ENC_BLOCK_SIZE
=> Improve PSA offset/len defines for tlv and remove some defs from bootutil

.github/workflows/zephyr_build.yaml, boot/zephyr/main.c
pointer to the image ARM vector table should be placed out of stack which is being reconfigured before vt is used for branch to the application. This caused transient boot failure when CONFIG_LTO=y.
Moved vt to static data scope.
fixes #2307
=> boot/zephyr/main: fix placement of pointer to arm vector

scripts/imgtool/image.py
After #2063 the imgtool verify fails to validate an image signed with a previous imgtool version.
The PR corrects `tlv_off` by accounting for protected TLVs found before the main scan.
Fixes #2302.
=> imgtool: fix verify tlv offset before main scan

boot/bootutil/src/bootutil_misc.c, boot/bootutil/src/image_validate.c, sim/src/image.rs
When computing the maximum image size in `bootutil_max_image_size` for the swap-move or swap-offset strategy, the computation was using the size of the flash area provided as argument and was not taking into account the size of the padding sector. This was causing an incorrect (too large) size to be returned in the following cases:
* Both primary and secondary slots have the same size.
* The primary and secondary slots don't have the same size, but the routine is called for the slot containing the padding sector.
For example, let's imagine swap-move is being used on a device having a sector size `S` and two slots of `N` bytes. This is valid configuration and the maximum image size is `N - S - T`, `T` being the size of the trailer rounded up to the next multiple of `S`. When calling …
=> boot: bootutil: Fix max image size computation for swap-move and swap-offset 

sim/tests/core.rs
The test case `oversized_secondary_slot`, introduced by https://github.com/mcu-tools/mcuboot/pull/1286 was not enabled when the `max-align-32` feature was selected because the test case was failing with some configurations.
From the PR description:
>  added oversized_secondary_slot test for ensure that too big image upgrade attempt will be rejected. I doesn't work for max-align-32 feature due to not precise operations on flash image in sim code. Fixing of this problem is out of scope for this PR.
Since 88294be188c25e4b7d02cc9c55fabfc9286c83b7, the `oversized_secondary_slot` test is now passing with `max-align-32` in all configurations and can therefore be enabled.
=> sim: Enable oversized_secondary_slot test with max-align-32

boot/bootutil/src/encrypted_psa.c
=> bootutil: encryption: Fix typo in PSA code

boot/bootutil/src/loader.c, sim/mcuboot-sys/src/api.rs, sim/mcuboot-sys/src/c.rs, sim/src/image.rs, sim/tests/core.rs
This PR fixes an issue that was preventing an interrupted then resumed upgrade to be reverted when the hardware rollback protection is enabled and the swap-scratch, swap-move or swap-offset strategy is used.
After a "test" upgrade has been performed, the security counter of every image must not be updated immediately to be able to roll back in case the upgrade is not confirmed. To that end, the `boot_update_hw_rollback_protection` routine, called just before exiting MCUboot, was checking the swap type of the image and updating the security counter only if the swap type was none, with the assumption that it implies no upgrade has been performed by MCUboot. This was working properly in the nominal case, when the upgrades are not interrupted, however this assumption is false if MCUboot has …
=> boot: bootutil: Fix security counter updated before revert after resuming upgrade

boot/bootutil/src/bootutil_misc.c
Fixes wrongly including swap and trailer sizes for single image builds which reduced the maximum size of applications, these areas are not used or applicable with single image modes
also ping @taltenbach
=> boot: bootutil: bootutil_misc: Fix max image size for single images

boot/zephyr/arm_cleanup.c, boot/zephyr/include/arm_cleanup.h, boot/zephyr/main.c
Zephyr 4.1 changes `CONFIG_CPU_HAS_NXP_MPU` to `CONFIG_CPU_HAS_NXP_SYSMPU`. This change reflects that.
Relates to https://github.com/mcu-tools/mcuboot/issues/2332
=> boot: zephyr: update NXP MPU define to new name

scripts/tests/test_commands.py
Exit code of imgtool executed without arguments differs based on click version.
=> imgtool: fix dependency on click version

boot/bootutil/src/loader.c, docs/release-notes.d/fix-boot-scramble-region.md
=> bootutil: Fix boot_scramble_region escaping flash area

boot/bootutil/src/encrypted.c
Optimize out some unneeded calls.
=> bootutil: boot_decrypt_key: Only one bootutil_hmac_sha256_drop needed

boot/zephyr/main.c
Consolidates USB DFU entry logic by unifying GPIO and timeout-based DFU triggers under a common flag. This avoids code duplication and improves maintainability.
Also improves log clarity for different DFU exit conditions.
=> boot: zephyr: Refactor USB DFU entry logic

boot/zephyr/io.c
The hfwinfo returns bitmask, not single values.
=> zephyr: Fix pinreset trigger

ci/fih-tests_run.sh
As the upstream tf-m repo is unreliable, change our CI scripts to pull from a github mirror. The code checks out a specific explicit SHA, so it should be easy to maintain the mirror.
=> Fix pull of TF-M to be from a github mirror

boot/boot_serial/src/boot_serial.c
Fixes passing the wrong slot ID to the hook calls in serial recovery mode
=> boot: boot_serial: Fix wrong slot ID for hook calls

boot/bootutil/src/image_validate.c, docs/release-notes.d/fix-direct-hash-base-address.md
Fetch the flash base address if direct hash calculation is performed.
Fixes: https://github.com/mcu-tools/mcuboot/issues/2368
=> bootutil: Use flash base address for direct hash

boot/bootutil/src/image_validate.c
This commit fixes the formatting of comments in the `image_validate.c` file to ensure they are properly aligned.
=> bootutil: Fix comment formatting

zephyr/module.yml
Makes this sample path listed in the zephyr module file
=> zephyr: Add zephyr samples folder to list of samples

boot/zephyr/Kconfig, boot/zephyr/main.c
Option to put execution in infinite loop.
Meant to be used for debug.
=> boot: zephyr: RAM cleanup debug loop

boot/bootutil/include/bootutil/fault_injection_hardening.h, boot/bootutil/src/fault_injection_hardening.c
Add `noreturn` attribute the `fih_panic_loop()` and add a terminal endless loop in the function to prevent build warnings like the below one found when build MCUBOOT in TF-M:
```
.../arm-none-eabi/include/assert.h: In function '__assert_func':
.../trusted-firmware-m/platform/ext/common/tfm_assert.c:22:1: warning: 'noreturn' function does return
22 | }
| ^
```
=> boot: bootutil: declare fih_panic_loop() as noreturn

boot/zephyr/io.c
Removes support for bootloader-led0, as this has been replaced with mcuboot-led0
=> boot: zephyr: Remove support for deprecated LED dts

boot/zephyr/prj.conf
=> boot: zephyr: Remove references to tinycrypt

boot/zephyr/boards/nrf54h20dk_nrf54h20_cpuapp_iron.conf, boot/zephyr/boards/nrf54h20dk_nrf54h20_cpuapp_iron.overlay
The nrf54h20 power domains are forced on at boot, no need to enable them or their drivers unless they are to be managed further within the bootloader.
Aligns with https://github.com/zephyrproject-rtos/zephyr/pull/90754
=> zephyr: boards: nrf54h20dk: disable power domains

boot/zephyr/Kconfig
Commit introduces BOOT_SOMETHING_USES_SHA<256,384,512> Kconfig options that can be used to control what algorithms should be compiled in with crypto backends.
=> zephyr: Improve SHA support selectors

boot/zephyr/CMakeLists.txt, boot/zephyr/Kconfig
Adds Kconfig option CONFIG_BOOT_ECDSA_PSA that allows to switch ECDSA to PSA backend.
=> zephyr: Enable building ECDSA PSA variant

boot/bootutil/src/image_validate.c, boot/zephyr/Kconfig, boot/zephyr/include/mcuboot_config/mcuboot_config.h
Currently MCUboot checks whether key hash in TLV matches any known builtin public keys.
When only one key in compiled in, most cases, then this match is pointless as image signature verification will just verify validity of the key anyway.
The PR adds MCUBOOT_BYPASS_KEY_MATCH option that allows to turn of the key matching and slightly reduces the binary size.
=> Allow bypasing signature hash key matching

docs/SECURITY.md, docs/release-notes.d/align-security-policy.md
Align the project security policy with the Trusted Firmware security policy at: https://www.trustedfirmware.org/.well-known/security.txt
=> Align with Trusted Firmware security policy

boot/bootutil/src/encrypted_psa.c, scripts/imgtool/image.py
HMAC-SHA512 used for MAC tagging encryption key has been incorrectly fed only 32 bytes for password.
=> Fix HMAC-SHA512 for ECIES-X25519

boot/bootutil/src/image_validate.c
Adds an error log output showing the version of the image security counter and the monotonic counter value when the image has too low a count to be booted
=> boot: bootutil: image_validate: Add error on security counter fail

boot/zephyr/sample.yaml
The legacy USB device stack is in the process of being deprecated. In order to pass CI in the Zephyr Project, we need to adjust the test case settings in sample.yaml. Clean up both test cases and add a Kconfig option that allows them to pass Twitter runs despite deprecation warnings and flash overflows.
Exact as https://github.com/zephyrproject-rtos/mcuboot/pull/131
=> boot: zephyr: adjust sample.yaml to pass USB deprecation process

boot/bootutil/src/swap_scratch.c
This PR fixes the scrambling of the scratch area after persisting a trailer to the primary slot. Previous use of boot_erase_region() didn't guarantee that the scratch area is scrambled, as it only erases memory for devices that selects CONFIG_MCUBOOT_STORAGE_WITH_ERASE.
=> bootutil: swap_scratch: Fix scratch scrambling

boot/zephyr/prj.conf
This Kconfig option has been deprecated. It has been replaced by HAS_BT_CTLR, however that's a promptless option so it can't be explicitly disabled.
=> boot: zephyr: Remove reference to deprecated BT_CTLR option

boot/boot_serial/src/boot_serial.c
For MCUboot's MCUBOOT_SINGLE_APPLICATION_SLOT, MCUBOOT_FIRMWARE_LOADER, MCUBOOT_SINGLE_APPLICATION_SLOT_RAM_LOAD
modes there is not image run-time status data at the end on the image. Erase of that was done as the last image page erase - and was no harm before by luck.
Following commit just reveled the issue:
=> boot/boot_serial: build-time skip of the erasing of img status page

boot/bootutil/include/bootutil/crypto/aes_ctr.h
memset was given incorrectly pointer size, instead of object size.
=> bootutil: Fix bootutil_aes_ctr_drop memset usage

boot/zephyr/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
Add the required zephyr,code-partition which is typically included by the common app.overlay to the nrf54h20dk_nrf54h20_cpuapp board overlay.
=> boot: zephyr: boards: nrf54h20dk cpuapp add chosen code part

boot/bootutil/src/image_validate.c
removing direct inclusion of mbedtls headers.
bootutil has already abstracted away mbedtls apis.
=> bootutil: src: image_validate.c: remove mbedtls headers

boot/bootutil/src/tlv.c, boot/zephyr/firmware_loader.c, boot/zephyr/single_loader.c
Fixes two issues introduced in https://github.com/mcu-tools/mcuboot/pull/2308:
1. `bootutil_tlv_iter_next()` may be called with `type == NULL`.
2. Both static `boot_image_validate_once()` functions in the Zephyr application have a flash area parameter named `fa_p`, not `fap_p`. This presumably went unnoticed because these functions are only compiled when `MCUBOOT_VALIDATE_PRIMARY_SLOT_ONCE` is defined.
=> Fix logging errors

boot/zephyr/flash_map_extended.c
Flexspi devices have their AHB address available in the dts which value is now assigned to FLASH_DEVICE_BASE
=> boot: zephyr: get base addres from dts for flexspi devices

boot/zephyr/boards/frdm_mcxa156.conf
Deletes configuration for the FRDM-MCXA156 board.
It's not required after MCXA156 flash write-program-size was reduced from 128 to 16 bytes.
=> boot: zephyr: boards: delete frdm_mcxa156 configuration

boot/bootutil/include/bootutil/boot_hooks.h, boot/zephyr/hooks_sample.c
Use the dedicated type to specify the slot number.
=> hooks: Use dedicated type for slot numbers

boot/bootutil/src/encrypted_psa.c
Use BOOT_LOG_MODULE_REGISTER(mcuboot_psa_enc), instead of BOOT_LOG_MODULE_DECLARE.
=> bootutil: Fix log module registration
