sim/.gitignore, sim/Cargo.lock, sim/Cargo.toml, sim/README.rst, sim/build.rs, sim/csupport/run.c, sim/src/api.rs, sim/src/area.rs, sim/src/c.rs, sim/src/flash.rs, sim/src/main.rs, sim/src/pdump.rs
Add the simulator, clean up logging, and create a small readme.
=> Sim updates

boot/zephyr/targets/nucleo_f401re.h
Signed-off-by: Ricardo Salveti <ricardo.salveti@linaro.org>
=> zephyr: add target header file for nucleo f401re

README-zephyr.rst, imgtool/README.rst
Add some docs for Zephyr, and add a note to Imgtool's readme about building gotchas.
=> Update documentation for Zephyr

boot/bootutil/src/loader.c
=> Assert flash ops

sim/src/main.rs
This adds simulation of the effects of doing multiple resets while upgrade is not completed, which is a failure condition I can easily reproduce while testing on real hardware.
Since I'm not seeding the random generator this will fail intermittently, which for a CI is probably not that great.
=> Add test of multiple random resets while upgrading

sim/src/api.rs, sim/src/flash.rs
* Print bail out error information
* Print specific location of non-ff writes
=> Add extra information on errors

boot/bootutil/src/bootutil_misc.c
- This also fixes an issue that could arrive if the magic is only partly
erased.
=> Use constant for magic size

sim/src/main.rs
This fixes a situation where the random resets calculation of all reset points was done at the beginning which could fail to reset the requested amount of times. Also since the upgrades were not marked as permanent, resets after the swap was finished would cause a revert swap. So this PR also marks upgrade as permanent for two of the tests, which should not be required anymore, but we stay on the safe side.
PS: The random reset point calculation is trying an amount which should be conservative enough to enable the total amount of resets asked by the user, but since there on each reset the total amount of flash operations increases by the number of flash operations done in the "startup", it could happen that it fails to do all resets before finishing the swap (but in my tests looks ok).
=> Fix random reset behavior

imgtool/sign.go
The bootloader assumes that parts of the flash that aren't written
still have 0xff in them.  Fix the padding code so that the padding is
done this way.
=> imgtool: Pad file with 0xff

Makefile, boot/bootutil/include/bootutil/caps.h, boot/bootutil/src/Makefile, boot/bootutil/src/caps.c, boot/bootutil/src/loader.c, sim/build.rs, sim/src/caps.rs, sim/src/main.rs
Implement an overwrite-only upgrade as well as a query to determine at run time if that is available.
=> Add overwrite-only upgrade

sim/src/main.rs
Refactor of main test code
- Some helper structs added to track state
- Add new trailer checking routine
- Add extra test for upgrade+revert with failure
- Misc improvements
=> Simulator refactorings

doc/PORTING.md
I fixed the review issues, so my suggestion is to merge as is and open new PR's if there's more stuff that needs to be fixed.
=> Initial porting guide

boot/bootutil/include/bootutil/bootutil.h, boot/bootutil/src/bootutil_misc.c, boot/bootutil/src/loader.c, sim/simflash/src/lib.rs, sim/src/main.rs
This improves behavior of swap handling.
=> Rework some of the handling of swap errors

release-notes.rst
=> Add release notes

.travis.yml
=> Add travis results to #builds channel in Slack

boot/bootutil/src/image_rsa.c
=> Fix macro in comment

doc/design.txt
=> Update design doc for compliance with implementation

README.md
- Add coverity and travis-ci badges
- Link title to project url
- Remove version information from header text
=> Add badges, link url

.travis.yml
=> Add travis integration for coverity

README.md
=> Update README based on master's version

.travis.yml
Currently, there is nothing to do to test that documentation is passing,
however Travis runs across the whole project.  Create a simply passing
Travis file so that it will pass on this branch.
=> Create passing Travis file

doc/design.txt, doc/signed_images.md
=> Update docs to describe new image format

README-mynewt.rst
=> Add mynewt option for generating new format images

.travis.yml
=> Fix slack integration token, remove coverity from master

.travis.yml, boot/bootutil/src/loader.c, sim/Cargo.toml, sim/src/main.rs
This fixes some issues when running in overwrite-only
=> Fix issues in overwrite-only mode

Makefile
=> Fixes a make param typo

scripts/imgtool.py
=> Remove duplicated choices by using existing dict

boot/bootutil/src/image_ec256.c
This is a optional fix that removes a TODO avoids a memcpy.
=> Avoid ec256 pubkey memcpy

.travis.yml, scripts/check-signed-off-by.sh
This adds validation of "Signed-off-by:" line.
=> Add travis' validation of "Signed-off-by:" line

scripts/check-signed-off-by.sh
=> Only check signed-off-by in PRs

NOTICE
Signed-off-by: Sterling Hughes <sterling@runtime.io>
=> Add NOTICE file for mcuboot from ASF

docs/design.md
=> Describe the tradeoffs of scratch size

sim/Cargo.lock, sim/mcuboot-sys/Cargo.toml, sim/simflash/Cargo.toml, sim/simflash/src/lib.rs
This is a rebase of #165, but since that change was closed, github created a new PR.
=> Fix some warnings in the simulator

docs/release-notes.md
=> Update with 1.1.0 release notes

repository.yml
=> Update Mynewt version numbers

boot/bootutil/src/image_ec.c
=> Fix EC224 API usage due to change in mbed-TLS

docs/Gemfile.lock
http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-9050
=> Update nokogiri due to security vulnerability

samples/zephyr/hello-world/CMakeLists.txt, samples/zephyr/hello-world/boards/README.rst
This PR includes several patches to modernize the Zephyr hello-world application according to the latest best-practices.
=> Modernize zephyr hello world sample

README.md
- Also fix imgtool script link
=> Use relative links for docs

repository.yml
=> Fix with correct release numbers

boot/bootutil/include/bootutil/bootutil_log.h, boot/bootutil/src/loader.c, boot/mynewt/src/main.c
=> Add mynewt logging

boot/boot_serial/src/boot_serial.c
This fixes an issue found on stm32f3 where `newtmgr` after writing an odd sized packet, would hardfault on the next write due to trying to write an odd address which is not valid on stm32f3 flash.
=> Fix boot_serial to follow flash write alignment

boot/bootutil/include/bootutil/bootutil_log.h, boot/bootutil/src/bootutil_priv.h, boot/bootutil/src/loader.c, boot/mynewt/mcuboot_config/syscfg.yml, boot/zephyr/Kconfig, docs/design.md
Fixes issue #176.
TODO: flashmap could be updated to do better checking when loading sector data (size of output array is not known which can easily lead to memory corruption).
=> Max sectors config

scripts/imgtool.py, scripts/imgtool/version.py, scripts/requirements.txt
This switches CLI parameter handling to click for much better UX.
=> Add click handling of cli options

boot/boot_serial/src/boot_serial.c, boot/boot_serial/src/boot_serial_priv.h, boot/boot_serial/test/src/boot_test.c, boot/boot_serial/test/src/testcases/boot_serial_empty_msg.c
Signed-off-by: Marko Kiiskila <marko@runtime.io>
=> boot_serial; re-enable mynewt boot_serial unittests.

docs/release-notes.md
=> Update with 1.2.0 release notes

.gitignore
=> Add Eclipse project files to gitignore

project.yml, repository.yml
=> mcuboot v1.2.0 repository

samples/zephyr/hello-world/CMakeLists.txt, samples/zephyr/hello-world/prj.conf
This project fails to build due to changes in upstream Zephyr; fix the issues.
=> Zephyr: fix build for hello world

scripts/check-signed-off-by.sh
=> Remove redundant text in SoB error message

.travis.yml, scripts/check-signed-off-by.sh, scripts/run_tests.sh
Because the amount of features that the simulator is testing is growing, the test time is taking a long time. This distributes simulator's tests over three travis machines to decrease test time.
=> Travis speed ups

boot/boot_serial/src/boot_serial.c, boot/mynewt/boot_uart/src/boot_uart.c, boot/mynewt/boot_uart/syscfg.yml
with mynewt.
Signed-off-by: Marko Kiiskila <marko@apache.org>
=> faster speeds for UART with serial bootloader

boot/bootutil/src/loader.c
Previously it was assumed that the trailer would fit one sector. While this works for most devices, some which happen to have lots of sectors end up using lots of space for their swap status area. The same issue could also happen if sectors are small (less than 2K/4K, for example).
This fixes the issue by checking the trailer size and erasing all sectors that encompass it.
=> Fix trailer erase for some devices

README.md, repository.yml
Third release candidate for 1.3.0.
=> Bump version to 1.3.0-rc3

ptest/src/main.rs
The change "Add Mynewt target builds to CI" changes the format of the
.travis.yml file a bit.  Fix up the ptest utility so that it is still
able to run the simulator tests.
=> ptest: Support new format of .travis.yml

README.md, docs/release-notes.md, repository.yml, scripts/setup.py, version.yml
=> Release 1.3.1

.travis.yml, sim/src/image.rs, sim/tests/core.rs
This adds testing of multi-image in swap mode to sim, and fixes the issues that were happening.
=> Multi image sim fixes

sim/src/image.rs, sim/src/lib.rs, sim/tests/core.rs
This PR collects a couple of refactorings/cleanups to the sim test code.
=> sim: Test simulator cleanups

scripts/imgtool/image.py, scripts/imgtool/main.py
Change adds showing image version while verifying.
=> scripts: Show image version while verifying

boot/bootutil/src/bootutil_misc.c, boot/bootutil/src/bootutil_priv.h, boot/bootutil/src/encrypted.c, boot/bootutil/src/image_validate.c, boot/bootutil/src/loader.c
This mainly reduces the size of the bootloader, but also makes some parts more readable and maintainable (hopefully!).
=> [RFC] This brings in a bunch of refactorings

boot/bootutil/src/image_validate.c
This fixes an issue where dependencies were being decrypted before hashing when encrypted images are used. When using dependencies, some "protected" TLVs are added to the image. Those TLVs take part into the image hash calculation, but are not encrypted and must be sent plain to the hash update routine.
=> Fix encrypted images with dependencies

docs/SECURITY.md
=> docs: Create initial security policy

README.md, docs/SECURITY.md, docs/release-notes.md, repository.yml
Release notes and a doc update for 1.4.0-rc1.
=> Prep for 1.4.0-rc1

docs/Gemfile.lock
https://nvd.nist.gov/vuln/detail/CVE-2019-16892
=> Fix CVE-2019-16892

boot/bootutil/src/bootutil_misc.c, boot/bootutil/src/bootutil_priv.h, boot/bootutil/src/loader.c
This is the start of adding some overflow and bound checking to MCUboot. This adds some overflow-checking add functions, and checks the values in the header. More checks can be built upon this.
=> Overflow and bound checks

README.md, docs/release-notes.md, repository.yml, scripts/imgtool/__init__.py
Update version stamps as well as the release notes.
=> Prepare for release v1.4.0-rc2

README.md, repository.yml, scripts/imgtool/__init__.py, version.yml
Update release notes and various version stamps.
=> Prepare for v1.4.0 release

boot/zephyr/main.c
Only execute serial recovery if valid pin condition is detected
during power up reset or pin reset on nRF devices with RESETREAS
register. This is to prevent going into serial recovery when
waking up from power off mode with the same pin conditions that
is configured to trigger serial recovery.
Signed-off-by: Jon Helge Nistad <jon.helge.nistad@nordicsemi.no>
=> boot: zephyr: Add check of RESETREAS for nRF SoC

README.md
These are some minor fixes to the README.md files submitted by Aidan
Earle <a_earle@live.com>.
=> README.md: Minor typographical and grammar fixes

samples/zephyr/hello-world/src/main.c
Update include due to changes in Zephyr. This is related to commit
f1d189c48649f179e6a9fcd71abe90cff82ad6b5.
=> zephyr: fix include in hello-world app

sim/src/tlv.rs
Remove a bunch of magic numbers from the TLV code, and just compute the size directly after encoding the data.  The size has to be back-patched after the TLV is built. The protected TLV size is a little harder, since it needs to be known before the image can be hashed. This is still done dynamically instead of with a variable that we adjust.
=> Compute sizes instead of magic numbers

docs/PORTING.md
Update the list of APIs needed for porting MCUboot to a new platform.
=> docs/PORTING.md: Update APIs needed for porting MCUboot

scripts/imgtool/image.py, scripts/imgtool/main.py
This partly fixes #226 (the image generation side). Previous PR (#636) was wrong!
=> Fix imgtool checking of oversized app

docs/index.md
To merge once the new mailing list is announced, if it is ever going to be...
=> docs: fix mailing list URL

README.md
Update the top-level README.md file to refer to the new mailing list.
=> README: update mailing list

boot/bootutil/src/loader.c
Fix for issue #669
Signed-off-by: Barry Solomon barry.solomon@dexcom.com
=> loader: Fix dependency check issue related to swap type

repository.yml
0-latest and 1-latest should point to latest stable release.
=> mynewt: Update latest tags in repository.yml

boot/cypress/BlinkyApp/BlinkyApp.mk, boot/cypress/BlinkyApp/Readme.md, boot/cypress/MCUBootApp/README.md, boot/cypress/Makefile, boot/cypress/README.md
* delete excess information from user docs
* delete excess information from makefiles
=> Cypress: update user docs

ext/fiat/src/curve25519.h
Update from upstream: 92b7c89e6e8ba82924b57153bea68241cc45f658
=> Update fiat from latest upstream

docs/PORTING.md, docs/design.md, docs/encrypted_images.md, docs/signed_images.md
- Fix rendering issues of multi-line HTML comments (license headers)
- Fix rendering issues of footnotes
=> Fix Markdown rendering issues

docs/design.md, docs/imgtool.md, docs/signed_images.md
- Update documentation of 'HW based downgrade prevention'
- Add description for the following features:
MCUBOOT_MEASURED_BOOT
MCUBOOT_DATA_SHARING
MCUBOOT_HW_KEY
- Fix rendering issues of multi-line HTML comments (license headers)
- Fix rendering issues of footnotes
=> docs: Provide description for multiple features

README.md, docs/release-notes.md, repository.yml, scripts/imgtool/__init__.py
Update version fields, and add release notes for the 1.6.0-rc1 release.
=> Preps for 1.6.0-rc1

README.md, docs/release-notes.md, repository.yml, scripts/imgtool/__init__.py
Update various version fields.  Also include a note in the release notes
describing Zephyr compatibility.
=> Preps for 1.6.0-rc2 release

README.md, docs/release-notes.md, repository.yml, scripts/imgtool/__init__.py
Update README, release notes the mynewt repository file, and imgtool for
the v1.6.0 release.
=> Preps for v1.6.0 release

boot/cypress/cy_flash_pal/cy_flash_map.c
Sad mistake happen in PR744 while cleaning up code - this is a fix
=> [Cypress] Fix compilation of cypress code

sim/Cargo.lock, sim/Cargo.toml, sim/simflash/Cargo.toml, sim/simflash/src/lib.rs, sim/src/image.rs, sim/src/tlv.rs
Upgrade rust dependencies in the simulator to latest versions. Most changes do not affect the sim code, but there are a few minor API changes that need to be applied.
=> Upgrade Rust dependencies to latest versions

boot/cypress/MCUBootApp/main.c
Signed-off-by: Bohdan Kovalchuk <bohd@cypress.com>
=> Cypress: fix one more unwanted warning

boot/zephyr/main.c
If software IRQ relay is enabled and VTOR is available,
the bootloader will switch from its real vector table
to the relay vector table before chain-loading to the
application.
Signed-off-by: Rafał Kuźnia <rafal.kuznia@nordicsemi.no>
=> boot/zephyr: set VTOR to relay vector before chain-load

scripts/imgtool/__init__.py
Signed-off-by: Ihor Slabkyy <ihor.slabkyy@cypress.com>
=> Change imgtool version to 1.7.0a1

scripts/setup.py
Fix author email after move to new mailing list.
=> imgtool: fix package's author email

boot/zephyr/sample.yaml
Change whitelist->allow to be compatible with sanitycheck in zephyr.
Signed-off-by: Anas Nashif <anas.nashif@intel.com>
=> sample: inclusive language: whitelist -> allow

boot/zephyr/flash_map_extended.c, boot/zephyr/include/flash_map_backend/flash_map_backend.h
Follows up the change added to Zephyr with: https://github.com/zephyrproject-rtos/zephyr/pull/24873
=> zephyr: struct device const-ification

boot/cypress/BlinkyApp/Readme.md, boot/cypress/MCUBootApp/README.md, boot/cypress/README.md
This change adds Disclaimer section to Cypress related documentation and adds details about custom hardware configuration flow.
Signed-off-by: Roman Okhrimenko <roman.okhrimenko@cypress.com>
=> cypress: Update user documentation with disclaimer and additional instructions

boot/bootutil/include/bootutil/fault_injection_hardening.h
The IAR toolchain does not handle the "%=" template. Emulate it with
a combination of __LINE__ and __COUNTER__
Signed-off-by: TTornblom <thomas.tornblom@iar.com>
=> boot: Fix FIH_LABEL/FIH_CALL macros for IAR

docs/release.md
After each release version will be changed to
MAJOR.MINOR.PATCH-dev.
fixes #839
=> doc/release: Describe development version designation

README.md, docs/release-notes.md, repository.yml, scripts/imgtool/__init__.py
Update version fields for 1.7.0-rc1 release.
go after https://github.com/mcu-tools/mcuboot/pull/859
=> [DNM] Preps for 1.7.0-rc1

README.md, docs/release-notes.md, repository.yml, scripts/imgtool/__init__.py
Update version fields for 1.7.0-rc2 release.
=> [DNM] Preps for 1.7.0-rc2

.github/workflows/imgtool.yaml, .github/workflows/mynewt.yaml, .github/workflows/sim.yaml, README.md
Fix workflows names on yaml root to be able to use them to refer to the workflow. Add badges for pypi, workflows and license.
=> ci: update workflows names and add more badges

.github/workflows/mynewt.yaml, .github/workflows/sim.yaml, README.md
* Run Sim and Mynewt workflows on `master` when commits are pushed (or merged!)
* Update badges to use the workflows names
=> Extra workflow fixes

.github/workflows/mynewt.yaml, .github/workflows/sim.yaml
Only check signed commits for PRs.
=> ci: fix signed-off-by checks in master

README.md
Switch version info to 1.8.0-dev
=> Post v1.7.0 action

scripts/imgtool/image.py
After the change to support protected TLVs, the `verify` command was not updated with proper support. Fix it by skipping any protected TLV found, and fix the size of the hashed/signed region to also include the protected TLV area.
Fixes part of #924
=> imgtool: fix validation with protected TLVs

boot/bootutil/include/bootutil/bootutil_public.h, boot/bootutil/include/bootutil/enc_key.h, boot/bootutil/include/bootutil/enc_key_public.h, boot/bootutil/src/bootutil_priv.h, boot/bootutil/src/bootutil_public.c
=> fix build with encryption enabled after bootutil_publi library was introduced

.github/workflows/imgtool.yaml, ci/imgtool_install.sh, ci/imgtool_run.sh, scripts/imgtool/__init__.py
* imgtool: rollback to 1.7.0 release
* ci: add caching for imgtool pip packages
* ci: update imgtool script to to use python/pip
=> Fix imgtool workflow

repository.yml
newt tool usess repository.yml from master branch.
=> mynewt: Update repository.yml with latest release

boot/bootutil/src/boot_record.c, boot/bootutil/src/loader.c, docs/design.md
Commit1: Check shared area more carefully before init
Commit2: Correct MCUBOOT_DIRECT_XIP_REVERT enablement
=> Some minor improvements

boot/boot_serial/src/boot_serial.c, boot/boot_serial/src/boot_serial_priv.h, boot/cypress/MCUBootApp/config/mcuboot_config/mcuboot_config.h, boot/mbed/include/mcuboot_config/mcuboot_config.h, boot/mynewt/mcuboot_config/include/mcuboot_config/mcuboot_config.h, boot/zephyr/CMakeLists.txt, boot/zephyr/Kconfig, boot/zephyr/boot_serial_extensions.c, boot/zephyr/include/mcuboot_config/mcuboot_config.h
PR contains tow commits:
- adding support for system specific mcumgr commands in serial recovery;
- adding zephyr implementation of the command that erases storage partition.
=> Serial recovery storage erase cmd

boot/bootutil/src/loader.c
Signed-off-by: Sherry Zhang <sherry.zhang2@arm.com>
Change-Id: I18ce06e008f858a1fef246bf1a4e527320ba6912
=> boot: Fix build time error in DIRECT_XIP mode

boot/zephyr/Kconfig, boot/zephyr/boot_serial_extensions.c, boot/zephyr/include/mcuboot_config/mcuboot_config.h
Added service for custom command for fetch non-standard image status.
cddl-gen header also fixed: https://github.com/NordicSemiconductor/cddl-gen/pull/77
=> Custom image property list comand

README.md, docs/readme-espressif.md
This PR adds Espressif port documentation and reference in readme.md.
=> readme.md: Adding espressif reference 

README.md, docs/release-notes.md, repository.yml, scripts/imgtool/__init__.py
Update version fields for 1.8.0-rc1 release.
=> Preps for 1.8.0-rc1

boot/cypress/BlinkyApp/Readme.md, boot/cypress/MCUBootApp/README.md, boot/cypress/README.md, docs/PORTING.md, docs/SECURITY.md, docs/SubmittingPatches.md, docs/design.md, docs/readme-espressif.md, docs/readme-riot.md, docs/readme-zephyr.md, docs/release-notes.md, docs/release.md, docs/signed_images.md, docs/testplan-mynewt.md, docs/testplan-zephyr.md, ext/nrf/README.md, sim/README.rst
Unified case in titles.
Fixed small grammar issues.
Signed-off-by: Francesco Servidio <francesco.servidio@nordicsemi.no>
=> doc: Fix case in titles

docs/PORTING.md, docs/design.md, docs/encrypted_images.md, docs/readme-espressif.md, docs/testplan-mynewt.md
Fixed the style used to format notes to be more consistent.
Signed-off-by: Francesco Servidio <francesco.servidio@nordicsemi.no>
=> doc: Fixed notes formatting

boot/espressif/port/esp_mcuboot.c
This PR intends to refactor both the `flash_area_read` and `flash_area_write` functions for properly supporting unaligned read and write operations on SPI Flash.
This refactor also handles read and write operations whose length in bytes are not multiple of 4.
Created a custom testing infra for validating the added changes:
https://godbolt.org/z/834rjjhMq
=> espressif: Fix flash_area_[read/write] support for unaligned accesses

docs/SECURITY.md
Updated security.md:
- Fixed small formatting issues
- Fixed a pair of sentences.
Signed-off-by: Francesco Servidio <francesco.servidio@nordicsemi.no>
=> doc: Updated security.md

docs/design.md
Added description for explain how the algorithm works.
=> doc/design: Explain swap without using scratch algorithm

sim/src/image.rs
This PR intends to prepare the simulator to execute images with a max align value other than 8 bytes.
**Note**: change extracted from patch series proposed on PR https://github.com/mcu-tools/mcuboot/pull/1217
=> sim: Calculate offsets from boot_max_align instead of hardcoding them

README.md, docs/index.md
Updated index.md and readme.md:
- Removed outdated info
- Added info about newly added ports
- Fixed a few style issues.
- Rephrased a few sections.
Signed-off-by: Francesco Servidio <francesco.servidio@nordicsemi.no>
=> doc: Updated index.md and readme.md

scripts/assemble.py
This file has been removed from upstream Zephyr in commit 2b7c61e306a
("cmake: re-work devicetree preprocessing steps").
Get the board name from .config instead; this is a stable place for it
to be found. Load the EDT itself from the pickle file in the build
directory; this has the advantage of fixing the script when out of
tree devicetree bindings are used.
Signed-off-by: Martí Bolívar <marti.bolivar@nordicsemi.no>
=> assemble.py: don't read BOARD.dts.pre.tmp

boot/nuttx/include/mcuboot_config/mcuboot_config.h
This PR enables additional options to configure upgrade policy and image load policy for NuttX RTOS
=> nuttx: extend configuration options

boot/bootutil/src/bootutil_misc.c
Update `boot_status_off` to take into consideration that scratch only has to store status for one swap of sectors, thus requiring much less flash space than what is required in the primary slot.
This commits does a bit of refactoring on the functions that return parts of trailer size to make the code clearer.
This should fix the bug found while testing #1217
=> bootutil: fix scratch status offset calculation

docs/readme-espressif.md
This PR updates the Espressif document.
=> espressif: Update readme-espressif.md to include information about hardware-assisted Flash Encryption and Secure Boot.

boot/bootutil/src/swap_move.c, boot/bootutil/src/swap_scratch.c
Added LOG for informing which a swap type is performed.
=> boot/bootutil: added log on swap type used

docs/ecdsa.md
Rephrased a few sentences.
Fixed a few typos.
Fixed lists.
Added additional small fixes.
Signed-off-by: Francesco Domenico Servidio <francesco.servidio@nordicsemi.no>
=> doc: fixed ecdsa.md

docs/release.md
Fixed spacing after periods.
Rephrased slighly unclear sentences.
Added other very minor fixes.
Signed-off-by: Francesco Domenico Servidio <francesco.servidio@nordicsemi.no>
=> doc: updated release.md

README.md, docs/release-notes.md, scripts/imgtool/__init__.py
Preparations for releasing v1.9.0-rc1.
=> V1.9.0 rel

README.md, docs/release-notes.md, scripts/imgtool/__init__.py
Bump version information for 1.9.0 release
=> Update to version 1.9.0

README.md, repository.yml
Missed this update for the release.  This should point Mynewt to the
latest release.
=> Update Mynewt repository.yaml for 1.9 release

boot/boot_serial/src/boot_serial.c, boot/boot_serial/src/echo.cddl, boot/boot_serial/src/serial_recovery_echo.c, boot/boot_serial/src/serial_recovery_echo.h, boot/boot_serial/src/serial_recovery_echo_types.h, boot/zephyr/CMakeLists.txt
Fixing missed update from cddl to zcbor.
=> boot_serial: Fix echo command code no longer compiling

boot/boot_serial/src/boot_serial.c
Two commits: 
1) refactoring of erase logic;
2) refactoring of write logic;
~~Depends on https://github.com/mcu-tools/mcuboot/pull/1388~~
=> Refactoring of erase and write operations in bs_upload

boot/nuttx/main.c
boot: nuttx: main: add suport for board late initialization.
When using nuttx MCUBoot app as a main entry point in
place of nsh_main it is necesary to perform board-specific
driver initialization through boardctl().
Signed-off-by: Andrés Sánchez Pascual <tito97_sp@hotmail.com>
=> boot: nuttx: main: add suport for board late initialization.

boot/zephyr/boot_serial_extensions.c, boot/zephyr/flash_map_extended.c, boot/zephyr/include/sysflash/sysflash.h, boot/zephyr/include/target.h
Two commits:
1) sysflash.h changes;
2) zephyr extensions.
~~This is waiting for https://github.com/zephyrproject-rtos/zephyr/pull/48174~~
=> Switch zephyr port from using FLASH_AREA_ macros to FIXED_PARTITION_ macros

samples/zephyr/Makefile
decrease sample/zephyr/makefile hard code
Signed-off-by: honglin leng <a909204013@gmail.com>
=> sample:zephyr: decrease some hard code

ci/fih-tests_run.sh, ci/fih_test_docker/execute_test.sh, ci/fih_test_docker/fi_tester_gdb.sh, docs/design.md
Update from `TF-Mv1.4.0` to `TF-Mv1.7.0`.
=> Update TF-M version in CI FIH test

docs/readme-espressif.md
This PR also applies some suggestions regarding command line separation on the examples.
=> doc: espressif: Add warning note for Flash Encryption with Serial Recovery usage

ci/compare_versions.py
packaging >= 22 dropped support for LegacyVersion, which was the usual result of an invalid version number being parsed. Now it is PEP-440 strict and throws an exception on fails. This fixes the script to work with both older and newer releases.
=> ci: Fix compatibility with packaging==22

boot/boot_serial/src/boot_serial.c, boot/boot_serial/src/boot_serial_priv.h, boot/bootutil/include/bootutil/boot_hooks.h
Changes:
1) Prototype for boot_reset_request_hook has been provided
2) Hook has been added to bs_reset in boot_serial.
=> Add boot_reset_request_hook

boot/bootutil/src/bootutil_misc.c
In rework:
- size has been removed from array, as it has been making array at least of two elements, even if scratch partition not used;
- some variables have been localized and some removed;
- no longer returning rc codes from flash_area_ functions on failure, just single point of failure-exit - it made no sense anyway as we can not recover from flash failure;
- flash area pointer is now NULLified on failure, or when status not found.
When building for SWAP_MOVE on nrf52840dk_nrf52840 this reduces flash usage by 16bytes, which is not so great but ate least 16bytes less.
=> bootutil: Little rework of boot_find_status

docs/readme-zephyr.md
Adds details on how to use the swap-using-scratch algorithm and associated risks.
=> docs: zephyr: Add note on swap-using-scratch

ci/check-signed-off-by.sh
Try a merge commit if no parameters are passed, otherwise accept the first parameter as the oldest SHA to check.
Alternative to #1615. It needs some extra testing but worked locally.
=> ci: Update signed commit check to accept a SHA

boot/mynewt/flash_map_backend/include/flash_map_backend/flash_map_backend.h
Simple stub of flash_area_get_sector using system provided flash_area_sector_from_off.
=> mynewt: Add flash_area_get_sector

ci/mynewt_install.sh, ci/mynewt_run.sh
Build Mynewt targets in similar way as Mynewt GH Actions. This also enables running Mynewt specific tests.
=> ci: mynewt: Sync with upstream Github Actions

boot/boot_serial/src/boot_serial.c
The mcumgr packet sent over serial should be fragmented into frames of up to 127 bytes, including 2-bytes frame start header and 1-byte for terminating newline [1], resulting in up to 124 bytes for the base64 encoded payload.
Current implementation doesn't fulfill above requirement and transmits single frames, without considering their length. This change introduces support for fragmenting as defined in 'SMP over console' specification.
[1] https://github.com/apache/mynewt-mcumgr/blob/master/transport/smp-console.md
=> boot_serial: support fragmentation for outgoing SMP packets

docs/index.md, docs/readme-zephyr.md, docs/serial_recovery.md
Added description on what is the serial recovery protocol in general.
=> doc: Added serial recovery documentation

boot/boot_serial/src/boot_serial.c
According to the [SMP protocol documentation](https://docs.zephyrproject.org/latest/services/device_mgmt/smp_groups/smp_group_1.html#image-upload-request), `image number` value in `image upload request` is optional and can be included only in packet with `off` (data offset) set to `0` (first packet in upload request).
In one of recent changes (commit cb07e888691d), initialization of the `img_num` variable was removed which, in extreme case (no image number provided in upload request), results in use of its uninitialized value in `flash_area_open()` call which then might lead to request abort.
This fixes above regression and also makes MCUboot implementation of the `image upload request` aligned with Zephyr documentation of the protocol by considering image number only from first (off == …
=> boot_serial: fix image number handle in image upload request

README.md
Add new badge to easily check build status for Espressif CI.
=> Add Espressif build status badge

docs/imgtool.md, scripts/imgtool/main.py
Update the --align option values.
Add its description.
Delete [required], as it is optional now.
=> doc: imgtool: update align description

boot/zephyr/boards/mimxrt1040_evk.conf
Add default configuration for mimxrt1040_evk.
=> boot: zephyr: add support for mimxrt1040_evk

docs/release-notes.d/boot-serial-echo.md, docs/release-notes.d/zephyr-encryption-single.md, docs/release-notes.d/zephyr-estimated-sysbuild.mc, docs/release-notes.d/zephyr-mass-erase.md, docs/release-notes.d/zephyr-mbedtls-kconfig.md, docs/release-notes.d/zephyr-usb.md
Adds release notes for various recent changes
=> docs: release: Add release notes

boot/zephyr/Kconfig, boot/zephyr/include/mcuboot_config/mcuboot_config.h
adding WATCHDOG_FEED support for WDT30 and WDT31
=> boot: zephyr: additional nrf watchdogs

scripts/imgtool/main.py
Fix "align" possible script error, caused by #1833
=> imgtool: fix "align" script error

ci/mynewt_install.sh
Match version with what is now used in upstream Mynewt.
=> ci: mynewt: Update external repositories

docs/release-notes.d/imgtool_sanity_test.md
Add missing release note for #1819
=> docs: Add release note snippet for imgtool testing

boot/bootutil/src/loader.c, boot/bootutil/src/swap_move.c
Convert tab to spaces; fix opening brace position.
=> Fix style issues

boot/zephyr/boards/mimxrt1050_evk_mimxrt1052.conf
- Add common mimxrt1050_evk_mimxrt1052.conf for all revisions.
- Delete the qspi revision mimxrt1050_evk_mimxrt1052_qspi.conf
=> boot: zephyr: boards: Add common mimxrt1050_evk configuration.

boot/bootutil/src/loader.c
Move checking of conditions, which remain the same for the whole
loop run, outside of the loop.
Depends on:https://github.com/mcu-tools/mcuboot/pull/2013
=>  boot: Simplify copy loop in boot_copy_region

.github/workflows/zephyr_build.yaml
Updates the upload artifact version
=> ci: Fix zephyr workflow

docs/design.md
Fixes the memory-size-effective slot layout description for the swap move mode.
Adds information about the additional swap status area size.
=> doc: design: fix the memory-size-effective slot size description

.github/workflows/issue.yml, .github/workflows/issue_closed.yml
Fixes using the wrong repo name
=> ci: Fix issue and closed issue workflows

.github/workflows/issue.yml
Fixes moving to the correct project
=> ci: Fix issue assignment

.github/workflows/zephyr_build.yaml
Updates to a newer version of the zephyr docker image
=> ci: zephyr: Update docker image version

docs/encrypted_images.md
factory-programming procedure.
This doc will help to avoid false positive tickets like this one: #1555
=> doc: imgtool: importance of clear flag

docs/compression_format.md
=> docs: compression_format: Fix tags

boot/zephyr/Kconfig, boot/zephyr/flash_map_extended.c, boot/zephyr/include/mcuboot_config/mcuboot_config.h, boot/zephyr/include/target.h
Added basic adaptations needed for introducing
nrf54h20dk board support in the future.
=> boot/zephyr: nrf54h20dk adaptations

README.md, docs/release-notes.d/bootutil-enc-hw-keys.md, docs/release-notes.d/bootutil-image-verification.md, docs/release-notes.d/compatible-slots.md, docs/release-notes.d/encrypted-scratch-partition.md, docs/release-notes.d/espressif-idf-version-checking.md, docs/release-notes.d/fix-nordic.md, docs/release-notes.d/fix-ram-load-zephyr-address.md, docs/release-notes.d/fix-stuck-revert.md, docs/release-notes.d/fix-zephyr-sysbuild-name.md, docs/release-notes.d/imgtool_sanity_test.md, docs/release-notes.d/max-app-size-changes.md, docs/release-notes.d/serial-recovery-list.md, docs/release-notes.d/serial-recovery-slot-info.md, docs/release-notes.d/serial-recovery-var.md, docs/release-notes.d/swap-using-offset.md, docs/release-notes.d/zephyr-auto-max-sectors.md, docs/release-notes.d/zephyr-compression.md, docs/release-notes.md, repository.yml, scripts/imgtool/__init__.py
Consolidate the release notes, and update various release files.
=> Updates for 2.2.0-rc1 release

boot/zephyr/include/flash_map_backend/flash_map_backend.h
Adds an include file that is missing
Fixes #2289
=> boot: zephyr: flash_map: Fix missing include

boot/bootutil/src/encrypted_psa.c
Provide proper identifiers for size and partitioning of the HKDF output.
=> bootutil: Improve HKDF code

README.md, docs/index.md, docs/release-notes.md, scripts/imgtool/__init__.py
Update release notes and the various release version files.
=> Updates for 2.2.0-rc2 release

docs/release-notes.md
=> doc: release-notes: Add note on fix for single images

README.md, docs/index.md, docs/release-notes.md, scripts/imgtool/__init__.py
Update release notes and various release version files.
=> Updates for 2.2.0 release

scripts/imgtool/image.py, scripts/imgtool/main.py
This fixes issues when trying to compress images with no
header padding requested.
=> scripts: imgtool: Compression of no header-padded images

boot/zephyr/main.c
Add support for booting ARC processors to MCUBoot. ARC defines the reset vector as the first function pointer within the vector table.
=> boot: zephyr: add support for booting ARC processors

sim/mcuboot-sys/csupport/run.c, sim/mcuboot-sys/src/c.rs, sim/src/image.rs, sim/tests/core.rs
Directly load an image to RAM and see if that works.
=> sim: Test for boot_load_image_from_flash_to_sram API

boot/boot_serial/src/boot_serial.c
Also
boot: boot_serial: Fix upload for swap using offset mode
=> boot: boot_serial: Fix slot info response on error

docs/release-notes.d/single-slot-fixes.md
Adds details about some fixed serial recovery issues
=> docs: release-notes: Add details on some fixed issues

boot/bootutil/src/bootutil_priv.h
=> boot: bootutil: write_sz fix
