- sim/build.rs
- sim/src/main.rs
Bring in some commits to properly find source dependencies when building the simulator, and to properly build with the 'zephyr' change previously committed.
There is also an additional enhancement to test multiple reverts that the swap only happens one additional time to revert, and there is no re-reverting.
> Update sim to build

- boot/bootutil/src/loader.c
Instead of just checking the upgrade image signature, check the
signature on each boot.  This helps to prevent rogue images being flash
by a means other than the upgrade process.
This feature is controlled by whether BOOTUTIL_VALIDATE_SLOT0 is
defined.
> Validate slot zero before booting

- apps/boot/README.md
- apps/boot/pkg.yml
- apps/boot/src/boot.c
- apps/boot/syscfg.yml
This commit implements the sample Mynewt boot app.
I'm a little uncertain about the directory structure (apps/boot).  I chose one that makes sense for Mynewt.  I think I am not familiar enough with Zephyr to know how anti-social this is.  Other options are:
* Rename app to mynewt-boot; other OS apps are siblings.
* Create OS-specific top-level directories (mynewt/apps/boot).
I don't think it is a problem to rearrange things when we have a better idea of what we're going for, so I opted for simplicity for now.
> MCUB-3 Add sample Mynewt boot app.

- boot/zephyr/flash_map.c
- boot/zephyr/targets/96b_carbon.h
- boot/zephyr/targets/96b_nitrogen.h
- boot/zephyr/targets/frdm_k64f.h
- boot/zephyr/targets/nucleo_f401re.h
Let's stay in-sync automatically with Zephyr master by referring
to CONFIGs for the flash device names.
Signed-off-by: Michael Scott <michael.scott@linaro.org>
> zephyr: targets: update flash driver names to use Zephyr CONFIGs

- boot/bootutil/src/loader.c
commit d930ec69c835b83ba933677d29760ba7605a1158
Author: David Brown <david.brown@linaro.org>
Date:   Wed Dec 14 07:59:48 2016 -0700
Validate slot zero before booting
adds a feature to validate slot 0 before booting it.  However, there
is an error in the logic, and if the magic number is written to an
invalid value, but not all 0xFF, it will consider any image to be
valid.
Fix this logic so that slot zero is always validated.
> Fix slot0 validation

- boot/zephyr/flash_map.c
Flash must be unlocked before it can be erased.
Signed-off-by: Marti Bolivar <marti.bolivar@linaro.org>
> zephyr: fix flash_area_erase()

- scripts/zep2newt.py
Avoid hardcoding the python2 path by using env python2 instead.
Signed-off-by: Ricardo Salveti <ricardo.salveti@linaro.org>
> zep2newt.py: use /usr/bin/env when searching for python2

- sim/src/main.rs
In change
commit bb5635e07439c809d055d3413844c394c0b1b4bc
Author: Fabio Utzig <utzig@utzig.org>
Date:   Mon Apr 10 09:07:02 2017 -0300
Add test of multiple random resets while upgrading
in addition to adding the try_random_fails, it shuffled the order that
the initial interruption test ran.  However, this test always clones
the flash device, so it doesn't matter what order the tests are run.
Revert this part of the change to avoid unnecessary complexity in the
code.
> Back out unneeded part of random reset test

- apps/boot/src/boot.c
- boot/bootutil/include/bootutil/bootutil.h
- boot/bootutil/src/loader.c
- boot/bootutil/test/src/boot_test_utils.c
- boot/zephyr/flash_map.c
- boot/zephyr/include/flash_map/flash_map.h
- boot/zephyr/main.c
This reverts commit a52d7a21f01bd2859be9e62e20cbe029dc5e846c, reversing
changes made to d21abaaa35c31d88f9b4a18f82bce848adffb569.
Premature merge.  Will bring this back in after #41 merges.
> Revert "Merge pull request #49 from mbolivar/flash-map-updates"

- boot/bootutil/src/bootutil_misc.c
- boot/bootutil/src/bootutil_priv.h
- boot/bootutil/src/loader.c
- sim/src/c.rs
PLEASE DO NOT MERGE.
Trailer management, most importantly status, is now handled separately
from image sectors handling. This should fix issues with resets that
happen while doing a swap.
> Update to status management

- boot/bootutil/src/image_ec.c
- boot/bootutil/src/image_ec256.c
- boot/bootutil/src/image_rsa.c
- boot/bootutil/src/image_validate.c
- boot/bootutil/src/loader.c
Fix mapping of syscfg.yml BOOTUTIL_* vars to C #defines, which was broken
on most .c files for lacking inclusion of mynewt "config.h"
> Fix broken Mynewt BOOTUTIL_ -> MCUBOOT_ mapping

- boot/bootutil/include/bootutil/bootutil_log.h
- sim/src/api.rs
Change the C logging code, when in the simulator, to query what the rust
logging level is set to.  This allows the level of logging from the C
code to be set through the environment.  For example
RUST_LOG=bootsim=info cargo run --release runall
will enable logging at the "info" level for all of the C code as well as
the simulator code.  The C code's logging can be selected specifically
by using bootsim::api instead of just bootsim in the above.
> sim: Allow Rust logging level to control C logging

- scripts/imgtool.py
- scripts/imgtool/image.py
This helps with development, allowing the image to only get headers and a SHA256 hash.
Note that this PR includes PR#53, and should not be merged until it is merged.  Only the last commit is relevant to this patch.
> Add support for "signing" without a signature

- doc/imgtool.md
- scripts/imgtool.py
- scripts/imgtool/image.py
Zephyr defaults to having zero bytes at the beginning of the binary image as a gap allowing for the header. Other targets do not, so accommodate that.
This is built on top of pr#53 and shouldn't be merged until it goes in. Only the last patch is relevant to this PR.
> Make header padding optional

- doc/imgtool.md
The imgtool script explicitly calls out python3.  Adjust 'pip' to
'pip3' to reflect this explicit version call as well.
> doc: Fix 'pip' example

- Makefile
- boot/bootutil/include/bootutil/bootutil.h
- boot/bootutil/src/bootutil_priv.h
- boot/bootutil/src/loader.c
- boot/bootutil/test/src/boot_test_utils.c
- boot/mynewt/src/main.c
- boot/zephyr/flash_map.c
- boot/zephyr/include/flash_map/flash_map.h
- boot/zephyr/main.c
- sim/build.rs
- sim/csupport/run.c
This is basically a rewrite of the changes previously merged and then reverted in https://github.com/runtimeco/mcuboot/pull/49.
It gets us 99% of the way to resolving MCUB-54. The remaining portions require an out of tree series of patches in Zephyr to be merged (https://github.com/zephyrproject-rtos/zephyr/pull/205).
The main fix is to introduce, and then use, flash_device_base(). However, while we're changing API that mynewt also uses, I take the opportunity to add flash_area_get_sectors() and deprecate flash_area_to_sectors().
@d3zd3z, this switches to the new flash API by default in the simulator.
@mkiiskila, this should be even better for mynewt: you can take your time and implement flash_device_base() and flash_area_get_sectors() whenever you want. I have left a default …
> Flash map updates, redux

- boot/bootutil/include/bootutil/bootutil_log.h
- sim/src/flash.rs
A couple of tweaks to the simulator to make debugging a bit easier.
- Send logs to stderr, the stream that Rust's logs send them to
- Tighten up the checking on flash writes. Note that this breaks stm32f4 at least until #41 is merged.
> Simulator tweaks

- sim/csupport/run.c
Re-tab run.c to match the rest of the files in the system.  This was
indented using Zephyr conventions (tabs for indent).  Re-indent using
spaces, with a 4-space indent level.
> sim: Match spacing on csupport/run.c

- boot/bootutil/src/loader.c
- boot/zephyr/flash_map.c
This error was catched by Coverity and it happens when a fail occurs
opening a flash map handle, which is not checked by the close
routine.
Right now this only affects Zephyr, but extra checking was added
assuming that in a future Mynewt implementation close could actually
be changed to do something.
> Fixes trying to close an invalid flash map handle

- boot/bootutil/include/bootutil/bootutil.h
- boot/bootutil/src/bootutil_misc.c
- boot/bootutil/src/bootutil_priv.h
- boot/bootutil/src/loader.c
- scripts/imgtool.py
- scripts/imgtool/image.py
- sim/src/c.rs
- sim/src/flash.rs
- sim/src/main.rs
This implements issue MCUB-14.
Trailer was updated with magic moved to the end and flags now are 8 bytes no matter which is the flash write size. This makes it easier to write external apps the can read/write this data without having the get extra info from the bootloader itself.
> New trailer format

- sim/Cargo.lock
- sim/Cargo.toml
- sim/simflash/Cargo.toml
- sim/src/main.rs
Most dependencies can be updated without issue. The 'docopt' package used to parse the command line has an API change, which requires some changes, especially since we have a custom parser for the --align argument to restrict it to specific powers of two.
> Update upstream dependencies used in the simulator

- boot/bootutil/src/loader.c
The MCUBOOT_VALIDATE_SLOT0 feature only verifies the signature when
there is no swapping happening.  The assumption was that if there is a
swap being done, the code will verify the signature of slot 1 before
doing the slot.
However, either due to bugs, or intentional trickery, it may be possible
to confuse the code into continuing a swap operation.  If the data is
modified before this, the bootloader can be tricked into booting the
resulting image in slot 0 without having verified the signature.
Fix this by always verifying slot 0's signature before booting it.
JIRA: MCUB-64
> Always validate slot 0 when requested

- README-RIOT.rst
This PR adds a first README for the usage of MCUBoot with RIOT. It's a very basic version, inspired from the README for Zephyr.
> Add README-RIOT.rst

- sim/README.rst
Now that we depend on a submodule for mbed TLS code, update the docs to
explain how to fetch this.  Otherwise, the error is somewhat misleading,
just showing a missing sha256.c file.
> sim: Update doc to explain submodules

- boot/boot_serial/pkg.yml
- boot/boot_serial/test/pkg.yml
- boot/bootutil/pkg.yml
- boot/bootutil/test/pkg.yml
- boot/mynewt/pkg.yml
Also use a single email for all packages.
> Remove incubator references from mynewt dev email

- README-mynewt.rst
- boot/bootutil/include/bootutil/sha256.h
- boot/bootutil/pkg.yml
- boot/bootutil/src/image_ec.c
- boot/bootutil/src/image_ec256.c
- boot/bootutil/src/image_rsa.c
- boot/bootutil/src/image_validate.c
- boot/bootutil/src/loader.c
- boot/mynewt/mcuboot_config/include/mcuboot_config/mcuboot_config.h
- boot/mynewt/mcuboot_config/pkg.yml
- boot/mynewt/mcuboot_config/syscfg.yml
- boot/mynewt/pkg.yml
This fixes `newtmgr` when building `mynewt` images to be run on `mcuboot`. README file also added.
> Fix newtmgr

- boot/bootutil/src/loader.c
This fixes a warning (which results in error with `-Werror`) when building in overwrite only mode.
> Fix warning building with overwrite only

- boot/zephyr/prj.conf
- samples/zephyr/Makefile
Two minor fixes. One to be able to flash the full.bin target. The other needed in recent Zephyr trees to allow writes to the flash device.
> Minor zephyr fixes in since rc1

- README.md
> Fix Slack's URL info

- doc/signed_images.md
Also documents config option to use PKCS#1 v1.5 as images generated by
newt.
> Fix names of Mynewt config options

- boot/zephyr/prj-p256.conf
- boot/zephyr/prj.conf
Upstream has made a breaking namespace change. Keep up.
> zephyr: s/BLUETOOTH/BT/

- boot/bootutil/include/bootutil/bootutil.h
- boot/bootutil/include/bootutil/image.h
- doc/design.txt
This continues the work in MCUB-67. The substantial change is deleting the 'pending' / 'confirmed' state space in favor of one defined in terms of 'swap types'.
> Design doc fixups

- .gitignore
- boot/zephyr/targets/hexiwear_k64.h
The target is nearly identical to the frdm_k64f as far as mcuboot is concerned.
There is another fix to anchor the mynewt ignored directories so that Zephyr target files aren't ignored.
> Add support for Hexiwear k64

- boot/zephyr/targets/nrf52_blenano2.h
Adds a new zephyr target for the nrf52_blenano2. This is the BLE
Nano 2 board created by Red Bear which contains a NRF52832 MCU.
Signed-off-by: Tyler Baker <tyler.baker@linaro.org>
> zephyr: add nrf52_blenano2 target

- Makefile
- boot/zephyr/dts.overlay
- boot/zephyr/prj.conf
This pull request forces mcuboot to fit within the boot partition using a DTS overlay, and enables it to do so on at least one STM32 target where it currently doesn't fit.
I did a spot-check build of a couple of other boards with different SoCs (96b_nitrogen and frdm_k64f) to verify we're still in bounds there as well.
hexiwear_k64f doesn't support this, but the build is broken on that board right now already anyway due to lack of flash partitions, so that's fine.
> Zephyr: fit inside the boot partition again

- README-zephyr.rst
In order to build for a particular Zephyr board, the Device Tree
definition for it in the Zephyr tree must include the flash description.
> zephyr: doc: Mention the DT flash description

- boot/zephyr/targets/nrf51_pca10028.h
- boot/zephyr/targets/nrf52_pca10040.h
Add the 2 official Nordic Development Kit targets that are missing from
the list in mcuboot, but supported in Zephyr.
> zephyr: nrf5x: add nRF51 and nRF52832 dev kits as targets

- boot/bootutil/include/bootutil/image.h
Add a flag `IMAGE_F_RAM_LOAD` and an associated header field
`ih_load_addr` to indicate that a particular image should be loaded into
RAM instead of being executed directly out of flash.  If the flag is not
set, this field will be ignored.  If it is set, and this feature is
supported by the bootloader, the image will be loaded into RAM at the
address specified in the new header field.
None of this functionality is implemented at this time.  This is merely
to define the header format to avoid having to change the image format
later.
JIRA: MCUB-79
> Define the load_addr header field

- boot/bootutil/src/loader.c
This function is unused in overwrite-only mode.  Clang seems to catch
this, whereas gcc does not.  Add the proper ifdefs so that the
simulator tests all pass on MacOS.
> Fix warning on overwrite-only

- docs/index.md
URL was referencing old location for this script.
> Fix `imgtool.py` link in main webpage

- boot/bootutil/src/loader.c
This is helpful when testing an image that is not signed or signed with an invalid key.
> Log error message when slot fails validation

- docs/design.md
The swap procedure as documented doesn't match the code, and it would
loose the contents of slot1[index] as it's erased before it is copied
anywhere. Also, add the missing word 'to'.
Signed-off-by: Ryan C Johnson <ryan.johnson@flex.com>
> Correction to swap procedure design documentation

- repository.yml
When using the release version of mcuboot for mynewt I realised (thanks to @utzig) that the release v1.0.0 wasn't up-to-date in repository.yml.
This PR adds it and makes it the latest.
> Fix repository for v1.0.0

- samples/zephyr/hello-world/CMakeLists.txt
Replace https://www.zephyrproject.org/doc/dts/device_tree.html with
http://docs.zephyrproject.org/devices/dts/device_tree.html
Signed-off-by: Ding Tao <miyatsu@qq.com>
> zephyr: Fix an invalid url in file CMakeLists.txt

- boot/bootutil/src/bootutil_misc.c
- boot/bootutil/src/image_rsa.c
- boot/bootutil/src/loader.c
- sim/mcuboot-sys/csupport/run.c
Fixes warnings treated as errors when upgrading gcc crate to 0.3.54. Warnings are due to non-used variables and comparison between signed and unsigned.
> Fix for gcc warnings

- .travis.yml
- scripts/check-signed-off-by.sh
Instead of trying to determine current branch using git, just rely on travis to know if this is a PR and if it is not, don't do signed-off-by checking.
> Use travis env variable to control check-signed-off-by

- scripts/imgtool.py
- scripts/imgtool/__init__.py
- scripts/imgtool/image.py
- scripts/imgtool/keys.py
- scripts/imgtool/version.py
Although these files are likely implicitly licensed under the Apache 2.0
license because of the LICENSE file for this project, make this explicit
in these files.
> imgtool: Add explicit license declarations

- .travis.yml
- boot/bootutil/src/bootutil_misc.c
- boot/bootutil/src/bootutil_priv.h
- boot/bootutil/src/loader.c
- sim/Cargo.lock
- sim/Cargo.toml
- sim/mcuboot-sys/Cargo.toml
- sim/mcuboot-sys/build.rs
- sim/mcuboot-sys/csupport/bootsim.h
- sim/mcuboot-sys/csupport/run.c
- sim/mcuboot-sys/src/c.rs
- sim/simflash/Cargo.toml
- sim/simflash/src/lib.rs
- sim/src/lib.rs
- sim/tests/core.rs
TLDR: this changes how mcuboot handles write fails to the status area (trailer metadata), allowing writes to fail as long as writes to the image data do not fail, and slot 0 validation is enabled. The usual behavior of aborting on any write failure is retained if slot 0 validation is disabled.
Beyond the changes to the swap write routines, some new stuff was added to the simulator to enable more thorough testing of this change:
* Enable/disable setting to check writes to non-erased areas;
* Allow declaring `bad memory` regions;
* Enable catching asserts.
Both of those are used by new tests. The assert stuff is used by a new test that was added to ensure that write failures with validation of slot 0 disabled are caught without breaking the test (it is expected to assert!). The bad memory …
> Do not assert on status write fails

- README-zephyr.rst
frdm_k64f.dts has been moved to boards/arm/frdm_k64f/
Signed-off-by: Dong Xiang <dong.xiang@linaro.org>
> Correct the path of zephyr sample dts file

- boot/bootutil/src/image_validate.c
- boot/bootutil/src/loader.c
> Avoid using uninitialized memory in split go

- scripts/assemble.py
Although this file is likely implicitly licensed under the Apache 2.0
license because of the LICENSE file for this project, make this explicit
in this file.
> assemble.py: Add explicit license declaration

- README.md
- boot/zephyr/targets/arduino_101.h
- docs/release-notes.md
The correct spelling is "MCUboot", so replace the instances that differ
from this.
> doc: Fix MCUboot capitalization

- boot/zephyr/CMakeLists.txt
When a relative path was used the build would fail when CMake was
invoked with the -B -H flags. Using an absolute path for the
dts.overlay flags fixes #187.
Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>
> zephyr: boot: Use abs. path instead of rel. path for dts overlay

- boot/zephyr/CMakeLists.txt
Since the Kconfig file was moved in 51a09210063 ("zephyr: Move Kconfig
file to boot/zephyr"), the CMakeLists.txt reference to it needs updating.
> zephyr: fix the build

- samples/zephyr/run-tests.go
Enhance the test runner so that it can verify the output of the tests by
itself.  This needs the console to be logged to a file, but otherwise
works the same as the current test runner.
Also, the build results are placed in a log file, so that it is easier
to see what is happening.
> zephyr: Create a test runner for the samples

- boot/zephyr/CMakeLists.txt
When the target doesn't have good enough generic support for MCUBoot,
you can specify the flash layout etc on a per-board basis by creating
a header, boot/zephyr/targets/BOARD.h.
The build system tries to pick this up, but isn't doing it
correctly. Fix it.
> zephyr: fix MCUBOOT_TARGET_CONFIG definition

- boot/zephyr/CMakeLists.txt
It's recommended practice to mass erase the flash chip before
reflashing mcuboot. Add a configuration option for Zephyr which does
this by default on some Zephyr runner backends which can support
this (pyOCD and dfu-util). Additional runners can be added as needed (and possible).
> zephyr: try to mass erase when flashing

- boot/zephyr/include/target.h
The upstream Zephyr project is renaming FLASH_DRIVER_NAME to
FLASH_DEV_NAME as part of some changes related to device tree.
Work around this for now by keeping the MCUboot name the same if
FLASH_DRIVER_NAME is not provided by Zephyr, but FLASH_DEV_NAME is.
> zephyr: add compatibility shim for flash driver name

- docs/design.md
- docs/index.md
- docs/readme-zephyr.md
- docs/release-notes.md
Github pages assumes that links to files using relative names point to the same location so this should work both when accessing through the github browser and mcuboot.com
> Change all doc links to use relative names

- boot/bootutil/src/image_rsa.c
Adds a fix for mbed TLS 2.7.0, as well as brings in mbed TLS 2.7.0 so it will get tested regularly.
> Fix for mbed TLS 2.7.0.

- boot/zephyr/os.c
This defines the correct "mbedtls" config files in both ECDSA256 and RSA modes.
> Fix configuration when RSA signature is used

- boot/bootutil/src/loader.c
BOOT_STATUS_ASSERT increments the variable if the macro argument
is evaluated as true, which is incorrect behavior compared to the
ASSERT macro.
> bootutil: loader: fix BOOT_STATUS_ASSERT macro

- boot/zephyr/include/config-boot.h
Although MCUboot has used PKCS#1 v2.1 (PSS) for some time now, the mbed
TLS config file was calling out v1.5.  This compiled because MCUboot
implements its own specialized version of the signature check, and only
needs the underlying primitives from mbed TLS.  (The general code in
mbed TLS is quite a bit larger).
To make it clear that we are always using PSS, change the mbed TLS
configuration to call this out explicitly.
> zephyr: Configure mbed TLS for PSS instead of V1.5

- boot/mynewt/pkg.yml
The boot loader app needs all the base dependencies, whether or not
`BOOT_SERIAL` is enabled.  Therefore, it makes sense for the serial boot
loader to add to, rather than replace, the dependency list.
This bug in the pkg.yml file went unnoticed ealier because of an issue
in newt: it used to effectively ignore the `.OVERWRITE` suffix when it
was applied to `pkg.deps`.
NOTE: this change was made to the Mynewt boot loader in this PR: https://github.com/apache/mynewt-core/pull/784
> Mynewt app: Remove .OVERWITE suffix from pkg.deps

- boot/zephyr/main.c
The macro _MspSet has gone away in Zephyr.  Change to use the __set_MSP
macro from the CMSIS code that has always been present.  This allows
mcuboot to build with Zephyr after:
commit c028f88b37d2a033d6a85c8d365ef048e1e4d621
Author: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>
Date:   Mon Mar 12 10:45:02 2018 +0100
arch: arm: remove redundant asm inline headers
Fixes #246.
> zephyr: arm: Use proper macro to set MSP

- boot/zephyr/CMakeLists.txt
Allow the user to add additional device tree overlays onto the default one that sets up the code partition.
> zephyr: CMakeLists: allow users to specify DTC_OVERLAY_FILE fragments

- boot/boot_serial/src/CMakeLists.txt
- boot/boot_serial/src/boot_serial.c
- boot/zephyr/Kconfig
Instead of relying on mbedTLS' base64 codec, use the new Zephyr base64
library.
> boot_serial: zephyr: Use new base64 library

- boot/boot_serial/src/boot_serial.c
- boot/zephyr/os.c
Following warnings were fixed within this patch:
'isspace' macro should take an int value
function 'bs_reset' should return void
redefinition of 'MBEDTLS_CONFIG_FILE' macro while
it is already defined by the zephyr build system.
> fix warnings while building along with serial recovery

- scripts/imgtool.py
The imgtool's `sign` command also works without a key, but it doesn't
sign, only appends a hash.  Add a `create` alias to this command so that
this usage makes more sense.
Fixes #240
> imgtool: Add 'create' alias for 'sign'

- boot/mynewt/src/main.c
- docs/readme-mynewt.md
This fixes an issue where while doing an image upload `newtmgr`/`mcumgr` would send packets that were impossible do base64decode in a 128 byte buffer.
> Fix boot_serial size of allocated buffers

- docs/Gemfile.lock
https://nvd.nist.gov/vuln/detail/CVE-2017-18258
> Update nokogiri due to CVE-2017-1825

- boot/boot_serial/test/pkg.yml
- boot/bootutil/test/pkg.yml
This PR addresses the following newt errors:
```
[ccollins@ccollins-mac:~/tmp/myproj3]$ newt test @mcuboot/boot/bootutil @mcuboot/boot/boot_serial
Testing package @mcuboot/boot/bootutil/test
Could not resolve package dependency: @mcuboot/test/testutil; depender: boot/bootutil/testTesting package @mcuboot/boot/boot_serial/test
Could not resolve package dependency: @mcuboot/test/testutil; depender: boot/boot_serial/test
Error: Test failure(s):
Passed tests: []
Failed tests: [boot/bootutil/test boot/boot_serial/test]
```
The unit tests depend on a few Mynewt packages (`test/testutil` and `sys/console/stub`).  If there is no repo prefix in the dependency specifier, newt assumes the package is in the local repo (mcuboot)`.  This PR adds the `@apache-mynewt-core/` prefix to these dependencies. …
> Mynewt unit tests - Add repo prefix to dependency lists

- boot/bootutil/include/bootutil/image.h
- scripts/imgtool.py
- scripts/imgtool/image.py
This removes the old "TLV size" and "keyId" fields that used to exist in the old image header format and updates it to use `load_addr`. Also fixes the name of reserved fields to index from 1.
This fixes #279 
> Fix leftovers from image_header v1

- sim/mcuboot-sys/csupport/bootsim.h
- sim/mcuboot-sys/csupport/mcuboot_config/mcuboot_assert.h
These (currently) trivial files do not add license headers.  Go ahead
and add the boilerplate Apache header.
In addition, I've also added an SPDX header.  Although this is a first
for the MCUboot project, this will provide a template for adding these
headers to other files.
Fixes #282
CC: Marti Bolivar <marti@opensourcefoundries.com>
CC: Fabio Utzig <utzig@apache.org>
> sim: Add missing license headers

- scripts/assemble.py
Zephyr has changed the format of macros used to define flash
area partitions. These strings no longer contain the `_0` suffix
> Fix regexp matchers for FLASH_AREA_* defines in assemble.py

- scripts/imgtool.py
- scripts/imgtool/image.py
This adds a new command line flag to allow passing in the max number of sectors for a swap when the image is padded. It defaults to 128 and should match the value configured in the bootloader.
Fixes #285
> Allow passing max sectors as parameter to imgtool

- samples/zephyr/Makefile
- scripts/imgtool.py
- scripts/imgtool/image.py
Add the new `--slot-size` and make `--pad` a bool flag, to allow checking that firmware fits in the slot without overflowing into the trailer region even when no padding was requested.
Fixes #241
>  Add --slot-size to allow size checking without pad

- boot/zephyr/CMakeLists.txt
Replace "bur" with "but".
Signed-off-by: Ding Tao <miyatsu@qq.com>
> zephyr: cmake: Fix a typo in file CMakeLists.txt

- boot/zephyr/prj.conf
In order to provide a pleasant out-of-the-box experience to users,
default to the RSA .pem file so that users do not get a cryptic error
when building with the default .conf file in upstream.
> zephyr: Default to RSA .pem file in config fragment

- boot/bootutil/src/loader.c
- scripts/imgtool.py
- scripts/imgtool/image.py
Overwrite only requires just magic + image_ok + copy_done. This fixes issues generating images in overwrite only mode when the firmware image is too big and overflows the swap status area.
> Allow passing in `--overwrite-only` flag

- boot/zephyr/main.c
For serial recovery enabled Assertions conditions were improperly
which cause runtime assertion whenever __ASSERT macro was enabled
along with the serial recovery mode running.
This patch fixes the issue.
Signed-off-by: Andrzej Puzdrowski andrzej.puzdrowski@nordicsemi.no
> Fix assertions in zephyr main file

- boot/boot_serial/include/boot_serial/boot_serial.h
- boot/boot_serial/pkg.yml
- boot/boot_serial/src/CMakeLists.txt
- boot/boot_serial/src/boot_serial.c
- boot/boot_serial/src/boot_serial_priv.h
- boot/boot_serial/syscfg.yml
- boot/boot_serial/test/pkg.yml
- boot/boot_serial/test/src/boot_test.c
- boot/boot_serial/test/src/testcases/boot_serial_empty_img_msg.c
- boot/boot_serial/test/src/testcases/boot_serial_img_msg.c
- boot/boot_serial/test/src/testcases/boot_serial_upload_bigger_image.c
- boot/boot_serial/test/syscfg.yml
- boot/mynewt/boot_uart/include/boot_uart/boot_uart.h
- boot/mynewt/boot_uart/pkg.yml
- boot/mynewt/boot_uart/src/boot_uart.c
- boot/mynewt/mcuboot_config/syscfg.yml
- boot/mynewt/src/main.c
- boot/mynewt/syscfg.yml
- boot/zephyr/main.c
- boot/zephyr/serial_adapter.c
Serial bootloader size was too big, so
- got rid of snprintf() reference
- got rid of cborattr
And on Mynewt side of size reduction:
- tuned kernel/os to not bring memory pool code
- replace minimal console with a more direct way of accessing uart
On some platforms the watchdog keeps running post-reset, and mynewt users have a gpio reporting when waiting for serial DFU. Therefore changed the code to pass platform specific routines to do reads and writes from uart. This allows Mynewt side to do it's watchdog tickling, gpio toggling without polling common code.
Unittests on mynewt side are still broken, but they've been so even before. So I'll create another PR to address those later.
Signed-Off-By: Marko Kiiskila <marko@apache.org>
> boot_serial rework

- docs/imgtool.md
- samples/zephyr/Makefile
- scripts/imgtool.py
- scripts/imgtool/image.py
The `--included-header` was "mandatory" when using imgtool with firmware images generated by the Zephyr build system and it was a source of issues when it was forgotten. This removes `--included-header` and adds a new parameter `--pad-header` with inverted semantics, to be used only when a zeroed header is required to be added to the firmware image.
Also updated imgtool documentation.
> Update `--included-header` usage and documentation

- boot/mynewt/src/main.c
This fixes an issue where the bootloader is activating a timer that is later not used by the installed target image causing a non handled interrupt fault.
> Deinit timer after serial load is finished

- boot/zephyr/main.c
While building with Zephyr 1.12 for the nucleo_f091rc I got undefined
reference to __set_MSP() during linking. Including soc.h fixes the
problem. Thanks carlesc.
> include soc.h in main.c

- boot/boot_serial/CMakeLists.txt
- boot/boot_serial/src/CMakeLists.txt
- boot/zephyr/CMakeLists.txt
> boot_serial: Fix build on Zephyr with ECDSA enabled

- sim/Cargo.lock
- sim/Cargo.toml
- sim/simflash/Cargo.toml
This updates error-chain to remove a warning on recent rust distros. `pem` was update to get fairly recent `error-chain` as well.
> Update sim dependencies

- scripts/assemble.py
Given the example lines:
#define FLASH_AREA_MCUBOOT_OFFSET_0 0x0
#define FLASH_AREA_MCUBOOT_OFFSET   FLASH_AREA_MCUBOOT_OFFSET_0
Changing OFFSET_0 to OFFSET(_0)? allows the re to possibly match the
second line where it would have stopped the match before. This combined
with the (0x)? means that the re does match the second line, with the
third group being just the F of FLASH_AREA_IMAGE_1_OFFSET_0. The int()
function fails because F is not a valid number. This commit makes the
matching more precise by 1) matching the 0x when there are hex digits
and without the 0x when there are decimal digits and 2) matching until
the end of the line.
> fix the offset and size regular expressions in assemble.py

- docs/imgtool.md
- scripts/imgtool/image.py
Adjusts the "base address" in an intel hex file if using "--pad-header."
If adding a header to a .hex file (using the command line "--pad-header"), the hex file gets shifted by HEADER_SIZE. This may cause hard coded addresses to be off by "header-size", making the firmware unusable. Instead, adjust the base address by the header size, so the existing firmware in the hex file is loaded to the proper addresses.
I'm not sure I've thought through all use cases here. But I've found the using --pad-header results in an invalid firmware image when passing in a hex file.
> imgtool: Adjust base_addr when injecting header

- boot/mynewt/src/main.c
On Mynewt some flash drivers on very slow devices tickle the watchdog to avoid possible hangs; those were also trying to tickle the watchdog in mcuboot when performing an upgrade or serial boot, without initializing the watchdog, causing an invalid memory write and reset issue.
> Initialize watchdog when running on Mynewt

- boot/boot_serial/src/boot_serial.c
- boot/zephyr/CMakeLists.txt
- boot/zephyr/Kconfig
- boot/zephyr/flash_map_extended.c
- boot/zephyr/include/flash_map_backend/flash_map_backend.h
- boot/zephyr/main.c
- boot/zephyr/serial_adapter.c
- Fixed ISR in serial_adapter to work with USB CDC ACM serial emulation. This commit prepares mcuboot for coming USB support patch.
- Added an option to erase flash pages progressively to avoid possible timeouts
This PR contains code which was separated form previous PR #318
Signed-off-by: Emanuele Di Santo <emdi@nordicsemi.no>
Signed-off-by: Emanuele Di Santo <andrzej.puzdrowski@nordicsemi.no>
> Erase flash pages progressively

- docs/PORTING.md
`bootutil` was updated to use exclusively `flash_area_align` removing the dependency on this single `hal_flash` function.
> Remove hal_flash_align from porting requirements

- docs/readme-zephyr.md
This patch documents requirements and dependencies necessary to build
mcuboot on Zephyr.
Signed-off-by: Piotr Mienkowski <piotr.mienkowski@gmail.com>
> docs: zephyr: add "Installing Requirements and Dependencies"

- boot/zephyr/include/config-rsa.h
- boot/zephyr/prj.conf
MCUboot is generating unnecessary warnings during its build. Fix them.
> Zephyr configuration fixes

- sim/mcuboot-sys/build.rs
- sim/mcuboot-sys/csupport/run.c
This also updates the RSA test to add extra build files for zeroize, and updates to new calloc/free configuration style.
> Update mbedtls submodule to 2.12.0

- boot/bootutil/src/bootutil_misc.c
- boot/bootutil/src/bootutil_priv.h
- boot/bootutil/src/loader.c
- boot/zephyr/flash_map_extended.c
- boot/zephyr/include/flash_map_backend/flash_map_backend.h
- sim/mcuboot-sys/csupport/flash_map.h
- sim/mcuboot-sys/csupport/run.c
- sim/mcuboot-sys/src/c.rs
- sim/simflash/src/lib.rs
- sim/src/lib.rs
This updates `mcuboot` and the simulator to allow flash devices that are not erased to 0xff, which is the case on STM32L1 and STM32L0 (maybe others!) both of which employ a flash technology that erases to 0.
An associated PR for Mynewt (https://github.com/apache/mynewt-core/pull/1323) must be merged first. A small `Zephyr` mock will be added soon.
> Support flash devices erased at 0

- boot/bootutil/src/bootutil_misc.c
It was impossible to set confirm flag due to incorrect comparison.
In this point of time state->image_ok is already decoded and contains
one of following values:
If BOOT_FLAG_UNSET then we are ok to set a confirm flag.
> Fix setting confirm flag

- boot/bootutil/src/bootutil_misc.c
This compliments the previous change on `image_ok` and also removes `flash_area_erased_val` call that is not needed anymore.
> Fix copy_done setting

- scripts/imgtool.py
- scripts/imgtool/image.py
Add big endian support to imgtool so that it can be used on big endian targets.
Signed-off-by: Mark Schulte <mschulte@lyft.com>
> [imgtool] Add big endian support

- boot/bootutil/src/bootutil_misc.c
- boot/bootutil/src/loader.c
- boot/zephyr/flash_map_extended.c
- boot/zephyr/include/flash_map_backend/flash_map_backend.h
- sim/mcuboot-sys/csupport/flash_map.h
- sim/mcuboot-sys/csupport/run.c
Mynewt has recently added an encrypted flash layer driver, that runs transparently on any flash, handling reads and writes, and bypassing other flash operations to the HW driver. As a result of this change, checking for erased data cannot be done by read + compare to `erased_val` but need to be routed to an empty check on the lower level. To do this Mynewt added a new `flash_map` function called `flash_area_read_is_empty` which checks for erased blocks (and reads/decrypts the data as well).
This commit uses `flash_area_read_is_empty` to determine if magic, flags and swap status are erased. For Zephyr/sim commits were added previously that mimic this functionality by simply doing the read/compare.
PS: This might be required on very slow MCUs under Mynewt: …
> Test erased flash with flash_area_read_is_empty()

- boot/zephyr/flash_map_extended.c
Implementation of flash_area_read_is_empty introduced recently
uses deprecated hal_flash_read API which caused build failure.
This patch uses zephyr's native flash_area_read() API which
solves the bug.
> zephyr: fix flash_area_read_is_empty

- scripts/check-signed-off-by.sh
This should print out what was expected and is missing in the "Signed-off-by" lines from a commit.
> Print missing Signed-off-by line info

- scripts/imgtool.py
Avoid passing invalid `encrypt` param to image constructor.
> Fix imgtool encrypt rebase issue

- version.yml
This file lets newt determine the version of the mcuboot repo.  Without this file, newt reports this annoying warning on each operation:
```
WARNING: Could not detect version of installed repo "mcuboot"; assuming 0.0.0/178be54bd6e5f035cc60e98205535682acd26e64
```
> Mynewt: Add `version.yml` file

- README.md
- docs/index.md
This will fix #336 by adding deprecation warning to Jira and
Confluence links as these are not used by the project anymore.
Signed-off-by: Sigvart Hovland <sigvart.hovland@nordicsemi.no>
> Add deprecated warning to Jira and Confluence links

- boot/bootutil/src/image_rsa.c
- In later versions of mbedtls than `mbedtls-2.6.1` need set the 'len' of struct mbedtls_rsa_context before run `mbedtls_rsa_check_pubkey(ctx)`
- Fixed by using mbedtls function `mbedtls_rsa_import`
- `mbedtls_rsa_import` is not existed in version `mbedtls-2.6.1` and the previous version
- Now supports the newest version `mbedtls-2.13.1`
- Execute `mbedtls_rsa_import` before `mbedtls_rsa_check_pubkey` in `bootutil_parse_rsakey` : _line 65 in image_rsa.c_
```
static int bootutil_parse_rsakey(mbedtls_rsa_context *ctx, uint8_t **p, uint8_t *end) {
...
/* The mbedtls version is more than 2.6.1 */
#if MBEDTLS_VERSION_NUMBER > 0x02060100
rc = mbedtls_rsa_import(ctx, &ctx->N, NULL, NULL, NULL, &ctx->E);
if (rc != 0) {
return -5;
}
#endif
rc = mbedtls_rsa_check_pubkey(ctx);
if (rc != 0) {
return …
```
> Fixed an issue that supported later versions of mbedtls than mbedtls-2.6.1 in RSA validation

- boot/zephyr/Kconfig
Add a hidden MCUBOOT config entry to mark a project as MCUBOOT.
It is useful when other parts of the system need to be aware that they are, in fact, the bootloader.
@nvlsianpu
> boot: zephyr: add MCUBOOT config

- boot/zephyr/include/target.h
- boot/zephyr/main.c
Zephyr target was corrupted as recntly zephyr's device tree
started adding DT_ prefix in generated labels.
This path aligns flash name macro used.
> fix zephyr target: corrupted build after zephyr PR #11180

- README.md
- docs/SubmittingPatches.md
- docs/index.md
- docs/readme-mynewt.md
- testplan/mynewt/project.yml
This updates all references from `github.com/runtimeco` to `github.com/JuulLabs-OSS` in docs and yml files.
> Fix main github repo links in docs

- scripts/imgtool.py
Throw exception on values that are less than the minimum acceptable size of 32 bytes.
> Add minimum size validation for header parameter

- scripts/imgtool.py
- scripts/imgtool/image.py
Generating images with no signature or encryption was broken by commit 06b77b835336d80c102e35f7c6da997d9380c9b8
This allows generating images with just sha256 again, and fixes a few leftovers from the imghash TLV change.
> Fix image creation without sign/encryption

- .travis.yml
- boot/bootutil/include/bootutil/image.h
- boot/bootutil/src/image_validate.c
- boot/bootutil/src/loader.c
- boot/zephyr/include/mcuboot-mbedtls-cfg.h
- boot/zephyr/os.c
- sim/mcuboot-sys/build.rs
- sim/src/lib.rs
- sim/src/tlv.rs
The visible issue here is that there was an assert checking header size against a buffer that was supposed to run only on encrypted images but was missing the `#ifdef`ery. This cause images with headers larger than 256 bytes to fail, regardless of the encrypted image setting.
This patch fixes the issue by adding correct support for encrypted images, regardless of the header size.
I added a patch to the simulator to run the testing with header size equal to 512 bytes, which I will drop before merging this PR, although I find it valuable to have a test like this, a better way to parametrize this has to be found, and also avoid running every test both on 32 and 512 byte headers.
> Fix encrypted support for images with header sizes larger than 256 bytes

- boot/bootutil/src/bootutil_misc.c
- boot/bootutil/src/image_validate.c
While porting MCUboot to a bare matel chip without OS (NXP LPC824) I found some unused includes.
After this pull request only four headers are required for a new target system:
"sysflash/sysfash.h"
"flash_map_backend/flash_map_backend.h"
"mcuboot_config/mcuboot_config.h"
"os/malloc.h"
The header "os/malloc.h" is only required by the split_go() function.
I my port I also removed split_go() but I’m not sure what it does so I kept it here.
Let’s see if CI passes or if I missed some details.
> Remove unused hal includes from bootutil

- sim/Cargo.lock
- sim/Cargo.toml
- sim/mcuboot-sys/Cargo.toml
- sim/mcuboot-sys/src/api.rs
- sim/mcuboot-sys/src/c.rs
- sim/mcuboot-sys/src/lib.rs
- sim/simflash/Cargo.toml
- sim/simflash/src/lib.rs
- sim/src/lib.rs
- sim/src/main.rs
- sim/tests/core.rs
Rust 2018 is now part of the stable compiler.  The 2018 brings numerous minor improvements, along with a few significant ones (such as non-lexical lifetimes).  This patchset migrates to code of the simulator to work with Rust 2018.  There are typically two patches for each crate, one that applies the minimal changes to allow the code to work with Rust 2018, and another that then makes the code more idiomatic. Both are largely automated, using commands described in the commit messages.
> Move to Rust2018

- boot/bootutil/include/bootutil/enc_key.h
Mynewt builds require the `mcuboot_config.h` file to translate syscfg setting names to MCUboot setting names.  This change fixes a build error that occurs when MCUboot is built with mbedTLS support:
```
Error: In file included from keys/bootkeys/src/bootkeys.c:2:0:
repos/mcuboot/boot/bootutil/include/bootutil/enc_key.h:29:10: fatal error: tinycrypt/aes.h: No such file or directory
#include "tinycrypt/aes.h"
^~~~~~~~~~~~~~~~~
```
> boot/bootutil: Add missing #include

- boot/bootutil/src/loader.c
As reported by issue #384, some #ifdefery was wrongly done, which broke overwrite-only mode under Zephyr.
> Fix overwrite-only mode under Zephyr

- boot/boot_serial/src/boot_serial.c
The `crc16.h` header has been deprecated in favor of `crc.h`.
Include the new header to prevent the warning.
> zephyr: boot_serial: fix crc header warning

- sim/Cargo.lock
- sim/Cargo.toml
- sim/simflash/Cargo.toml
- sim/src/main.rs
- sim/src/testlog.rs
Since logging was broken due to incompatibility between `log` and `env_logger` versions, those crates were updated to known to be compatible versions. Update initialization of `env_logger` that does not return a Result<> anymore.
Other crates were updated to remove duplicated versions as much as possible.
> Update simulator dependencies

- boot/boot_serial/test/pkg.yml
- boot/mynewt/pkg.yml
A recent change in the Mynewt repo (`b10cbea5ef882e7f91d1c34ffcf2506d3e183003`) imposes the LOG API requirement on the `sys/mfg` package.  To fix broken builds, make the Mynewt app and test package depend on `sys/log/stub`.
> Fix Mynewt builds; add log stub dependency

- boot/zephyr/boards/nrf52840_pca10059.conf
The board cannot output logs on the UART because it is used by MCUBoot's serial recovery for DFU. Remove logging and the RTT console from project defaults.
> boot: zephyr: pca10059: disable logging by default

- boot/zephyr/Kconfig
Select GPIO when MCUBOOT_SERIAL is enabled, so that the bootloader won't hardfault when trying to obtain the bindings to the GPIO driver.
@nvlsianpu have a look when you can, thank you.
> boot: zephyr: select GPIO when MCUBOOT_SERIAL is enabled

- boot/zephyr/CMakeLists.txt
Commit 3ac36ead3 updated the bundled asn1parser, which now consists of two files. The Zephyr build system was not updated with that commit which has broken ECDSA signature builds. This adds the new file.
This fixes #397.
> Fix ECDSA signature builds in Zephyr

- ptest/.gitignore
- ptest/Cargo.lock
- ptest/Cargo.toml
- ptest/src/main.rs
This is a small utility that facilitates doing the Travis-style parallel tests during development. To use, `cd ptest`, and `cargo run`. It will read the configuration from the `.travis.yml` file.
> Create ptest utility

- samples/zephyr/overlay-ecdsa-p256.conf
Set the public key for ECDSA tests to use the ECDSA.  This avoids a link
error with:
../app/libapp.a(keys.c.obj):(.rodata.bootutil_keys+0x0): undefined reference to `ecdsa_pub_key'
../app/libapp.a(keys.c.obj):(.rodata.bootutil_keys+0x4): undefined reference to `ecdsa_pub_key_len'
> samples/zephyr: Build ECDSA tests with ECDSA key

- boot/zephyr/CMakeLists.txt
- boot/zephyr/Kconfig
Misc. modernizations and cleanups of the MCUBoot build scripts in preparation for a future PR that will resolve https://github.com/zephyrproject-rtos/zephyr/issues/7868
> Modernize zephyr build scripts

- repository.yml
Newt only allows the following stability strings in a repo version:
VERSION_STABILITY_NONE   = ""
VERSION_STABILITY_STABLE = "stable"
VERSION_STABILITY_DEV    = "dev"
VERSION_STABILITY_LATEST = "latest"
VERSION_STABILITY_COMMIT = "commit"
An attempt to update a project that uses mcuboot would choke due to the invalid stability string "rc1":
```
Error: Unknown stability (rc1) in version 1.3.0-rc1
```
> [Mynewt] repository.yml: Remove invalid stability "rc1"

- boot/zephyr/boards/nrf51_pca10028.conf
Disable logging and enable size optimizations on
nrf51_pca10028 target in order to fit in boot slot size
for out-off-the-box build.
fixes #411
> zephyr:board: squash nrf51_pca10028 flash footprint

- boot/bootutil/src/bootutil_misc.c
This change affects the "set pending" operation.  That is, the operation that configures mcuboot to temporarily swap images on the next boot.
If the slot 1 trailer contained an invalid 128-bit magic number, an assertion would fail, causing a crash.
If corruption is detected in the slot 1 trailer, the entire image slot is erased, and the "set pending" operation fails with a `BOOT_EBADIMAGE` status.
mcuboot cannot meaningfully recover from data corruption.  The only recourse is to erase the bad data so that future upgrades can be performed.  I was tempted to add a build-time setting to control whether the image slot gets erased when corruption is detected, but I dont think this
freedom justifies the cost of extra config.  A device with a corrupt image slot can no longer be upgraded, so the …
> Set pending: don't crash when image slot corrupt

- boot/zephyr/CMakeLists.txt
NOTE: depends on https://github.com/zephyrproject-rtos/zephyr/pull/6809 -- DO NOT MERGE unless that's merged as well
The upstream Zephyr runner for nrfjprog now supports an --erase
toggle, which controls whether a mass-erase is done. Add that to its
invocation when CONF_ZEPHYR_TRY_MASS_ERASE is given, just like is done
for dfu-util and pyocd.
> zephyr: CMakeLists.txt: support nrfjprog mass erase flag

- boot/bootutil/src/loader.c
In case if no image is loaded and the `MCUBOOT_VALIDATE_SLOT0` is enabled, the current implementation will stuck at this assertion. This means when assertions will be evaluated that the if-statement after the assertion is dead code.  I think no image loaded shouldn't be a case which will be catched with an assertion.  
What do you think ?
> Do not use an ASSERT to catch the case if no image is loaded

- boot/boot_serial/src/boot_serial.c
- boot/zephyr/serial_adapter.c
zephyr macro min() was hanged to MIN()
Kconfig key CDC_ACM_PORT_NAME was changed to CDC_ACM_PORT_NAME_0
zephyr sha of the fixing time is https://github.com/zephyrproject-rtos/zephyr/commit/406dc2cb0e2868392f444677ace416440695829f.
> zephyr: fix build with zephyr

- boot/zephyr/serial_adapter.c
Zephyr changed way of generation UART device name label
which implies device name label text change.
Patch aligns the code to above change.
> zephyr: align uart device name

- boot/zephyr/CMakeLists.txt
The pattern that 'set_conf_file' has been added to the Zephyr build
system, so it is not necesary for the application build script to
implement it.
Also, the macro has been deprecated, so it should not be used.
This change is a pure refactoring.
Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>
> zephyr: cmake: Don't declare the deprecated macro set_conf_file

- boot/bootutil/pkg.yml
- boot/mynewt/src/main.c
This changes are required to fix build on Mynewt when using the HW crypto framework (currently a proposal available here: https://github.com/apache/mynewt-core/pull/1649)
> Add Mynewt configuration to enable HW crypto

- boot/bootutil/include/bootutil/enc_key.h
- boot/bootutil/src/encrypted.c
- boot/zephyr/flash_map_extended.c
- boot/zephyr/include/flash_map_backend/flash_map_backend.h
- sim/mcuboot-sys/csupport/run.c
enc_state table was indexed with assumption that
image flash area are subsequent and increasing numbers.
It might not be true while building zephyr.
Patch introduce flash_area_id_to_image_slot() implementation for
the zephyr port and uses it to assign proper slot number.
This API is already available in MyNewt.
> image encryption: fix enc_state array indexing for zephyr

- ci/mynewt_run.sh
- ci/mynewt_targets/bootserial/syscfg.yml
- ci/mynewt_targets/ecdsa/syscfg.yml
- ci/mynewt_targets/ecdsa_kw/syscfg.yml
- ci/mynewt_targets/rsa/syscfg.yml
- ci/mynewt_targets/rsa_kw/syscfg.yml
- ci/mynewt_targets/rsa_overwriteonly/syscfg.yml
- ci/mynewt_targets/rsa_rsaoaep/syscfg.yml
- ci/mynewt_targets/rsa_rsaoaep_bootstrap/syscfg.yml
This allows both MCUBoot as root package with Mynewt core as remote and the other way around.
Currently when MCUBoot is added as a repo with Mynewt as root package, `newt` shows warning messages due to the CI targets having an absolute import path (not a pkgpath) and `newt` not being able to find the imported packages. Support for using pkgpaths in `newt` was added today, https://github.com/apache/mynewt-newt/pull/277, and this updates the imports accordingly. I also removed symlink creation because `newt` is able to find the packages by scanning the source tree.
> Use Mynewt pkgpath in imports

- boot/boot_serial/test/pkg.yml
- boot/boot_serial/test/src/boot_test.h
- boot/bootutil/include/bootutil/bootutil.h
- boot/bootutil/src/bootutil_priv.h
- boot/bootutil/test/pkg.yml
These unit tests were failing with build errors such as this:
```
boot/boot_serial/test/src/testcases/boot_serial_img_msg.c:64:26: error: use of undeclared identifier 'FLASH_AREA_IMAGE_PRIMARY'
rc = flash_area_open(FLASH_AREA_IMAGE_PRIMARY, &fap);
^
```
The `FLASH_AREA_IMAGE_{PRIMARY,SECONDARY}` definitions were not visible because `MCUBOOT_MYNEWT` was not getting defined in the boot_serial unit test package.
This commit defines `MCUBOOT_MYNEWT` in the boot_serial unit test package, and adds the necessary include to pull in the PRIMARY / SECONDARY definitions.
> Mynewt: Fix boot_serial unit tests

- scripts/imgtool/main.py
If imgtool is used for signing with encryption
it will disallow using public RSA key for
signing.
Signed-off-by: Chris Bittner <chris.bittner@nordicsemi.no>
> imgtool: Discard public RSA if set for signing

- boot/zephyr/CMakeLists.txt
This fixes #399 where dts.overlay was not being appended.
The build scripts were erroneously modifying the shadowed non-cache
variable instead of the cache variable.
Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>
> cmake: Fix bug where dts.overlay was not being appended

- boot/zephyr/Kconfig
It is no longer necessary to override TEXT_SECTION_OFFSET when BOARD_HAS_NRF5_BOOTLOADER. The nrf52840_pca10059 board no longer overrides TEXT_SECTION_OFFSET but sets the correct FLASH_LOAD_OFFSET instead, automatically.
Please @nvlsianpu, have a look.
> boot: zephyr: do not override TEXT_SECTION_OFFSET

- boot/bootutil/include/bootutil/sha256.h
Adding multiple crypto backends will grow quadraticly. This change will
ensure that the growth will be linear and generate less complexity.
Signed-off-by: Sigvart Hovland <sigvart.m@gmail.com>
> boot: bootutil: Simplify check for crypto backends to reduce complexity

- samples/zephyr/hello-world/CMakeLists.txt
set_conf is not used anymore.
This functionality was replaced.
Signed-off-by: Chris Bittner <chris.bittner@nordicsemi.no>
> zephyr: cmake: Remove obsolete code

- boot/zephyr/Kconfig
- boot/zephyr/prj.conf
At present setting up Zephyr logging subsystem is performed in a non-standard and somehow confusing way. Rather than defining a log module and a corresponding log level the MCUBoot uses  BOOT_HAVE_LOGGING Kconfig option.
The standard method to configure logging in Zephyr looks as follows:
- enable log subsystem by selecting `LOG` Kconfig option.
- select module log level by modifying `MCUBOOT_LOG_LEVEL`
The current MCUBoot method:
- enable `BOOT_HAVE_LOGGING` Kconfig option (the option selects `LOG`).
- select module log level by modifying `MCUBOOT_LOG_LEVEL`
Presumably the design comes from the time when Zephyr used two different log subsystems and user might have had a problem selecting the proper one. A dedicated BOOT_HAVE_LOGGING would simplify it. This is no longer necessary. …
> zephyr: remove BOOT_HAVE_LOGGING Kconfig option

- scripts/imgtool/image.py
- scripts/imgtool/main.py
This patch aims to add the ability to specify and add dependency TLVs to MCUBoot. Due to the security critical nature of this feature, having dependency TLVs mean that the TLV Info header and these TLVs become part of the protected area.
> imgtool: Add support for dependency description

- boot/zephyr/boards/nrf51_pca10028.conf
- boot/zephyr/boards/nrf52840_pca10059.conf
- boot/zephyr/include/mcuboot_config/mcuboot_config.h
The removal of CONFIG_BOOT_HAVE_LOGGING in 15aa6ef ("zephyr: remove BOOT_HAVE_LOGGING Kconfig option") missed some uses. In particular, the one in mcuboot_config.h that converts Kconfig options to MCUboot's platform-agnostic configuration macros.
This broke logging even when the relevant Kconfig options were on.
Fix things up by using CONFIG_LOG instead.
Tested logging works again on nrf52840_pca10056. Build tested nrf51_pca10056 to make sure it still fits. The nrf52840_pca10059 build overflows flash by 0.16%, but that was a problem before 15aa6ef.
@nvlsianpu I think we should fix the nrf52840_pca10059 build break in a separate patch if it's OK with you. This PR is just to fix the logging regression.
> zephyr: fix logging

- boot/zephyr/boards/nrf52840_pca10059.conf
I can get the board enumerating as a CDC-ACM device when plugged into my system with this patch. Without it, it overflows flash with the toolchain Nordic is currently recommending.
CC: @lemrey
> zephyr: fix build for nrf52840_pca10059

- boot/bootutil/include/bootutil/sha256.h
The change
boot: bootutil: Simplify check for crypto backends to reduce complexity
Adding multiple crypto backends will grow quadraticly. This change will
ensure that the growth will be linear and generate less complexity.
unfortunately is not legal C.  It can be fixed by eliminating the
intermediate macro, so that the `defined` keywords are within the `#if`.
> boot: bootutil: Change conditional to valid C

- ci/mynewt_targets/ecdsa/target.yml
- ci/mynewt_targets/ecdsa_kw/target.yml
- ci/mynewt_targets/rsa/target.yml
- ci/mynewt_targets/rsa_kw/target.yml
- ci/mynewt_targets/rsa_overwriteonly/target.yml
- ci/mynewt_targets/rsa_rsaoaep/target.yml
- ci/mynewt_targets/rsa_rsaoaep_bootstrap/target.yml
This allows the CI targets to be built if MCUBoot is a dependency of other repos as well as current local package only build support.
> Add pkgpath to Mynewt key_files

- boot/zephyr/Kconfig
Add button 1 as default serial detect pin for nrf9160_pca10090
Signed-off-by: Andreas Vibeto <andreas.vibeto@nordicsemi.no>
> boot: serial recovery: Add pca10090 default detect pin

- boot/zephyr/serial_adapter.c
Follow the device name changes in Zephyr.
Signed-off-by: Filip Kubicz <filip.kubicz@nordicsemi.no>
> boot: zephyr: Update USB CDC ACM device name

- boot/zephyr/main.c
USB should be disabled before jumping to the application image if any usb func is enabled to support using either `MCUBOOT_SERIAL` plus `BOOT_SERIAL_CDC_ACM`  or DFU mode with `BOOT_WAIT_FOR_USB_DFU`, or any future usb functionality which could be involved in MCUboot. 
Actually, this fix can't fix the issue #477 totally because `usb_disable()` is not implemented in STM32 SoCs. But this one is also necessary for fixing the issue. 
fix #477
Signed-off-by: Jun Li <jun.r.li@intel.com>
> bugfix: disable usb for all usb funcs before booting

- scripts/imgtool/image.py
- scripts/imgtool/keys/ecdsa.py
- scripts/imgtool/keys/rsa.py
- scripts/imgtool/main.py
`imgtool verify -k <some-key.(pub|sec)> <img-file>`
Allow imgtool to validate that an image has a valid sha256sum and that it was signed by the supplied key.
This implements #486
> Add new verify command

- boot/bootutil/include/bootutil/bootutil.h
- boot/bootutil/src/bootutil_misc.c
- boot/bootutil/src/bootutil_priv.h
- boot/bootutil/src/loader.c
- docs/design.md
- sim/mcuboot-sys/src/c.rs
- sim/src/image.rs
This fixes #480.
When mcuboot rewrites image trailers during a swap, some information is lost.  If a reset occurs before the swap completes, mcuboot may not be able to determine which swap type to resume upon startup.  Specifically, if a "revert" swap gets interupted, mcuboot will perform an extraneous swap on the subsequent boot.  See https://github.com/JuulLabs-OSS/mcuboot/issues/480 for details.
**NOTE:** A different PR (#482) adds unit tests which test this fix.
This PR adds an additional field to the image trailer: `swap-type`.  The new trailer structure is illustrated below:
```
0                   1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
~ …
```
> Fix double swap on interrupted revert

- scripts/requirements.txt
Since Ed25519 curve primitives are available since cryptography package
version 2.6 need to bump its version.
> requirements.txt: bump cryptography Py package version

- .travis.yml
- docs/design.md
- scripts/imgtool/main.py
This just adds the extra parameter for the password which was missing in the ed25519 key generation. `cryptography` and `openssl` can already correctly handle the generation of ed25519 encrypted keys.
> Allow imgtool to generated encrypted ed25519 keys

- boot/bootutil/include/bootutil/sha256.h
mbedTLS made sha256 functions that do not return errors deprecated. This updates to use the new functions avoiding the extra functions calls, and breakage when the deprecated calls are effectively removed.
> Update mbedTLS sha256 usage to avoid deprecation

- boot/zephyr/main.c
Above header was moved to another path.
Which align to zephyr running master after https://github.com/zephyrproject-rtos/zephyr/commit/68c389c1f82aa2c6fedb0d077de31d86cd36bce2
> zephyr: fix include of system_timer.h

- boot/bootutil/src/loader.c
There is a bug in split_go that never opens the loader image flash
area, but opens the app/split image flash area twice. This prevents
split_image_check from passing and the app from ever loading.
This should take care of https://github.com/JuulLabs-OSS/mcuboot/issues/499
> Fix bug that prevents split images from working.

- boot/mynewt/src/main.c
The Mynewt HASH HW driver can be used to do the sha256 validation in the bootloader instead of relying on mbedTLS/tinycrypt. When enabled it must be initialized before `boot_go` (and `boot_img_validate`) is run, so this does the extra checking and runs initialization when required.
This is related to https://github.com/apache/mynewt-core/pull/1876
> [MYNEWT] Allow initialization of HASH when enabled

- boot/bootutil/src/loader.c
- boot/mynewt/mcuboot_config/include/mcuboot_config/mcuboot_config.h
- boot/zephyr/include/mcuboot_config/mcuboot_config.h
- samples/mcuboot_config/mcuboot_config.template.h
When HW / OS provides an always enabled watchdog, this macro can optionally be implemented to avoid resets which are expected to occur under normal conditions when swapping very large images or
running on slower devices.
> Add watchdog feeding macro

- .travis.yml
- NOTICE
- boot/bootutil/include/bootutil/enc_key.h
- boot/bootutil/include/bootutil/image.h
- boot/bootutil/src/bootutil_misc.c
- boot/bootutil/src/bootutil_priv.h
- boot/bootutil/src/encrypted.c
- boot/bootutil/src/image_validate.c
- boot/bootutil/src/loader.c
- boot/zephyr/flash_map_extended.c
- boot/zephyr/include/mcuboot_config/mcuboot_config.h
- boot/zephyr/include/sysflash/sysflash.h
- boot/zephyr/include/target.h
- docs/PORTING.md
- docs/design.md
- docs/imgtool.md
- docs/readme-zephyr.md
- samples/mcuboot_config/mcuboot_config.template.h
- sim/mcuboot-sys/csupport/run.c
- sim/src/image.rs
This change replaces the slot 0/1 terminology with primary/secondary
slot and replaces FLASH_AREA_IMAGE_0/1 with
FLASH_AREA_IMAGE_PRIMARY/SECONDARY. This naming convention
may be more understandable, fits better to MCUs with multiple images
and it is an architecture agnostic alternative as well.
Signed-off-by: David Vincze <david.vincze@arm.com>
> Introduce multi-image boot

- docs/design.md
> docs: fix typos in design.md

- samples/zephyr/Makefile
- samples/zephyr/README.md
Zephyr builds use 'cmake' which can generate either makefiles, or use
the Ninja build tools.  There are several significant advantages to
using Ninja as the build tool:
- It is significantly faster.  Ninja reads a directory and stats the
files in it once.  Make often stats a given directory thousands of
times, many for files that don't even exist.
- It has better output.  Ninja collects commands together with their
error output.  When doing multi-cpu builds, Ninja prints a status
indicator, and only prints fully verbose commands when that command
fails.  Instead of having to try an piece together a given command
with its errors, they will always be together.
- Make's support of multiple CPUs is a crude hack.  Make forks off
multiple processes to use multiple CPUs.  These processes don't …
> Use Ninja instead of Makefiles for Zephyr

- boot/bootutil/include/bootutil/image.h
- scripts/imgtool/image.py
This struct currently relies on padding being done by the C compiler.
Although this is generally done the same across targets, this isn't
required, and it is better to make any padding explicit.  This also
makes it clear that there is extra space in this structure that can be
used for another purpose.
The python imgtool is also fixed to match.  It was using a 32-bit int,
which only worked in the little endian case.
> image: use explitic padding on dependency version

- sim/Cargo.lock
- sim/Cargo.toml
- sim/src/depends.rs
- sim/src/image.rs
- sim/src/lib.rs
- sim/src/tlv.rs
- sim/tests/core.rs
This adds some changes that support testing dependencies within the simulator. Currently, there is a simple test case for incorrect dependencies, but it is disabled because the mcuboot code hangs in this configuration.
> Sim tests for dependencies

- boot/mynewt/mcuboot_config/include/mcuboot_config/mcuboot_config.h
- boot/mynewt/mcuboot_config/syscfg.yml
For Mynewt, if a watchdog driver is available, it is always used and feed during a swap operation. Since the swap operation is able to resist resets, the watchdog can stay disabled to preserve some flash space (watchdog driver), with the side-effect that a swap might take longer because of having to resume interrupted operations.
> Add Mynewt option to enable the watchdog

- sim/src/image.rs
There are three methods that verify multiple images that essentially
manually implement the `all` and `any` methods of `Iterator`.  It makes
it difficult to understand what these do, as there is an early return of
true or false, with various negations of the check.
Replace these with calls directly to `any` or `all` so that it is
clearer what each function is doing.  The generated code should be the
same.
> sim: Simplify verification methods

- scripts/mcubin.bt
- sim/mcuboot-sys/src/area.rs
- sim/src/image.rs
- sim/src/lib.rs
- sim/tests/core.rs
Add a `debug_dump()` method to `Images` to allow the images to be
written to a file.  The dependency test will call this if the
environment variable MCUBOOT_DEBUG_DUMP is set.
In order to make these debug dumps more useful, add a simple partition
table to the beginning of the image (where MCUboot would reside on
target).  This has a simple header, and then entries for each partition,
using the partition ids used within the simulator.  This allows the
image to be more easily used by external tools.
As an example, `scripts/mcubin.bt` is a binary template for the [010
Editor](https://www.sweetscape.com/010editor/), allowing it to decode
and show the details of images from MCUboot.
> sim: Add debugging ptable to image dumps

- scripts/assemble.py
This accounts for changes in the Zephyr build which include:
1) Flash areas are prefixed with `DT_`
2) The generated DTS was renamed to generated_dts_board_unfixed.h
3) The build tree has an extra "zephyr" dir.
Fixes #408
> Fix assemble.py tool for compatibility

- scripts/imgtool/image.py
- scripts/imgtool/main.py
Allow the user to set the load_addr field of the header.
This could be useful in multi image situations to help
deduce the image number of an update without having to
look at the swap info.
> scripts: allow user to set load_addr

- boot/bootutil/src/bootutil_misc.c
Fix for several compile errors that occur with BOOTUTIL_LOG_LEVEL set to BOOTUTIL_LOG_LEVEL_DEBUG.
> Fix build errors that occur when log level is BOOTUTIL_LOG_LEVEL_DEBUG 

- boot/bootutil/src/loader.c
- docs/design.md
Since a copy/erase during a swap can result in some number of sectors erased and copied, which is not necessarily equal to 1, update design document and bootloader function naming to reflect this fact, by using the postfix "_region" instead of "_sector" in those cases.
This fixes #541
> Use better naming for swap copy/erase functions

- boot/bootutil/src/bootutil_misc.c
These were caught by GCC printf-like macro attribute warnings.
(The relevant types are all uint32_t, but %lx wants a long unsigned.)
> bootutil_misc: fix printf types in log macros

- scripts/imgtool/__init__.py
- scripts/imgtool/main.py
- scripts/setup.py
This adds the simplest possible image versioning support to imgtool, supporting the command `imgtool version` and `pip show imgtool`. Also promotes the current version to `1.4.0a3`. No Travis-CI wheel building support added yet.
> Imgtool versioning

- boot/bootutil/include/bootutil/image.h
- boot/bootutil/src/bootutil_priv.h
- boot/bootutil/src/encrypted.c
- boot/bootutil/src/image_validate.c
- boot/bootutil/src/loader.c
- boot/bootutil/src/tlv.c
- boot/zephyr/CMakeLists.txt
- sim/mcuboot-sys/build.rs
This introduces an API which allows for iteration over an image's TLVs without resorting to low-level implementation details. All previous TLV low-level handling was updated to comply with this new interface, and it also makes it easier for external code to handle TLVs.
The API provides two functions:
1) To start a new iterator:
```
int bootutil_tlv_iter_begin(struct image_tlv_iter *it,
const struct image_header *hdr,
const struct flash_area *fap, uint8_t type,
bool prot);
```
2) To iterate over existing TLVs of given type:
```
int bootutil_tlv_iter_next(struct image_tlv_iter *it, uint32_t *off,
uint16_t *len, uint8_t *type);
```
A type of `IMAGE_TLV_ANY` was added to allow for iteration over all TLVs.
Low-level TLV access functions were removed from API, but low-level structs are still …
> Add TLV iterator API

- boot/boot_serial/test/src/testcases/boot_serial_upload_bigger_image.c
- boot/mynewt/flash_map_backend/pkg.yml
The boot_serial test was failing build because it hadn't been updated to use new multi-image flash area nomenclature. This fixes the build.
> Fix Mynewt boot_serial unittest

- boot/bootutil/include/bootutil/image.h
- boot/bootutil/src/image_validate.c
- boot/bootutil/src/loader.c
- boot/bootutil/src/tlv.c
- docs/design.md
- scripts/imgtool/image.py
- sim/src/image.rs
- sim/src/tlv.rs
When using protected TLVs (for dependencies) the image validation was run over header + payload + tlv_info + protected TLVs. As a side-effect it was impossible to update the TLVs without rehashing (+ resigning) an image. This updates the validation routine to skip the tlv_info, so that hashing is run over header + payload + protected TLVs.
Fixes #539.
This is WIP, needs rebase after #549 is merged; `imgtool` and documentation changes in progress.
> New protected TLV format

- boot/bootutil/include/bootutil/bootutil.h
- boot/bootutil/src/bootutil_misc.c
- boot/bootutil/src/bootutil_priv.h
- sim/mcuboot-sys/csupport/run.c
- sim/mcuboot-sys/src/c.rs
Values of type `extern const` generate possibly an extra load (depending on the value), but also make it possible to introduce VLA (variable length arrays) into the code. These changes eliminate two of these consts that really should just be #defines. Instead of the simulator accessing them directly, provide an accessor function to make the constant value available.
> Eliminate a few `extern const` items

- boot/zephyr/Kconfig
To enable multi image support in mcuboot one needs
to set the 'UPDATEABLE_IMAGE_NUMBER' config.
Add this to zephyrs MCUBoot kconfig to allow this.
> kconfig: add option for multi image

- boot/zephyr/Kconfig
- boot/zephyr/serial_adapter.c
zephyr changes the way in which it provide name of
serial device used by serial recover.
see: https://github.com/zephyrproject-rtos/zephyr/pull/18752
This path introduce build time configuration of device name
which is set to exact the same device which was set before.
> zephyr/serial_recovery: fix serial device binding

- scripts/setup.py
Seems like pypi.org is not accepting "None" for email anymore, so this just adds the mailing list in case someone needs to contact the project.
> imgtool: add mailing list email to setup

- scripts/imgtool/image.py
- scripts/imgtool/main.py
Add a new flag `-x` (or `--hex_addr`) which adjusts the memory address where this file has to be written to. This is useful when generating upgrade images that will go to the secondary slot, in cases where the user is not using mcumgr or some other delivery mechanism, and has to manually adjust the addresses using `objcopy`.
PS: this uses internals of the intelhex python module (protected variables) because no existing mechanism to do the adjustment seems to exist.
> imgtool: allow address adjustment in output hex

- scripts/imgtool/__init__.py
- scripts/imgtool/image.py
- scripts/imgtool/main.py
This was not tested in HW; also can wait for after 1.4.0.
> imgtool: add `erased-val` option, add full trailer to HEX files

- boot/mynewt/src/main.c
- boot/mynewt/syscfg.yml
Add a new Mynewt option that allows for overriding the default `hal_system_start` routine; this allows for startup customizations required by some BSPs.
There's also a commit with some example custom code that will be dropped before merge!
> mynewt: allow overriding the startup routine

- boot/boot_serial/test/pkg.yml
- boot/bootutil/pkg.yml
- boot/mynewt/pkg.yml
This patch changes the cflag entry for MCUBOOT_MYNEWT to make it
consistent when using #if or #ifdef.
Signed-off-by: Andy Gross <andy.gross@juul.com>
> mynewt: Make cflags consistent for if or ifdef usage

- boot/bootutil/src/bootutil_misc.c
- boot/bootutil/src/image_rsa.c
- boot/bootutil/src/loader.c
- boot/bootutil/src/tlv.c
- boot/zephyr/Kconfig
- boot/zephyr/include/flash_map_backend/flash_map_backend.h
- ci/sim_run.sh
- docs/encrypted_images.md
- scripts/setup.py
- sim/simflash/src/lib.rs
Ran automated checker for common typos [1]. Most of these changes have
no functional change *except* for `./ci/sim_run.sh` where, previously
the `bootstrap` feature wasn't being selected properly.
I didn't touch anything in the `./ext/` folder as anything in there
should probably be fixed in the upstream repo.
[1] https://github.com/codespell-project/codespell
Signed-off-by: Sam Bristow <sam@bristow.nz>
> Fix up typos

- scripts/imgtool/image.py
Commit 9117fded476768b458253902a7d9c87e3663802a added support for supplying an `--erased-val`, which defaults to 0xff. When padding a header, the checks were still validating against 0, which is the value used for padding by the Zephyr build system. Now when the user passes `--pad-header` this check is skipped (we already know the contents).
> imgtool: fix header padding value check

- docs/encrypted_images.md
- docs/index.md
Add an H1 heading to encrypted_images.md.
Signed-off-by: Ruth Fuchss <ruth.fuchss@nordicsemi.no>
> docs: add missing heading

- ext/nrf/cc310_glue.h
Copy paste bug in cc310 glue layer for nRF where disable does not set
the enable register to 0. Thanks to @solsbarry for pointing this out.
Fixes: #586
Signed-off-by: sigvartmh <sigvart.m@gmail.com>
> Bugfix: nRF Cryptocell not being disabled

- .travis.yml
- boot/bootutil/src/bootutil_misc.c
- boot/bootutil/src/bootutil_priv.h
- boot/bootutil/src/loader.c
- sim/Cargo.toml
- sim/src/image.rs
- sim/src/lib.rs
Some (largely simulator) changes to test the configuration with overwrite-only enabled on devices with large write sizes. The flash API still returns a `uint8_t` for the alignment, so this value will be bogus for devices with 512-byte alignment, but these tests ensure that the value isn't actually used in the overwrite-only case.
There is one change that changes the size of the type where the alignment is stored within the boot code. Changing this would allow a particular platform to define `flash_area_align()` to return a larger type, and not immediately discard the value.
Supporting larger write alignment with swap will be significantly more work, and is not addressed by the PR.
> Test overwrite mode with large-write align devices

- boot/bootutil/src/encrypted.c
Use correct macro for the size of a DH shared secret. The previously used macro had the same size (SHA-256 digest length) but incorrect semantics.
> Fix HKDF input size macro

- sim/src/tlv.rs
Avoid having to declare default values in type instantiation.
> sim: derive Default for TlvGen

- boot/bootutil/src/bootutil_misc.c
- sim/src/tlv.rs
Removes the hard-coded image encryption keys, and updates with keys generated randomly before use. This tests the correct behavior of how ephemeral keys should be used when generating new images.
> sim: add randomly generated image encryption keys

- docs/encrypted_images.md
URL anchors are already generated automatically by the GH markdown processor, but they are not visible. This adds the proper links to the page.
> docs: add URL anchor links to encrypted images md

- boot/zephyr/include/target.h
8accafd5c7e8d19c832574993ffb664f69fa345e has removed `#endif` statement belonging to `#if` unrelated to removed code block, causing compilation error:
```
In file included from /.../mcuboot/boot/zephyr/main.c:26:
/.../mcuboot/boot/zephyr/include/target.h:8: error: unterminated #ifndef
#ifndef H_TARGETS_TARGET_
[35/229] Building C object CMakeFiles/app.dir/.../mcuboot/boot/bootutil/src/image_rsa.c.obj
ninja: build stopped: subcommand failed.
ERROR: command exited with status 1: /usr/bin/cmake --build /.../mcuboot/build
```
Restore it.
> zephyr: restore removed #endif in target.h

- sim/src/image.rs
These were added during development to make sure conditional compilation
was working.  Now, they just cause excess messages to be printed.
Remove them.
> sim: Remove some extraneous print

- boot/zephyr/CMakeLists.txt
- boot/zephyr/dts.overlay
0e3fa72df4849eb42c99efb34b8617046c2e33cb removed device tree overlay that configures Zephyr to link mcuboot at the beginning of the flash, and CMake variable that pointed to it (required for Zephyr). This resulted in mcuboot not being linked at some offset, rendering it unable to boot. Restore overlay and required code.
Without it, Zephyr will use `zephyr,code-partition` configuration from board device tree that usually points to the `slot0_partition`. This behaviour is due to the [CONFIG_USE_CODE_PARTITION](https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_USE_CODE_PARTITION.html) being used in MCUboot's configuration for Zephyr.
Fixes #601.
Signed-off-by: Sergey Koziakov <dya.eshshmai@gmail.com>
> zephyr: restore device tree overlay

- samples/zephyr/run-tests.go
Remove a redundant chip erase from run-tests.go.  The '-e chip' should
tell pyocd to perform a chip erase.  There seem to be some combinations
of daplink and pyocd that if an invalid image is loaded into the device,
it can no longer be flashed by pyocd.  Performing the chip erase as a
separate command easily gets it into this state.  It can be recovered by
using the DAP filesystem to write the image.
> samples: zephyr: Remove redundant extra chip erase

- boot/bootutil/include/bootutil/image.h
- boot/bootutil/src/image_validate.c
- boot/bootutil/src/tlv.c
- sim/src/tlv.rs
Two changes, one for the code, and one for the simulator to make TLVs 16 bits. The format is compatible with the existing TLVs, so it isn't necessary to change imgtool until we want to support a TLV value larger than 8-bits (presumably that can happen with the user-defined TLV support).
> Make TLVs 16 bits

- sim/src/image.rs
- sim/src/tlv.rs
Currently, the tests that appear to be testing for invalid signatures
are actually just testing that images aren't used if the entire TLV
block is missing.  Fix this by being more subtle about our corruptions.  If
there is no signature, corrupt that data being used to generate the
hash.  Otherwise, modify a bit at the end of the signature itself, which
should be detected by the signature checking code.
> sim: Actually test invalid signatures

- sim/src/tlv.rs
For some reason, the ECDSA signature generation code attempted to
adjust the length of the ASN.1 of the actual signature.  It wasn't doing
this right, and was creating ASN.1 expecting many more entries than were
present.  The half-run parser in the tinycrypt ECDSA signature check
didn't care about this, but mbed TLS's signature check does care.
The intent of the padding was to be able to predict the size of the TLV
before writing it out.  Keep the padding for now, even though there is
no simple way of knowing how many pad bytes to remove (just removing
them will remove extra if there is a zero in the last byte of the
signature.
A future change will eliminate the padding, as it should no longer be
needed.
> sim: Fix ecdsa padding

- boot/bootutil/src/bootutil_misc.c
- boot/bootutil/src/bootutil_priv.h
- boot/bootutil/src/swap_misc.c
- boot/bootutil/src/swap_move.c
Fix an issue where an upgrade could fail to execute.
This happened randomly in the "perm_with_fails" test in the simulator; for it to happen the first reset had to occur just after writing the metadata to mark the start of a new upgrade, but before any swap happened; if followed by a new reset happening at a point where the metadata was erased and rewritten, it would result in an upgrade failure. The images would still be valid though although in their original slots.
The fix stores the detected boot status source in the state. When metadata was found in the primary slot we assume a swap has already started (even though no sector swap has happened) and avoid
erasing/rewriting it.
> Fix random upgrade failure using swap move 

- boot/bootutil/include/bootutil/bootutil_log.h
- boot/mynewt/mcuboot_config/include/mcuboot_config/mcuboot_logging.h
- boot/zephyr/include/mcuboot_config/mcuboot_logging.h
- sim/mcuboot-sys/csupport/mcuboot_config/mcuboot_logging.h
- sim/mcuboot-sys/csupport/run.c
- sim/mcuboot-sys/src/api.rs
* Adds a new level (BOOT_LOG_SIM) to be used only for messages that are interesting while debugging bootutil in the simulator. This should be used for extra verbose prints.
* Also added fflushs after fprints to guarantee that messages are printed even when assertions are raised.
* For abstraction completeness, add "do nothing" definitions of _LOG_SIM to the other ports.
* Make DEBUG the default level when building the simulator (one can still lower verbosity using any other value for RUST_LOG).
> Simulator logging improvements

- boot/bootutil/src/loader.c
- boot/bootutil/src/swap_move.c
- boot/bootutil/src/swap_scratch.c
There are a few error messages printed by the boot code.  In a normal
platform, these are real errors, and really should print a message.
However, in the simulator, we intentionally create these scenarios, and
these errors only serve to distract from the rest of the test output.
Conditionalize the error prints based on whether we are running in the
simulator.
> boot: Clean up errors during sim test

- scripts/imgtool/main.py
Apply a few improvements to the type parameter in the keygen command. Currently finding out the key types requires passing an invalid value to display what values are available. Instead add them the help page, so it shows an output like below:
```
-t, --type type     One of: rsa-2048, rsa-3072, ecdsa-p256, ecdsa-p224,
ed25519  [required]
```
When no type is given in the CLI, ask for it:
```
$ ./imgtool.py keygen -k privkey.pem
Type (rsa-2048, rsa-3072, ecdsa-p256, ecdsa-p224, ed25519):
```
> imgtool: Add helpers for type in keygen command

- boot/bootutil/src/image_validate.c
- docs/ecdsa.md
- docs/index.md
Start with some documentation on ECDSA signatures, and the problems with
the current padding approach.  Present a plan to support correctly
formatted ECDSA signatures, and how to handle the transition both in the
C code, as well as the tooling that signs images.
> docs: Write up some docs about ecdsa padding

- scripts/imgtool.nix
This allows us to create temporary, reproducible development environment using [Nix](https://nixos.org) for working with `imgtool.py`.
> scripts: Add `imgtool.nix`

- boot/bootutil/src/bootutil_priv.h
- boot/bootutil/src/swap_move.c
- boot/zephyr/Kconfig
- sim/mcuboot-sys/build.rs
*From commit messages*:
* boot: Add free space check for swap without scratch
Add a missing test which ensures that there is enough free sectors to perform an upgrade when using the move strategy; this basically checks that the sectors used by the trailer don't overlap the last sector required for a move up operation.
* sim: enable saving encrypted TLV for ECIES
This changes the simulator to save the encryption TLV itself instead of the unecrypted AES-128 key when doing the ECIES encryption test, to add proper test coverage of this configuration option.
* boot: zephyr: remove [EXPERIMENTAL] from config option
Swap without scratch has been tested enough and no obvious bugs (or "show stopper) bugs seem to exist; so remove [EXPERIMENTAL] and make it "stable".
> Extra swap without scratch check; better sim coverage; remove Zephyr [EXPERIMENTAL] option

- boot/zephyr/CMakeLists.txt
To be more robust in the placement of MCUBoot directory,
use the ZEPHYR_BASE env variable to locate
nrfxlib directory.
> cmake: use zephyr base in relative path

- sim/mcuboot-sys/src/api.rs
- sim/mcuboot-sys/src/area.rs
- sim/mcuboot-sys/src/c.rs
- sim/mcuboot-sys/src/lib.rs
- sim/simflash/src/lib.rs
- sim/simflash/src/pdump.rs
- sim/src/caps.rs
- sim/src/depends.rs
- sim/src/image.rs
- sim/src/lib.rs
- sim/src/main.rs
- sim/src/testlog.rs
- sim/src/tlv.rs
- sim/tests/core.rs
Add an apache SPDX header and explicit license lines.  The date ranges
of the license lines is derived from the git history.  Having these
explicitly present will make contributions from other parties easier, as
they will simply be able to add their own copyright line, rather than
having to describe that it only covers modifications.
> sim: Add explicit copyright and licenses to the sim

- .travis.yml
- boot/bootutil/include/bootutil/caps.h
- boot/bootutil/src/caps.c
- boot/bootutil/src/loader.c
- boot/zephyr/Kconfig
- boot/zephyr/include/mcuboot_config/mcuboot_config.h
- docs/design.md
- sim/Cargo.toml
- sim/mcuboot-sys/Cargo.toml
- sim/mcuboot-sys/build.rs
- sim/src/caps.rs
- sim/src/depends.rs
- sim/src/image.rs
- sim/src/lib.rs
- sim/tests/core.rs
Depends on 'MCUBOOT_OVERWRITE_ONLY' option since swap info is not protected
by signature
Proposal to issue #224 
> add option for rollback protection

- boot/boot_serial/src/boot_serial.c
- boot/zephyr/flash_map_extended.c
- boot/zephyr/main.c
- boot/zephyr/serial_adapter.c
Zephyr will soon no longer add the drivers subdirectory of the include
hierarchy to the search path, so references to driver headers must
include the drivers/ prefix.
Signed-off-by: Peter Bigot <peter.bigot@nordicsemi.no>
> zephyr: fix driver include paths

- boot/zephyr/Kconfig
According to our CI:
Redundant 'source "$(ZEPHYR_BASE)/Kconfig.zephyr" in
'boot/zephyr/Kconfig'. Just do 'source "Kconfig.zephyr"'
instead. The $srctree environment variable already points
to the Zephyr root, and all 'source's are relative to it.
Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>
> boot: zephyr: Fix Kconfig inclusion

- boot/zephyr/main.c
GPIO_DIR_IN has been replaced by GPIO_INPUT, GPIO_PUD_PULL_UP by
GPIO_PULL_UP, and gpio_pin_read() by gpio_pin_get_raw().  Update the
code to use the preferred API if it available.  This avoids
deprecation warnings in the build.
Signed-off-by: Peter Bigot <peter.bigot@nordicsemi.no>
> boot: zephyr: move to non-deprecated GPIO flags

- boot/bootutil/pkg.yml
- boot/zephyr/CMakeLists.txt
- boot/zephyr/Kconfig
- ext/fiat/src/curve25519.c
- ext/tinycrypt-sha512/lib/include/tinycrypt/sha512.h
- ext/tinycrypt-sha512/lib/pkg.yml
- ext/tinycrypt-sha512/lib/source/sha512.c
- sim/mcuboot-sys/build.rs
Add option to build ed25519 with Tinycrypt.
This depends on https://github.com/intel/tinycrypt/pull/42 being accepted and update of local copy.
UPDATE: sha-512 was added separately while upstream PR is pending acceptance.
> Add Tinycrypt based SHA-512 for ED25519

- boot/zephyr/main.c
- boot/zephyr/serial_adapter.c
Since zephyrproject-rtos/zephyr#20375
Need to enable USB by the application.
substitute to #643
> zephyr: enable usb by the application

- scripts/imgtool/image.py
The `--erased-val` (or `-R`) option was doing conversion of base 10, so the only value that was acceptable was 0. Although not passing this option would result in the default `0xff` being used, this fixes the issue by refactoring a new function that does the heuristic conversion based on the prefix base.
> imgtool: fix passing --erased-val with 0xff value

- boot/zephyr/Kconfig
Prior to this the kconfig would fail because of invalid value for an int
> kconfig: add default pin for serial recovery for nrf53

- sim/Cargo.lock
- sim/Cargo.toml
- sim/mcuboot-sys/Cargo.toml
- sim/simflash/Cargo.toml
Updates a few sim dependencies, reducing the amount of crates required for a build; also gets rid of cases of more than one version required for some crates. Results in depending on 76 crates instead of 89 before the PR.
> sim: update dependencies

- docs/Gemfile.lock
https://nvd.nist.gov/vuln/detail/CVE-2020-7595
> docs: update nokogiri to fix CVE-2020-7595

- repository.yml
A recently added `newt` feature allows it to only clone selected git submodules: https://github.com/apache/mynewt-newt/pull/377. This changes the MCUBoot repository to remove submodules from the cloning process, because they are not used by Mynewt.
> mynewt: allow newt to bypass submodule cloning

- NOTICE
- boot/bootutil/include/bootutil/image.h
- boot/bootutil/include/bootutil/security_cnt.h
- boot/bootutil/src/image_validate.c
- boot/bootutil/src/loader.c
- boot/zephyr/Kconfig
- boot/zephyr/include/mcuboot_config/mcuboot_config.h
- docs/design.md
- scripts/imgtool/image.py
- scripts/imgtool/main.py
- Add new security counter to protected TLV area
- Add new command line option for imgtool to specify the value of this counter
- Modify the simulator to prevent the tests from failing (temporary solution)
- Make the security counter verification part of the image validation process
- Introduce security counter interface and also provide a SW only weak implementation (currently does absolutely nothing)
Related GitHub issue: #597 
Please provide feedback and ideas how it could be combined with a SW only solution (if we need it at all). Currently the verification of a new image's security counter value is mandatory.
Please see my additional comments below.
> introduce HW rollback protection

- boot/zephyr/Kconfig
- boot/zephyr/boards/nrf52840_pca10056_big.overlay
- boot/zephyr/main.c
- boot/zephyr/prj.conf
- boot/zephyr/sample.yaml
- boot/zephyr/serial_adapter.c
- boot/zephyr/usb_cdc_acm_log_recovery.conf
Modyfied serial_adapter so log are alowed when using USB
CDC ACM serial port emulation.
As log needs to work asynchronously in its own thread,
mcuboot need to give some time for execution this thread using
k_sleep().
Added configuration for nrf52840_pca10056 which shows how
to enable looging along with USB - among other, thread log
processing is required.
build command (form zephyr-project root directory)
west build -d build/mcuboot/nrf52840_pca10056 -b nrf52840_pca10056
./bootloader/mcuboot/boot/zephyr/
-- -DDTC_OVERLAY_FILE=./boards/nrf52840_pca10056_big.overlay
-DOVERLAY_CONFIG=./boards/nrf52840_pca10056_usb_cdc_log.conf
> zephyr: allow recovery over usb cdc-acm with logs enabled

- boot/bootutil/src/loader.c
Might get past the loop without going in at least once.
Signed-off-by: Erik Johnson <erik.johnson@nimbelink.com>
> loader: Fixed warning about uninitialized rc variable

- boot/cypress/README.md
Updating the URL for git repository in README file to reflect merge
of PSoC62 into mcuboot master.
> Update instructions to point to correct git URL

- .gitmodules
- boot/cypress/MCUBootApp/MCUBootApp.mk
- boot/cypress/MCUBootApp/README.md
- boot/cypress/MCUBootApp/config/mcuboot_crypto_acc_config.h
This PR is based on https://github.com/JuulLabs-OSS/mcuboot/pull/653
- Added hardware acceleration of MbedTLS crypto functions.
- Added one additional dependency https://github.com/cypresssemiconductorco/cy-mbedtls-acceleration.git
- Signature and hash verification performed approximately 4 times faster 
- readme updated
> Cypress: Hardware acceleration of cryptography implementation for 062 device

- scripts/imgtool/image.py
- scripts/imgtool/main.py
Add imgtool command line option for confirming (setting image_ok = 0x01) in a padded image.
Fixes: #664
Signed-off-by: Henrik Brix Andersen <hebad@vestas.com>
> imgtool: add option for confirming a padded image

- boot/boot_serial/src/boot_serial.c
_NOTE: Umbrella PR, for Zephyr, that gathers required changes to other project is here:
zephyrproject-rtos/zephyr#21825_ 
***Important: merge right after the umbrella PR***
Changes needed due to overwrite of Zephyr fork of Tinycbor with
mynewt-core version.
Signed-off-by: Dominik Ermel dominik.ermel@nordicsemi.no
> zephyr: Enabling Zephyr/mynewt-core version of tinycbor

- scripts/imgtool/keys/ecdsa.py
The sign method may add 1 or 2 '\0' character padding to ensure the signature TLV is 72 bytes. But the verification function didn't strip the paddings before invoking crypto libraries. It causes failure when the signature is 70 or 71 bytes.
> fix #675 ECDSA verification fail when padding is added

- scripts/imgtool/keys/ecdsa.py
- scripts/imgtool/main.py
- sim/src/tlv.rs
Continuing from #621, make non padded ECDSA signatures the default. The `--pad-sig` flag is added to imgtool to be able to make images for old versions of MCUboot.
> Remove default padding from ECDSA signatures

- boot/zephyr/CMakeLists.txt
- boot/zephyr/Kconfig
- boot/zephyr/arm_cleanup.c
- boot/zephyr/include/arm_cleanup.h
- boot/zephyr/main.c
This patch is needed as MCUBoot should be able to chain-load any
application, not only these built using zephyr.
Introduced cleanup on ARM core control register.
Might be required as for instance the application assumes
that it starts with thread mode configured as by default, not
according to zephyr-rtos configuration.
MCUBoot disables interrupt before application chain-load used
basepr register. This Patch introduce additional celenup on
NVIC register.
> zephyr: cleanup of ARM core before application boot

- boot/bootutil/include/bootutil/image.h
Replace BUILD_ASSERT_MSG() with BUILD_ASSERT() in order for the following PR to proceed:
zephyrproject-rtos/zephyr#23437
> bootutil: Replace BUILD_ASSERT_MSG() with BUILD_ASSERT()

- boot/bootutil/include/bootutil/image.h
This reverts commit 6d417c9c84f347e275146cf8b11c02373a1eb831.
The patch was merged accidentally too early.
> Revert "bootutil: Replace BUILD_ASSERT_MSG() with BUILD_ASSERT()"

- boot/zephyr/main.c
Zephyr timeout API is changing and will use opaque value (k_timeout_t)
instead of raw values. K_MSEC is used to convert raw milliseconds value
to k_timeout_t.
This change is backward compatible so can be merged independently.
Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>
> zephyr: Wrap sleep value with K_MSEC

- boot/zephyr/CMakeLists.txt
DEPENDS ON:
https://github.com/zephyrproject-rtos/tinycbor/pull/13
It is no longer needed to add TINYCBOR to list of interface libraries.
> zephyr: TinyCBOR has been removed from interface libraries

- boot/bootutil/include/bootutil/boot_record.h
- boot/bootutil/include/bootutil/boot_status.h
- boot/bootutil/include/bootutil/image.h
- boot/bootutil/src/boot_record.c
- boot/bootutil/src/loader.c
- boot/zephyr/Kconfig
- boot/zephyr/include/mcuboot_config/mcuboot_config.h
- scripts/imgtool.nix
- scripts/imgtool/__init__.py
- scripts/imgtool/boot_record.py
- scripts/imgtool/image.py
- scripts/imgtool/main.py
- scripts/requirements.txt
- scripts/setup.py
This patch enables measured boot by implementing an interface for mcuboot to share various attributes/measurement of the authenticated images (boot data) with the runtime software (sharing arbitrary data is also possible). As a result it also creates the prerequisites for an attestation service
(runtime) by preserving this data from the boot stage.
The imgtool was updated to optionally add a new type of TLV to the image manifest with all the attributes and measurements that are known at build time. Before adding this data to the TLV area it is encoded in CBOR format. Later mcuboot will read and update this binary data and add it to a shared memory area between the bootloader and runtime software.
The list of shared measurements is based on the recommendations of Arm's Platform Security …
> Share boot data with runtime software

- boot/boot_serial/src/boot_serial.c
k_sleep() requires explicit conversion of the unit since it takes an
opaque type starting with:
https://github.com/zephyrproject-rtos/zephyr/pull/23382
> zephyr: boot_serial: Use K_MSEC() with k_sleep

- scripts/assemble.py
Switch to using the devicetree_legacy_unfixed.h header for extracting flash partition information.
Zephyr has switched to using a new gen_defines.py script and a new set of macros/defines for devicetree code generation for all nodes except flash partitions, which are still in the legacy format.
Signed-off-by: Henrik Brix Andersen <henrik@brixandersen.dk>
> scripts: assemble.py: switch to using devicetree_legacy_unfixed.h

- boot/zephyr/arm_cleanup.c
Use <arch/arm/aarch32/cortex_m/cmsis.h> include instead of <zephyr.h> to
get access to Cortex-M CMSIS API. zephyr.h provides kernel API, does not
guarantee access to CPU internals.
Fixes: #699 "Building MCUBoot for Zephyr fails on multiple ARM boards"
> zephyr: arm_cleanup.c: use <.../cortex_m/cmsis.h>

- boot/bootutil/include/bootutil/image.h
- boot/bootutil/include/bootutil/sign_key.h
- boot/bootutil/src/image_validate.c
- boot/cypress/MCUBootApp/keys.c
- boot/zephyr/Kconfig
- boot/zephyr/include/mcuboot_config/mcuboot_config.h
- boot/zephyr/keys.c
- scripts/imgtool/image.py
- scripts/imgtool/main.py
Enable the public key(s) (used for image authentication) to be removed from MCUboot and be appended to the image instead. In this case the key or its hash must be provisioned to the device and MCUboot must be able to retrieve the key-hash from the hardware to compare it with the calculated hash of the public key from the image manifest. After validating the key it can be used for image authentication. This way MCUboot can be independent from the public key(s) (they are not embedded in it).
This feature was already available in TF-M's MCUboot fork, this PR covers its integration with the original MCUboot code.
> Add HW key support for image validation

- scripts/imgtool/__init__.py
- scripts/imgtool/image.py
- scripts/imgtool/main.py
Set the RAM_LOAD flag in the image header when a load address was passed
to the imgtool script, indicating that the image should be loaded into
RAM and run from there.
> imgtool: Set RAM_LOAD flag in header when needed

- scripts/imgtool/__init__.py
Set imgtool version to 1.6.0alpha3 after merging [#712](https://github.com/JuulLabs-OSS/mcuboot/pull/712).
> imgtool: release 1.6.0alpha3

- boot/bootutil/include/bootutil/image.h
This macro is part of the C11 standard.  Remove the use of a specialized macro
just for Zephyr, and use the standard macro for all platforms.  This reduces
dependencies on specific versions of Zephyr
> Use _Static_assert on all platforms

- boot/bootutil/include/bootutil/bench.h
- boot/bootutil/include/bootutil/bootutil.h
- boot/bootutil/include/bootutil/bootutil_log.h
- boot/bootutil/include/bootutil/bootutil_test.h
- boot/bootutil/include/bootutil/enc_key.h
- boot/bootutil/include/bootutil/ignore.h
- boot/bootutil/include/bootutil/image.h
- boot/bootutil/include/bootutil/sha256.h
- boot/bootutil/include/bootutil/sign_key.h
- boot/bootutil/src/bootutil_misc.c
- boot/bootutil/src/bootutil_priv.h
- boot/bootutil/src/caps.c
- boot/bootutil/src/encrypted.c
- boot/bootutil/src/image_ec.c
- boot/bootutil/src/image_ec256.c
- boot/bootutil/src/image_ed25519.c
- boot/bootutil/src/image_rsa.c
- boot/bootutil/src/image_validate.c
- boot/bootutil/src/loader.c
- boot/bootutil/src/swap_misc.c
- boot/bootutil/src/swap_move.c
- boot/bootutil/src/swap_priv.h
- boot/bootutil/src/swap_scratch.c
- boot/bootutil/src/tlv.c
- docs/design.md
I'd like to start a discussion as to how we can more clearly format copyright and licenses in our source files.  This is modeled after what many modern projects are moving to, explicit copyrights, and an SPDX line that identifies the license.
The problem with the existing format is that there are no copyright statements from any party. This means some additional parties will have to add awkward lines like: "Modifications are copyright...".
> Update license headers more appropriate for non-Apache project

- ci/imgtool_install.sh
Add missing `packaging` to allow version comparison.
> Fix imgtool publishing missing python package

- boot/zephyr/Kconfig
Updated boards reference names.
> zephyr/Kconfig: reference missing new Nordic boards keywords

- README.md
- sim/README.rst
Fix the simulator docs to include the `--recursive` argument needed for mbed TLS to now get all of its code. Also, make a link in the top-level docs to the simulator to increase awareness.
> Update the simulator docs slightly

- boot/boot_serial/src/boot_serial.c
The variable `dec_off` can possibly be uninitialized in this function.
As long as the serial protocol used is formed correctly, the
initialization will always happen.  Place an initialization upon
function entry to protect against a case where a malformed protocol is
able to provoke this variable being used before being initialized.
> boot_serial: Initialize possibly initialized variable

- boot/boot_serial/src/serial_recovery.cddl
- boot/boot_serial/src/serial_recovery_cbor.c
- boot/boot_serial/src/serial_recovery_cbor.h
Was 3, but mcumgr sometimes sends 2 ("off" + "data", "len" is not needed
when "off" != 0). Reduce to 1 to avoid the problem, since the code
has other checks to catch this.
Signed-off-by: Øyvind Rønningstad <oyvind.ronningstad@nordicsemi.no>
> serial_recovery: Reduce minimum number of members in packet

- boot/bootutil/src/loader.c
Tiny patch before release 1.6.0.
Fix uninitialized variable warning that may occur when
compiler optimization is enabled (especially for size).
> boot: Fix uninitialized variable warning

- boot/zephyr/CMakeLists.txt
Using find_package to locate Zephyr.
Old behavior was to use $ENV{ZEPHYR_BASE} for inclusion of boiler plate
code.
Whenever an automatic run of CMake happend by the build system / IDE
then it was required that ZEPHYR_BASE was defined.
Using ZEPHYR_BASE only to locate the Zephyr package allows CMake to
cache the base variable and thus allowing subsequent invocation even
if ZEPHYR_BASE is not set in the environment.
It also removes the risk of strange build results if a user switchs
between different Zephyr based project folders and forgetting to reset
ZEPHYR_BASE before running ninja / make.
Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>
> cmake: use find_package to locate Zephyr

- boot/zephyr/Kconfig
A few mcuboot option were outside of mcuboot-specific
menu.
This patch moves them into mcuboot menu.
> zephyr/Kconfig: cleanup mcuboot menuconfig

- boot/boot_serial/src/boot_serial.c
- boot/zephyr/arm_cleanup.c
- boot/zephyr/main.c
- boot/zephyr/serial_adapter.c
Use C99 types in favor of the Zephyr defined types.
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
> zephyr: Convert from Zephyr to C99 types

- boot/zephyr/sample.yaml
dtc overlay should be transfered via DTC_OVERLAY_FILE,
not by DTC_OVERLAY.
> zephyr: fix zephyr testcase extra_tags

- boot/zephyr/CMakeLists.txt
Fixes mistake in CMakeLits.txt that prevented successful compilation
of single image with serial recovery enabled.
> boot/zephyr: Fix single image compilation with serial recovery

- boot/zephyr/CMakeLists.txt
- samples/zephyr/Makefile
- samples/zephyr/hello-world/CMakeLists.txt
- scripts/assemble.py
This commit is a followup to the usage of `find_package(Zephyr ...)`.
The zephyr/hello-world sample has been updated to use find_package.
The assemble.py script now takes ZEPHYR_BASE as an argument, so it may
be used from CMakeLists.txt files when ZEPHYR_BASE is not set in
environment, and thus the Makefile sample has been adjusted accordingly.
Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>
> cmake: scripts: now using ZEPHYR_BASE as local variable

- boot/zephyr/Kconfig
- boot/zephyr/main.c
If SW_VECTOR_RELAY is enabled, the bootloader sets
the pointer to address, where interrupts will be
forwarded.
Signed-off-by: Rafał Kuźnia <rafal.kuznia@nordicsemi.no>
> boot/zephyr: add option to relocate interrupts to application

- docs/encrypted_images.md
As title, fix the typo for imgtool keygen command
> Fix the typo for imgtool keygen command

- boot/bootutil/src/loader.c
- sim/src/image.rs
- sim/tests/core.rs
This fixes an issue where an image might be erased, but a trailer left behind. It can happen if the image in the secondary slot did not pass validation, in which case the whole slot is erased. If during the erase operation, a reset occurs, parts of the slot might have been erased while some have not. The concerning part is the trailer because it might disable a new image from being loaded through mcumgr; so just get rid of the trailer here, if the header is erased.
> Fix erase of possible trailer leftover after reset

- scripts/assemble.py
In scripts/assemble.py:
Use the <board_name>.dts.pre.tmp file in <build-dir>/zephyr to find the
board name.
This allows the build directory path to be set freely and not enforcing
directory structures.
> zephyr: Find board name from dts.pre.tmp file

- scripts/assemble.py
Make `-z` flag optional, so if it is not provided rely on the ZEPHYR_BASE environemnt variable to find the Zephyr tree.
> assemble: Allow use of ZEPHYR_BASE environment var

- boot/bootutil/src/swap_move.c
- scripts/imgtool/main.py
- sim/src/image.rs
- sim/src/lib.rs
When using swap in move mode, the current compatibility test only allows for same size and layout between slots. This results in one sector that can never be used in the secondary slot, which corresponds to the first move up operation in the primary slot. This relaxes and checking a bit, so both same size slots and a primary with one extra sector are valid.
> Allow larger primary slot in swap-move

- boot/zephyr/serial_adapter.c
Align the code to the new UART callback signature, see:
https://github.com/zephyrproject-rtos/zephyr/pull/26426
> zephyr: serial: Align with new callback signature

- ext/nrf/cc310_glue.h
Added traslation for cryptocell peripheral for use with chip
without TrustZone.
Signed-off-by: Piotr Ciura <piotr.ciura@nordicsemi.no>
> boot: Support for nrf52840 with ecc keys and cryptocell

- scripts/imgtool/main.py
As discussed in
https://github.com/zephyrproject-rtos/zephyr/pull/28026, when
generating confirmed images, it makes sense to pad them.
> imgtool: --confirm implies --pad

- scripts/imgtool/image.py
- scripts/imgtool/main.py
In an effort to create a script to do firmware based on an URL, I could
not easily retrieve the image digest. `newtmgr` needs the hash when
marking a image for testing.
> imgtool: Print image digest during verify

- boot/zephyr/main.c
On Cortex M7, and NXP i.MX RT 1020 specifically, MCUBOOT will fail after loading a new image if the instruction cache is enabled. This works for us and might help others, but I need help to figure out where to do this, and what ifdefs to use to turn it on. Also, I'm not sure if the ARM_MPU_Disable thing is really needed.
> Turn off cache for Cortex M7 before rebooting

- boot/zephyr/CMakeLists.txt
Change fixes build issue that occurs if CONF_FILE contains multiple
file paths instead of single file path.
Signed-off-by: Marek Pieta <Marek.Pieta@nordicsemi.no>
> boot: zephyr: Fix build issue for multiple conf files

- boot/bootutil/src/bootutil_priv.h
- boot/bootutil/src/image_validate.c
- boot/bootutil/src/loader.c
- boot/bootutil/src/swap_misc.c
- boot/bootutil/src/swap_scratch.c
- boot/bootutil/src/tlv.c
- samples/mcuboot_config/mcuboot_config.template.h
- scripts/imgtool/design.md
- scripts/imgtool/main.py
This PR introduces the ram-loading mode in addition to the other
upgrade modes (swap strategies, overwrite-only, direct-XIP). When
ram-loading is enabled with the MCUBOOT_RAM_LOADING option, mcuboot
selects the newest valid image based on the image version numbers from
the image header, thereafter the selected image loaded to the RAM and
executed from there. Load address is extracted from the image header.
Therefore the images must be linked to the RAM memory region.
The ram-loading mode is very similar to the direct-XIP mode, main
difference is to load the newest image to the RAM beforehand the
authentication and execution. Similar to direct-XIP mode either
of the primary and the secondary slots can hold the active image.
Ram-loading can be useful in case of a bit more powerful SoC, …
> RAM loading upgrade mode

- go.mod
- samples/zephyr/.gitignore
- samples/zephyr/mcutests/mcutests.go
- samples/zephyr/run-tests.go
- samples/zephyr/test-compile.go
Some changes to the test build and run process so that it is possible to build the tests and run them on separate machines (or separate containers). Without arguments, `run-tests.go` works as it did before, but now, the `tests-compile.go` can be used to build and assemble the results into a zip file, which can be transported to another system, and used with the new `-prebuilt` argument to `run-tests.go` to use the prebuilt tests rather than building them.
> Separate Zephyr sample build

- scripts/imgtool/image.py
When Image.create() is called without the 'custom_tlvs' argument, it
gets its default value (None). It must be checked before performing
any operations on/with it.
> imgtool: Fix 'custom_tlvs' argument handling

- scripts/imgtool/image.py
Imgtool does not take into account value of `confirm` flag, when signing .hex images. Because of that user can't get signed hex file for swap upgrade type `permanent`.
This PR adds `confirm` flag analysis while signing hex file format.
Signed-off-by: Roman Okhrimenko <roman.okhrimenko@cypress.com>
> imgtool: Add possibility to set confirm flag for hex files as well

- boot/cypress/MCUBootApp/main.c
- boot/cypress/Makefile
- boot/cypress/cy_flash_pal/flash_qspi/flash_qspi.c
- boot/cypress/cy_flash_pal/flash_qspi/flash_qspi.h
- boot/cypress/platforms/retarget_io_pdl/cy_retarget_io_pdl.c
- improved code in MCUBootApp
- added possibility to enter deep sleep mode after mcuboot app execution
- deinitialize QSPI block after app execution
- add endless loop in main function
- minor refactoring
Signed-off-by: dmiv <dmiv@cypress.com>
Signed-off-by: Roman Okhrimenko <roman.okhrimenko@cypress.com>
Signed-off-by: Taras Boretskyy <taras.boretskyy@cypress.com>
> Cypress: Add entering deep sleep, deinit qspi periphs in MCUBootApp, code improvements

- .github/workflows/mynewt.yaml
- .github/workflows/sim.yaml
These duplicate the existing travis builds using the github workflow. Since most of the work is done by support scripts, this is mostly about running these scripts.
> Create github workflow files for CI

- .github/workflows/mynewt.yaml
- .github/workflows/sim.yaml
Remove option to run on push because it is triggering two runs for each test for all PRs.
> workflows: run on PR only

- boot/cypress/MCUBootApp/main.c
- boot/cypress/platforms/retarget_io_pdl/cy_retarget_io_pdl.c
- boot/cypress/platforms/retarget_io_pdl/cy_retarget_io_pdl.h
Entering deep sleep on CM0 without valid application on CM4 caused pyocd error while programming. This fix disables entering deep sleep mode on CM0 if no valid applications found for boot. Waiting for uart complete tx reworked. Code refactoring
Signed-off-by: Roman Okhrimenko <roman.okhrimenko@cypress.com>
> cypress: Disable entering deep sleep if no boot/upgrade images found in MCUBootApp

- docs/PORTING.md
Remove a footnote that is not generating a proper link and add an inline link to the mbed TLS referece for platform.h. This also fixes a warning when running through recommonmark==0.6.0 because it is unable to parse the old syntax.
> doc: fix link to external page in PORTING

- boot/zephyr/main.c
to avoid causing stack overflow in the image being booted.
> boot: zephyr: reset SPLIM registers before boot

- boot/bootutil/include/bootutil/bootutil.h
- boot/bootutil/include/bootutil/fault_injection_hardening.h
- boot/bootutil/include/bootutil/fault_injection_hardening_delay_rng.h
- boot/bootutil/include/bootutil/image.h
- boot/bootutil/include/bootutil/security_cnt.h
- boot/bootutil/src/bootutil_misc.c
- boot/bootutil/src/bootutil_priv.h
- boot/bootutil/src/fault_injection_hardening.c
- boot/bootutil/src/fault_injection_hardening_delay_rng_mbedtls.c
- boot/bootutil/src/image_rsa.c
- boot/bootutil/src/image_validate.c
- boot/bootutil/src/loader.c
- boot/cypress/MCUBootApp/cy_security_cnt.c
- boot/cypress/MCUBootApp/main.c
- boot/mynewt/src/main.c
- boot/zephyr/CMakeLists.txt
- boot/zephyr/Kconfig
- boot/zephyr/include/mcuboot_config/mcuboot_config.h
- boot/zephyr/main.c
- boot/zephyr/single_loader.c
- sim/mcuboot-sys/build.rs
Adding SW counter measures against fault injection attacks in HW. These attacks could be clock or power glitching, EM pulse, laser beam, temperature change.  The goal of the attacker is is to execute unauthenticated code on the device.  The expectation of the attacker that due to these injected faults the CPU will change its normal behaviour and in this way create a benefit for the attacker to bypass secure boot and image authentication. The potential differences in the CPU behaviour could be one or more instruction skip, modifying register content, corrupting memory read, corrupting instruction decoding, resetting bits in program status register. 
The SW counter measure are not guaranteeing 100% protection against all HW attack but make harder to bypass image authentication. The SW …
> SW counter measures against HW level fault injection

- .github/workflows/sim.yaml
- boot/bootutil/include/bootutil/caps.h
- boot/bootutil/src/caps.c
- boot/bootutil/src/loader.c
- sim/mcuboot-sys/build.rs
- sim/mcuboot-sys/csupport/run.c
- sim/mcuboot-sys/csupport/storage/flash_map.h
- sim/mcuboot-sys/src/api.rs
- sim/src/caps.rs
- sim/src/image.rs
- sim/tests/core.rs
This should fix bootstrap in swap-move along with other fixes.
@d3zd3z After some issues I've found working on this PR, I think we should just remove the `MCUBOOT_OVERWRITE_ONLY_FAST` option and make it the default behavior when doing overwrite-only, what do you think?
Fixes #706, #738
> sim: add bootstrap test

- boot/zephyr/prj.conf
Some Zephyr boards enable HW stack protection by default, which
propagates in mcuboot build. Bootloader works fine with that option, but
the problem arises when we jump to application code. HW stack protection
catches application code during early init, which results in
"unresponsive" application.
Disable HW stack protection, so it doesn't make any harm for application
code.
Signed-off-by: Marcin Niestroj <m.niestroj@grinn-global.com>
> boot: zephyr: Disable HW stack protection

- boot/bootutil/include/bootutil/fault_injection_hardening.h
- boot/bootutil/src/fault_injection_hardening_delay_rng_mbedtls.c
Remove an unnecessary include and create conditionally
the MCUBOOT_FIH_PROFILE_OFF define to avoid redefinition
warnings.
> Clean-up fault injection hardening header

- boot/bootutil/src/fault_injection_hardening_delay_rng_mbedtls.c
- boot/cypress/MCUBootApp/main.c
- boot/mynewt/src/main.c
- boot/zephyr/main.c
- boot/zephyr/single_loader.c
Direct inclusion of "bootutil/fault_injection_hardening_delay_rng.h"
causes linking collision as this header belongs to `FIH_ENABLE_DELAY`
mode.
This header is already included by "bootutil/fault_injection_hardening.h"
appropriately.
fixes #831
> boot: remove fih delay rng inclusion

- boot/zephyr/single_loader.c
The comment on why first parameter to bootutil_img_validate is allowed
to be NULL, in boot_image_validation of single_loader.c, has been
rewritten.
> boot/zephyr: Improve badly written comment

- .travis.yml
This PR disables (almost) all of the travis test jobs. 
Please note that the 'imgtool' test is not disabled, as in case of an empty matrix the CI seem to report failure.
> Temporarily disable travis test jobs

- boot/bootutil/src/swap_move.c
When the image in the primary slot is padded, the boot source is considered the primary slot; this results in skipping the typical initialization of the trailer, which ends up bricking the device. As it is fine to always initialize the trailer in the primary slot when starting a new upgrade the extra check was removed.
Should fix #829 when done.
> bootutil: fix swap-move brick with padded image in primary slot

- boot/bootutil/src/bootutil_misc.c
- boot/bootutil/src/bootutil_priv.h
- boot/bootutil/src/swap_misc.c
- boot/bootutil/src/swap_move.c
- boot/bootutil/src/swap_scratch.c
- boot/zephyr/include/flash_map_backend/flash_map_backend.h
- docs/PORTING.md
- sim/mcuboot-sys/csupport/run.c
- sim/mcuboot-sys/csupport/storage/flash_map.h
Removes the current `flash_area_read_is_empty` which lacked a bit of clarity in its naming and error handling, as well as requiring an extra API in the flash map, and switches to using an internal function `bootutil_buffer_is_erased`.
Code that was previously using `flash_area_read_is_empty` must now be updated to do a `flash_area_read` followed by a call to `bootutil_buffer_is_erased` with the read buffer.
The proposal was previously discussed here: https://github.com/zephyrproject-rtos/zephyr/pull/28519
> boot: bootutil: drop flash_area_read_is_empty

- boot/zephyr/Kconfig
- boot/zephyr/include/mcuboot_config/mcuboot_config.h
- boot/zephyr/main.c
copy of https://github.com/zephyrproject-rtos/mcuboot/pull/34
This fixes soft-bricks that we have seen as a result
of the bootloader being interrupted by the watchdog.
Signed-off-by: Emil Hammarstrom <emil.hammarstrom@assaabloy.com>
> boot/zephyr: add nrfx watchdog kick during boot region copy

- boot/zephyr/flash_map_extended.c
This function was drooped from MCUBoot's porting API.
> zephyr: remove flash_area_read_is_empty()

- docs/design.md
Some design.md content is causing build errors when they are included in a .rst based documentation tree in Sphinx.
Adjust the format to make it work in both systems.
> clean up multi-image documentation

- boot/boot_serial/src/boot_serial.c
- 1.
The last data packet might be non aligned to multiple of
the flash write-block-size. This cause that the `image upload`
mcumgr command mighty fail if the device flash driver doesn't
support one-byte write-block-size.
This patch complements the last write operation to aligned chunk
so it meet the requirements.
- 2.
.Added check for ensure than received data chunk doesn't
cross expected image size..
> boot/boot_serial: allow unaligned last chunk

- boot/bootutil/src/loader.c
For some configurations, eg CONFIG_BOOT_DIRECT_XIP=y, fih_rc might never be initialized; initialize and fix warning.
> bootutil: fix unitialized variable warning

- boot/zephyr/flash_map_extended.c
The function was made week so zephyr-rtos implementation
will be used if available.
> boot/zephyr: make flash_area_erased_val() weak

- boot/zephyr/Kconfig
- boot/zephyr/arm_cleanup.c
- boot/zephyr/include/arm_cleanup.h
- boot/zephyr/main.c
- boot/zephyr/prj.conf
Zephyr has introduced an option to perform the cleanup
of ARM core HW registers during early boot, when the
firmware is chain-loaded by MCUboot. Therefore, MCUboot
does not need to perform the same cleanup before jumping
to the application image. The patch relies on the fact
that building MCUboot with Zephyr implies loading also
a Zephyr-based application firmware. If this is not the
case, the application developer needs to enable the
MCUBOOT_CLEANUP_ARM_CODE Kconfig option manually, in the
project configuration.
Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>
> zephyr: Kconfig: change default for MCUBOOT_CLEANUP_ARM_CODE

- boot/bootutil/src/swap_move.c
A previous fix for allowing padded images in the primary slot, ended up causing an issue that would fail to upgrade under the right circumstances. The issue was caused when the following set of steps happened after an upgrade was detected:
1) trailer is erased on the primary slot
2) status is written to the primary slot
3) trailer is erased on the secondary slot
4) reset
1) trailer is erased on the primary slot
2) status partially written or not written to primary slot (no magic)
3) reset
This would result in images stored in the same slots they were initially, aka no upgrade, which would fail the simulator test for upgraded images.
The previous padded images fix was reverted and the status source was upgraded to also check that the secondary slot has a valid magic in it, so that there's …
> Fix upgrade issue in swap-move

- boot/zephyr/main.c
After modifying the CONTROL register, ISB function should be
used to ensure the effect of the change applies to
subsequent code.
Due to the simple nature of the Cortex-M3, Cortex-M4, Cortex-M0+,
Cortex-M0, and Cortex-M1 pipeline,
omission of the ISB instruction does not cause any problem.
But might cause problem on a more advanced core.
> zephyr: added ISB after cortex control was set

- boot/zephyr/arm_cleanup.c
This function must be excluded from build when
core doesn't have MPU.
> zephyr/arm_cleanup: exclude z_arm_clear_arm_mpu_config() when no MPU

- boot/bootutil/include/bootutil/image.h
This patch adds macro definitions for proprietary vendor TLV types.  The
intent of this patch is to set aside a certain range of TLVs for use by
various vendors.
Signed-off-by: Andy Gross <andy.gross@juul.com>
> boot: Add vendor defined TLV range and macros

- .mbedignore
- boot/mbed/app_enc_keys.c
- boot/mbed/include/flash_map_backend/flash_map_backend.h
- boot/mbed/include/flash_map_backend/secondary_bd.h
- boot/mbed/include/mcuboot_config/mcuboot_assert.h
- boot/mbed/include/mcuboot_config/mcuboot_config.h
- boot/mbed/include/mcuboot_config/mcuboot_logging.h
- boot/mbed/include/os/os_malloc.h
- boot/mbed/include/sysflash/sysflash.h
- boot/mbed/mbed_lib.json
- boot/mbed/mcuboot_main.cpp
- boot/mbed/src/flash_map_backend.cpp
- docs/index.md
- docs/readme-mbed.md
- mbed-os.lib
This PR introduces support for Mbed-OS with mcuboot. You can find demos of [a bootloader here](https://github.com/AGlass0fMilk/mbed-mcuboot-demo) and [a bootable application](https://github.com/AGlass0fMilk/mbed-mcuboot-blinky) here.
> Port mcuboot to Mbed-OS

- mbed-os.lib
This commit reverts the addition of an `mbed-os.lib` file introduced with the Mbed-OS port (d82afbfaa839f2d4b86b883fc570f4955a9bec0e). 
Mbed-OS build tools use .lib files to pull in additional dependencies automatically with a single command. The intended usage of mcuboot with mbed-os is to clone mcuboot _next to_ mbed-os, rather than mbed-os inside mcuboot.
Signed-off-by: George Beckstein <becksteing@embeddedplanet.com>
> Remove mbed-os library file

- .mbedignore
- README.md
- boot/mbed/include/mcuboot_config/mcuboot_config.h
This PR introduces a few patch changes to the Mbed-OS port including:
- Add a link to the Mbed-OS readme from the respository's main README.
- Temporarily disable building with the TinyCrypt backend for Mbed-OS builds
An explanation of the TinyCrypt change:
TinyCrypt uses a modified version of micro-ecc. Another version of micro-ecc is also used by the Mbed Cordio BLE stack. When building mcuboot for a target with BLE enabled, this causes multiple-defined symbol errors during linking. Due to the nature of Mbed's current build system, it is difficult to fix this.
Mbed will soon release a more flexible cmake-based build system that will make it possible to exclude these TinyCrypt files from an application build that may also link Cordio BLE sources.
Until then, this commit temporarily …
> Mbed-OS patches - temporarily disable TinyCrypt backend

- samples/zephyr/test-compile.go
This reference to the old Juul URL got missed.  Fix it as well.
> samples: zephyr: Fix URL in test compilation

- .travis.yml
- ci/fih-tests_install.sh
- ci/fih-tests_run.sh
- ci/fih_test_docker/Dockerfile
- ci/fih_test_docker/build.sh
- ci/fih_test_docker/damage_image.py
- ci/fih_test_docker/execute_test.sh
- ci/fih_test_docker/fi_make_manifest.sh
- ci/fih_test_docker/fi_tester_gdb.sh
- ci/fih_test_docker/generate_test_report.py
- ci/fih_test_docker/run_fi_test.sh
- docs/design.md
The tests investigate the behaviour of MCUBoot in case of instruction skip. The idea behind the test implementation is to create a set of scripts that execute the following:
- Run in MCUBoot in QEMU with a corrupted image.
- Attach a debugger to QEMU, and stop execution of MCUBoot.
- Modify the PC register by adding a predefined value to it
- Continue the execution
- Check whether the image booted successfully.
- As it would be unrealistic to test with skipping all the instructions, the test is limited to the instructions that are hardened in MCUboot. The FIH_* macros define symbols in the code at the beginning and the end of the hardening code, and the address of those symbols are extracted by the test scripts.
To Achieve this, the pull requests consists of the following additions to the …
> Add Travis-CI tests for testing SW counter measures against HW level fault injection

- ci/imgtool_install.sh
Should fix the current fail trying to build a bdist_wheel.
> ci: add wheel dependency to imgtool publishing

- boot/zephyr/Kconfig
BOOT_DIRECT_XIP_REVER enable code which shall only be enabled
while BOOT_DIRECT_XIP=y.
> zephyr/Kconfig: allow xip-revert only for xip-mode

- boot/bootutil/src/bootutil_priv.h
If RAM_LOAD is defined then the return value of memcpy() is
always compared against its first parameter. By definition
memcpy() returns with its first paramter (destination) so
the not equal check is always false. The fix replaces this
runtime check with a comma operator assigning 0 to the
variable at build time, as a result compiler can be done
dead code elimination much better.
Signed-off-by: Tamas Ban <tamas.ban@arm.com>
Change-Id: I8d0d6e68a931661fa19d395556beb20470d74fb1
> boot: Fix LOAD_IMAGE_DATA macro

- README.md
- docs/release-notes.md
- repository.yml
- scripts/imgtool/__init__.py
Update version fields for 1.7.0 release.
Added compatibility note for zephyr-rtos.
> Preps for 1.7.0 release

- boot/mynewt/src/main.c
mynewt code calls hal_bsp_init() at start of bootloader.
This may initialize some resources (timer/uart/dma).
mynewt has now hal_bsp_deinit() function that should be called
before application is executed.
This new function allows to stop resources that were started.
This can stop cputimer which was started including enabled
interrupt. This timer interrupt was very likely to fire
for STM devices that has 16 bits timer used, when mcuboot
did not started LSE and application wanted to.
Starting LSE oscillator takes so much time in some cases
that timer interrupt will execute MCU from mcuboot vector
after RAM was already cleared by startup code and that
would lead to crash loop.
Blocking interrupts before starting application would
also help but leaving peripherals in reset state
seems …
> boot/mynewt: De-initialize peripherals before calling app

- boot/bootutil/include/bootutil/crypto/aes_ctr.h
- ext/tinycrypt/lib/include/tinycrypt/ctr_mode.h
- ext/tinycrypt/lib/source/ctr_mode.c
- ext/tinycrypt/tests/test_ctr_mode.c
Applies a few fixes/improvements after the last refactoring of the crypto; this should make the final binary somewhat smaller and about the same speed.
* Add an offset parameter to mode ctr so it can be properly used as a streaming cipher, like required by the flash encryption algorithm.
* Avoid memset'ing a buffer that does not hold a secret; it contains the encryption of the counter.
> Crypto fixes after last refactoring

- boot/zephyr/prj.conf
Addition of cbprintf capability in zephyr
https://github.com/zephyrproject-rtos/zephyr/pull/29876
cause flash footprint rise by ~4 KB. Selecting
CBPRINTF_NANO=y mitigates the footprint rise.
> zephyr: use minimal CBPRINTF implementation

- boot/zephyr/prj.conf
Enables LOG_MINIMAL in the default build.
Ref: NCSDK-7206
Signed-off-by: Stephen Stauts <stephen.stauts@nordicsemi.no>
> boot: zephyr: Default to LOG_MINIMAL

- boot/mbed/include/mcuboot_config/mcuboot_logging.h
This PR prevents the following build error:
```
./mcuboot/boot/mbed/include/mcuboot_config/mcuboot_logging.h:65:30: error: 'IGNORE' was not declared in this scope
65 | #define MCUBOOT_LOG_ERR(...) IGNORE(__VA_ARGS__)
```
This build error occurs when the bootloader is configured with Mbed's logging library, mbed-trace, disabled or when a logging level other than "MCUBOOT_LOG_LEVEL_DEBUG" is used. Since "bootutil/ignore.h" was not included previously, the "IGNORE(...)" macro was undefined in this scope.
Signed-off-by: George Beckstein <becksteing@embeddedplanet.com>
> Fix Mbed OS logging port when trace is disabled.

- boot/mbed/src/flash_map_backend.cpp
- docs/PORTING.md
The internal functions of mcuboot are not consistent in opening/closing flash areas and sometimes nested calls happen to `flash_area_open` and `flash_area_close`. With the previous implementation, a nested call to `flash_area_close` would deinitialize the underlying `BlockDevice`. This could cause subsequent flash operations on an "open" flash area to fail.
This PR adds a simple open counter for each flash area and ensures the underlying `BlockDevice` is initialized and deinitialized appropriately. The `BlockDevice` is only initialized when transitioning from an open count of 0 to 1. The `BlockDevice` is only deinitialized when the open count falls to 0.
Signed-off-by: George Beckstein <becksteing@embeddedplanet.com>
> Add reference counting to Mbed OS flash backend

- boot/bootutil/CMakeLists.txt
In order to allow other projects to include the bootutil files more
easily. Allows renaming and moving of bootutil files without breaking
external projects' file lists (if they include this cmake file instead
of directly listing the files they use). Prevents an issue where
moving/renaming bootutil files breaks the FIH CI test.
Signed-off-by: Raef Coles <raef.coles@arm.com>
> bootutil: Add cmake build file

- scripts/imgtool/__init__.py
- scripts/imgtool/image.py
- scripts/imgtool/main.py
The commit adds support for IMAGE_F_ROM_FIXED flag that allows setting
information on image base address into image_header.
> imgtool: Add support for setting fixed ROM address into image header

- boot/mbed/mbed_lib.json
- boot/mbed/src/flash_map_backend.cpp
- boot/mbed/src/secondary_bd.cpp
This commit introduces changes that allow users to build for other non-swap type update methods (overwrite only, swap using move, direct xip, or RAM loading). Changes include:
- Adding configuration options relating to XIP
- Updating the Mbed flash map backend to be compatible with XIP updates
- Add default secondary_bd in internal flash for XIP on Mbed OS.
Signed-off-by: George Beckstein <becksteing@embeddedplanet.com>
> Enable support for building mcuboot for Mbed with direct-xip

- ci/fih_test_docker/Dockerfile
To a version which uses the new bootutil cmake, allowing the bootutil
files to be moved/renamed without breaking the FIH test.
Signed-off-by: Raef Coles <raef.coles@arm.com>
> ci: Update tf-m version in FIH test

- boot/zephyr/arm_cleanup.c
- boot/zephyr/include/arm_cleanup.h
- boot/zephyr/main.c
Cleanup the NXP MPU configuration before chain-loading the application.
Signed-off-by: Henrik Brix Andersen <hebad@vestas.com>
> boot: zephyr: cleanup NXP MPU configuration before boot

- .travis.yml
- ci/fih-tests_install.sh
- ci/fih-tests_run.sh
- ci/fih_test_docker/docker-build/Dockerfile
- ci/fih_test_docker/docker-build/build.sh
- ci/fih_test_docker/execute_test.sh
Moved Dockerimage and build script to a separate directory. This should be used to build a new docker image and this image should be pushed to Docker hub. Source repos were removed from the image and only tools remain. The Travis config file was updated to pull and cache the used docker image instead of rebuilding all the time. The running script now clones trusted-firmware-m at the right place (sibiling to mcuboot clone) and runs the docker images mapping the VM's directory to the internal container.
> Update FIH test docker flow on Travis

- boot/zephyr/main.c
Fix compilation with CONFIG_LOG_MINIMAL enabled by disabling the custom log handling code.
Fixes e75e33d9817fefb8ec37b5979f93e3dd41e81b8f
Signed-off-by: Henrik Brix Andersen <hebad@vestas.com>
> boot: zephyr: fix compilation with CONFIG_LOG_MINIMAL=y

- boot/bootutil/include/bootutil/boot_record.h
- boot/bootutil/src/boot_record.c
Modify the function boot_add_data_to_shared_area from static to
global as it is used in the user interface boot_save_shared_data.
Signed-off-by: Sherry Zhang <sherry.zhang2@arm.com>
> bootutil: Modify boot_add_data_to_shared_area function scope

- ci/sim_run.sh
- ptest/src/main.rs
A few testing changes to help benchmark test runs to figure out where time is being spent. The first patch splits the build and run parts of the tests, while adding a `time` command to show the amount of time taken by the test. The second patch enhances ptest to check for an environment variable `PTEST_LOG_ALL`, which will cause the results of all tests to be output, instead of just failures. These changes helped determine that #913 was not worth pursuing.
> Allow logging from all test, not just failures.

- ci/fih-tests_run.sh
To fix a regression caused by f68473814f17a299ff8766bc3cf86e014552f479,
where an older TF-M version was used that didn't support the bootutil
cmake.
Signed-off-by: Raef Coles <raef.coles@arm.com>
> ci: Update TF-M version

- ci/check-signed-off-by.sh
Addresses issues when running signed-off-by checks on the Zephyr fork due to GH rebases done on UX rewriting the commit with the primary email instead of whatever email was used originally.
> ci: relax signed-off-by checks on forks

- boot/zephyr/main.c
- boot/zephyr/prj.conf
CONFIG_LOG_MINIMAL was replaced by CONFIG_LOG_MODE_MINIMAL since
https://github.com/zephyrproject-rtos/zephyr/pull/31404 PR was
merged.
CONFIG_LOG_MINIMAL is still emitted as legacy property, but
cat't be assigned so prj.conf was fixed.
> boot:zephyr: CONFIG_LOG_MINIMAL converted to CONFIG_LOG_MODE_MINIMAL

- boot/cypress/BlinkyApp/libs.mk
- boot/cypress/BlinkyApp/main.c
- boot/cypress/MCUBootApp/libs.mk
- boot/cypress/MCUBootApp/main.c
- boot/cypress/libs/watchdog/watchdog.c
- boot/cypress/libs/watchdog/watchdog.h
Add watchdog timer to MCUBootApp plus BlinkyApp to implement additional way of boot/upgrade image operation confirmation.
> cypress: Add support for watchdog timer update in boot image

- scripts/imgtool/image.py
Fixes padding hex images when encrypting. The issues stems from binaries using `bytes` and IntelHex returning `array` where `bytes` cannot be appended to, so use `.extend()` instead.
Found while testing #939
> imgtool: fix encrypting hex images

- boot/zephyr/main.c
The commit changes banner message to indicate that bootloader has been
built for Direct-XIP mode.
It also removes, in Direct-XIP compiled code, information on jumping
into first slot: that information is not always correct for Direct-XIP
and other messages correctly point slot that will be used.
> boot/zephyr: Fix Direct-XIP boot messages

- boot/bootutil/include/bootutil/image.h
- boot/bootutil/src/loader.c
The series of commits adds IMAGE_F_ROM_FIXED flag, which has already been defined in imgtool and used in mcumgr, but has been missed in mcuboot, and code that uses the flag to skip application images that have been placed in incorrect slot.
> Adding IMAGE_F_ROM_FIXED flag

- sim/Cargo.lock
- sim/simflash/Cargo.toml
- sim/simflash/src/lib.rs
The thiserror crate is getting more of a community following than failure (about half of the lifetime downloads, recent downloads are about double, though), and has already reached a 1.0 stable.
This PR makes minor changes to the code to use this new crate.
> Migrate error handling in sim to "thiserror"

- boot/zephyr/main.c
The commit fixes definition and usage of ZEPHYR_LOG_MODE_MINIMAL
to prevent compilation warnings on possibly non-portable code.
> boot: zephyr: Fix compilation warnings with ZEPHYR_LOG_MODE_MINIMAL

- boot/zephyr/Kconfig
- boot/zephyr/main.c
Signed-off-by: Josh Gao <josh@jmgao.dev>
> zephyr: add an option to use GPIO to enable USB DFU.

- boot/zephyr/main.c
Removed configuration of gpio pin using flags which were
removed for zephyr-project long ago. Also old method of read
the pin value was removed.
No sense to keep that as nowadays MCUboot is also not compatible
with zephyr version which supports these flags and methods.
> boot/zephyr: cleanup GPIO pin setup

- boot/bootutil/src/bootutil_misc.c
- boot/bootutil/src/bootutil_priv.h
- boot/bootutil/src/bootutil_public.c
The commit fixes alignment issue in boot_write_trailer, that would
occur in case when input buffer length would be greater than
alignment parameter of flash.
Possible scenario:
```
let align = 4
let inlen = 7
```
ccording to the previous logic `align < inlen => align = inlen` (line 316-318). which means that
```
320: memset(&buf[inlen], erased_val, align - inlen);
```
does not write any erase value to fill in buffer because `align - inlen == 0`. and line
```
322: rc = flash_area_write(fap, off, buf, align);
```
writes unaligned buffer due to `align == inlen == 7`
Test PR for zephyr: https://github.com/zephyrproject-rtos/zephyr/pull/33292
> bootutil: Fix boot_write_trailer write alignment

- docs/index.md
Update the main webpage to contain links to the wiki page docs on the
project charter, and the membership page.
> docs: Add links to wikipage on project

- boot/zephyr/CMakeLists.txt
When CONFIG_BOOT_SIGNATURE_KEY_FILE is left empty, the cmake find command gets
called with a wrong number of arguments. This patch skips the search for the
signature key file within config files in that case.
Signed-off-by: Nico Lastzka <Nico.Lastzka@ATSonline.de>
> cmake: fix evaluation with empty signature key file

- boot/boot_serial/src/boot_serial.c
Use the new header used for `sys_reboot` on Zephyr.
Ref. https://github.com/zephyrproject-rtos/zephyr/pull/34599
> boot: boot_serial: use new Zephyr reboot header

- boot/zephyr/boards/mimxrt1060_evk.conf
- boot/zephyr/boards/mimxrt1064_evk.conf
The mimxrt1060_evk and mimxrt1064_evk boards have large slots so we need
to increase CONFIG_BOOT_MAX_IMG_SECTORS from the default.
Signed-off-by: Maureen Helm <maureen.helm@nxp.com>
> boot: zephyr: Configure mimxrt106x_evk boards

- boot/mbed/mbed_lib.json
Removing the header size configuration which apparently does not do anything.
What was the reason behind this parameter? @AGlass0fMilk
> Mbed: Remove unused header size config

- boot/mbed/app_enc_keys.c
- boot/mbed/include/mcuboot_config/mcuboot_config.h
- boot/mbed/mbed_lib.json
This commit introduces changes to allow the Mbed-OS port to disable use of signature verification. Previously this was not possible even though it is a valid mcuboot configuration.
Signed-off-by: George Beckstein <george.beckstein@gmail.com>
> Enable no signature verification configuration for Mbed-OS.

- boot/bootutil/include/bootutil/bootutil_public.h
- boot/bootutil/src/bootutil_public.c
bootutil_public.c: add two user APIs
Add boot_set_pending_multi_image() and
boot_set_confirmed_multi_image() APIs so that the user can set the
image with given index as pending, confirmed.
Signed-off-by: Sherry Zhang <sherry.zhang2@arm.com>
Change-Id: Ifca04d396b38c6c64581703794071f6b42e9dfbf
> bootutil_public.c: modify boot_set_pending() and boot_set_confirmed()

- .github/workflows/imgtool.yaml
- .github/workflows/mynewt.yaml
- .github/workflows/sim.yaml
- README.md
- ci/imgtool_install.sh
- ci/imgtool_run.sh
- docs/index.md
- docs/readme-mbed.md
- docs/release-notes.md
- docs/release.md
- repository.yml
Change references in CI and docs from 'master' to 'main' as the primary
branch has been renamed.
> Migrate master->main

- boot/bootutil/src/loader.c
The variable `rc` is used in `context_boot_go` for a number of operations, mostly checking return codes for an error. It is also used to store the result of comparing the installed application version numbers (using `boot_version_cmp`).
At the end of `context_boot_go`, `rc` is returned as the result of the operation.
In some configurations, namely direct XIP (without revert or any other extra boot checks), it is possible for the comparison result to be the last value of `rc`. In most cases, this will cause `context_boot_go` to report a failure (ie: non-zero return code), as the value of `rc` will be 1 or -1 if the installed applications aren't the same version.
This commit resets the value of `rc` to 0 after the version comparison has taken place.
Fixes #976
Signed-off-by: George …
> Fix version comparison result causing boot failure

- boot/boot_serial/src/boot_serial.c
- boot/zephyr/main.c
K_sleep() is not available when multithreading is disabled.
Let's use k_busy_wait() in that case.
> boot_serial: zephyr: allow to build when CONFIG_MULTITHREADING=n

- .github/workflows/stale_issue.yml
This workflow will add a 'stale' label to any issues that haven't been
modified in 60 days, and then after an additional 14 days, will close
the issue.
The template was copied from Zephyr.
> github: Add workflow to mark stale issues

- boot/zephyr/serial_adapter.c
The following commit in Zephyr removed the need to unlock interrupts
when booting in single-threaded mode:
https://github.com/zephyrproject-rtos/zephyr/commit/3b89cf173b6b0085c84a09fd97b42e08a25ae4b3
Remove the now obsolete lines.
Fixes #302.
> zephyr: serial: Remove unnecessary call to irq_unlock

- .gitmodules
- boot/boot_serial/pkg.yml
- boot/boot_serial/src/boot_serial.c
- boot/boot_serial/src/cbor_common.c
- boot/boot_serial/src/cbor_common.h
- boot/boot_serial/src/cbor_decode.c
- boot/boot_serial/src/cbor_decode.h
- boot/boot_serial/src/cbor_encode.c
- boot/boot_serial/src/cbor_encode.h
- boot/boot_serial/src/regenerate_serial_recovery_cbor.sh
- boot/boot_serial/src/serial_recovery_cbor.c
- boot/boot_serial/src/serial_recovery_cbor.h
- boot/boot_serial/src/types_serial_recovery_cbor.h
- boot/boot_serial/test/src/testcases/boot_serial_upload_bigger_image.c
- boot/zephyr/CMakeLists.txt
- boot/zephyr/Kconfig
Also update cddl-gen to newer version.
This removes the dependency on tinycbor.
> boot_serial: port CBOR encoding to use cddl-gen

- boot/bootutil/include/bootutil/bootutil_public.h
- boot/bootutil/src/bootutil_public.c
- boot/bootutil/src/swap_move.c
- boot/bootutil/src/swap_scratch.c
The PR contains series of commits that:
- make `boot_read_swap_state` public and available from bootutil_public.h;
- change `fixup_revert` to use provided flash area object pointer to obtain swap state by call to `boot_read_swap_state`, instead of previously used `boot_read_swap_state_by_id`; this makes ID param (`sec_id`) no longer needed;
- makes `boot_swap_sector` call `boot_read_swap_state` on already opened scratch flash area, instead of using `boot_read_swap_state_by_id`, with the area ID, which caused double open on the flash area;
- changes logic of `boot_set_pending_multi` by moving `flash_area_open` to the top of the function, making that the only place where flash area object is obtained in the function; switches the function to use `boot_read_swap_state`;
- switches …
> Make boot_read_swap_state declaration public

- boot/bootutil/include/bootutil/ramload.h
- boot/bootutil/src/bootutil_priv.h
- boot/bootutil/src/loader.c
- docs/design.md
Multiple image boot support is implemented for direct-xip and ram-load
strategies. Dependency checking is also added, and for ram-load more
executable ram regions can be set.
Signed-off-by: Mark Horvath <mark.horvath@arm.com>
Change-Id: I59b346277dcb2c17cef4800f1e556b4ea9144845
> boot: Multi-image boot for direct-xip and ram-load

- boot/bootutil/src/bootutil_priv.h
- boot/bootutil/src/loader.c
The commit removes implementation of boot_initialize_area
specific for flash_area_to_sectors, and applies changes to
the flash_area_get_sectors using variant, to make it
alternatively work with flash_area_to_sectors.
> bootutil: Reduce boot_initialize_area variants

- CODE_OF_CONDUCT.md
Incorporate the [Contributor Covenant](https://www.contributor-covenant.org/)
used by a large number of open source communities.
> Create template code of conduct

- boot/zephyr/sample.yaml
MCUboot was build only for frdm_k64f in zephyr CI.
Extended Zephyr-RTOS integration platform by nrf52840dk_nrf52840
and nrf52840dongle_nrf52840 which allow to build MCUBoot on
these platform in Zephyr-RTOS CI.
> zephyr: allow to build nRF52840 targets in zephyr-rtos CI

- boot/bootutil/zephyr/CMakeLists.txt
Switch to use zephyr_library_named() which creates a shorter library name.
> Fix path length limit win os

- boot/boot_serial/src/boot_serial.c
- boot/cypress/MCUBootApp/config/mcuboot_config/mcuboot_config.h
- boot/mbed/include/mcuboot_config/mcuboot_config.h
- boot/mynewt/mcuboot_config/include/mcuboot_config/mcuboot_config.h
- boot/zephyr/include/mcuboot_config/mcuboot_config.h
- samples/mcuboot_config/mcuboot_config.template.h
If a port supports single thread or is bare-metal then might be need
to switch to idle mode explicitly form MCUboot code.
The call allows to enable lower power consumption while waiting for
incoming transmission in serial recovery etc.
Especially:
Sine a while there is no silent idle thread created automatically while
CONFIG_MULTITHREADING=n in zephyr. Since that any single thread application
needs to call k_cpu_idle() by itself for entering idle mode, which
allows for reduction power consumption.
> boot: introduce MCUBOOT_CPU_IDLE() for support low power single thread 

- boot/bootutil/src/loader.c
There ir a couple of misspelled variables (slot -> active_slot).
fix #1028
Signed-off-by: Carlos Falgueras García <carlos.falgueras@wslw.es>
> bootutil: Fix some misspelling variables

- .github/workflows/stale_issue.yml
Change the stale bot to 180 days before initial flag.  In addition,
avoid issues entirely that have the 'someday' label applied.
> workflow: Back off stale bot a bit

- boot/boot_serial/src/boot_serial.c
- boot/bootutil/include/bootutil/image.h
- boot/bootutil/src/bootutil_misc.c
- boot/bootutil/src/bootutil_priv.h
- boot/bootutil/src/bootutil_public.c
- boot/bootutil/src/encrypted.c
- boot/bootutil/src/loader.c
- boot/bootutil/src/swap_misc.c
- boot/bootutil/src/swap_priv.h
- boot/bootutil/src/swap_scratch.c
- boot/cypress/cy_flash_pal/include/flash_map_backend/flash_map_backend.h
- boot/mbed/include/flash_map_backend/flash_map_backend.h
- boot/mynewt/flash_map_backend/include/flash_map_backend/flash_map_backend.h
- boot/zephyr/flash_map_extended.c
- boot/zephyr/include/flash_map_backend/flash_map_backend.h
- boot/zephyr/single_loader.c
- docs/PORTING.md
- sim/mcuboot-sys/csupport/run.c
Intention of this PR is to present an idea that should allow the mcuboot to become system agnostic regarding
the internal structure of flash_area and flash_sector objects.
The idea is to provide getter/setter macros (here) or functions that should only be used to access the fields of objects
and forbid direct access to fields.
Such approach should allow greater flexibility regarding management and processing of such objects as it should allow additional, system processing of returned values, which, after obtaining an object (for example flash_area) is not possible,
> RFC: Replace direct access to flash_area/flash_sector fields with getter functions

- boot/bootutil/include/bootutil/bootutil_public.h
This PR intends to provide two fixes for minor issues encountered during the creation of a new port:
- The `mcuboot_config.h` header is missing from `bootutil_public.h` includes for the evaluation of the `MCUBOOT_HAVE_ASSERT_H` definition.
- `ASSERT` macro may be already defined by the underlying OS, so we need to avoid redefining it.
> bootutil: Include missing header and prevent ASSERT redefinition

- boot/boot_serial/src/boot_serial.c
- boot/boot_serial/src/boot_serial_priv.h
- boot/zephyr/Kconfig
- boot/zephyr/flash_map_extended.c
- boot/zephyr/include/mcuboot_config/mcuboot_config.h
The PR adds support for respecting the "image" parameter of the mcumgr image upload command in serial recovery.
This allows to directly upload image by number; the translation of the image number to the destination is done by platform specific implementation of the `flash_area_id_from_direct_image` function.
The PR contains two commits:
- general code change, addition of `MCUBOOT_SERIAL_DIRECT_IMAGE_UPLOAD` that controls the options and prototype for `flash_area_id_from_direct_image`
- Zephyr specific implementation.
> Option for serial recovery to respect "image" parameter of mcumgr image update

- boot/bootutil/src/loader.c
Change fixes memory alignment of the RAM buffer that is used to temprorarily store data during swap. Some FLASH drivers require word-aligned input data buffer. Using unaligned buffer results in FLASH write error.
> boot: bootutil: Fix memory alignment of RAM buffer

- .github/workflows/sim.yaml
- boot/bootutil/include/bootutil/caps.h
- boot/bootutil/src/bootutil_priv.h
- boot/bootutil/src/caps.c
- boot/bootutil/src/image_validate.c
- boot/bootutil/src/loader.c
- sim/Cargo.toml
- sim/mcuboot-sys/Cargo.toml
- sim/mcuboot-sys/build.rs
- sim/mcuboot-sys/csupport/run.c
- sim/mcuboot-sys/src/api.rs
- sim/mcuboot-sys/src/c.rs
- sim/mcuboot-sys/src/lib.rs
- sim/src/caps.rs
- sim/src/image.rs
- sim/src/tlv.rs
- sim/tests/core.rs
Fix enough in the simulator so that the direct-xip and ramload configurations can be run. All of the existing tests assume that MCUboot modifies flash to make use of the new image. This PR does not add additional tests for this functionality, but fixes enough so that they can be compiled, and that inappropriate tests will be avoided.
> Add support in sim for direct-xip and ramload

- boot/bootutil/src/boot_record.c
The commit "boot: Check shared area more carefully before init" adds
the support that the shared area can be used by other boot stages.
Before this commit, MCUboot initialize the shared memory based on a
global variable which indicates whether the shared memory has been
initialized by MCUboot. After this commit, MCUboot also checks the magic
value as well as the sanity check before initialization. So if the data
in shared memory retains after a reset, MCUboot does not initialize the
shared memory thus 'SHARED_MEMORY_OVERWRITE' error happens in
'boot_add_data_to_shared_area'.
So reverted this commit temporarily.
Signed-off-by: Sherry Zhang <sherry.zhang2@arm.com>
Change-Id: I1fc390bc17f90c2624024bc101ba8b4d5a75fe23
> boot: Revert "boot: Check shared area more carefully before init"

- boot/boot_serial/src/boot_serial.c
- boot/zephyr/include/mcuboot_config/mcuboot_config.h
The `CONFIG_BOOT_ERASE_PROGRESSIVELY` is used in common boot_serial.c code to turn on the progressive erase;
because the code is common and the options is Zephyr characteristic Kconfig option, the PR renames the option to port agnostic `MCUBOOT_ERASE_PROGRESSIVELY`, and adds proper mcuboot_config.h code to handle the change for Zephyr.
> Rename CONFIG_BOOT_ERASE_PROGRESSIVELY to platform agnostic MCUBOOT_ERASE_PROGRESSIVELY

- boot/zephyr/Kconfig
The Kconfig option is applied only when MCUBOOT_SERIAL is enabled
so it has been moved into MUCBOOT_SERIAL dependent section
of Kconfig.
> zephyr: Relocate BOOT_ERASE_PROGRESSIVELY option

- boot/boot_serial/src/boot_serial.c
- boot/bootutil/include/bootutil/bootutil_log.h
- boot/bootutil/src/bootutil_misc.c
- boot/bootutil/src/bootutil_public.c
- boot/bootutil/src/loader.c
- boot/bootutil/src/swap_misc.c
- boot/bootutil/src/swap_move.c
- boot/bootutil/src/swap_scratch.c
- boot/zephyr/flash_map_extended.c
- boot/zephyr/flash_map_legacy.c
- boot/zephyr/include/platform-bench.h
- boot/zephyr/main.c
- boot/zephyr/serial_adapter.c
- boot/zephyr/single_loader.c
The "MCUBOOT_LOG_MODULE_(DECLARE|REGISTER)" macros should have a name
coherent with the rest of the logs macors, ie "BOOT_LOG_*". Also,
"bootutil_log.h" should define them as empty when the logs are disabled and
as "MCUBOOT_LOG_MODULE_*" when they are not.
With this change, the mcuboot user doesn't have to define
MCUBOOT_LOG_MODULE_* macros if the logs don't going to be used.
Signed-off-by: Carlos Falgueras García <carlos.falgueras@wslw.es>
> bootutil: Refactor MCUBOOT_LOG_MODULE_(DECLARE|REGISTER) macros

- boot/bootutil/src/loader.c
A false error condition occurs from v1.7.0 when all the optional features are disabled in direct-xip mode.
This bug is not present anymore on the main branch because it has been eliminated as the code changed over time.
> v1.7 branch: Fix false error condition in direct-xip mode

- boot/bootutil/include/bootutil/image.h
The previous definition did not work as setting any type of flag would
make IS_ENCRYPTED true.
Signed-off-by: Salome Thirot <salome.thirot@arm.com>
> boot: Fix IS_ENCRYPTED macro definition

- scripts/assemble.py
This PR updates the path to the devicetree python package lib files according to this Zephyr PR [zephyrproject-rtos#33746](https://github.com/zephyrproject-rtos/zephyr/pull/33746) which moved the devicetree lib files.
Old path: `ZEPHYR_BASE/scripts/dts/`
New path: `ZEPHYR_BASE/scripts/dts/python-devicetree/src/devicetree/`
This PR solves the issue [mcuboot#1043](https://github.com/mcu-tools/mcuboot/issues/1043) Without this fix mcuboot won't build with zephyr 2.6.0.
> Update path to devicetree python package lib files

- boot/zephyr/sample.yaml
The platforms that are listed as integration platforms in
the Zephyr boot sample need to be included in the platform
allow list, otherwise zephyr CI will through an error.
Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>
> boot: zephyr: add integration platforms to the allow list

- boot/boot_serial/src/cbor_encode.h
Fix structure member assignment in tstrx_put() tstrx_put_term()
macro.
> cbor_encoder: fix str encoding macros

- boot/boot_serial/src/boot_serial.c
The commit modifies mcumgr group processing in boot_serial_input
to allow catching any group that has not been processed by user
provided function.
> boot_serial: Allow platforms to catch any unprocessed groups

- boot/zephyr/Kconfig
LOG_IMMEDIATE Kconfig option has been repurposed and is now a Zephyr's internal, non-visible symbol that should not be modified by the end user.
The option's default value has been added in the past to configure synchronous logging if multi-threading is disabled. At present it prevents the user from configuring synchronous logging mode when multi-threading is enabled.
Remove the defaults altogether as the logging mode used by MCUBoot is defined in prj.conf.
> zephyr: do not set defaults for LOG_IMMEDIATE Kconfig

- boot/bootutil/src/loader.c
When no dynamic memory is used, there is no need for include "os/malloc.h",
and do so will force the user to create an empty "os/malloc.h" file.
Signed-off-by: Carlos Falgueras García <carlos.falgueras@wslw.es>
> bootutil: Only include <os/malloc.h> if it going to be used

- boot/bootutil/src/loader.c
Magic for different header was reported than the one that had failed
the check.
> boot: Fix log reporting magic from incorrect header

- boot/zephyr/main.c
`irq_lock()` sets `BASEPRI_MAX` aka. the `BASEPRI` mask to whatever
zephyr has configured it to be by the value of `_EXC_IRQ_DEFAULT_PRIO`.
However by calling arm_cleanup() we also do the call to
`__disable_irq()` setting the PRIMASK to 1. Meaning the only exceptions
we can recive is fault exceptions. Masking out more exceptions does not
really make sense.
The rational behind this change is that sometimes applications booted by MCUBoot will not expect the `BASEPRI`
to be set to something other than 0(No effect). Meaning if they depend on
using some exception which now is masked out by `BASEPRI` they will
fail. 
Signed-off-by: Sigvart Hovland <sigvart.hovland@nordicsemi.no>
> boot: zephyr: Do not use `irq_lock()` if using arm cleanup

- .mbedignore
The old mbed CLI 1 tool, currently used to compile the MCUboot port for Mbed™ OS, compiles all files unless otherwise specified in `.mbedignore`.   The espressif directory in the boot folder was added to the ignore file to prevent failed builds. 
@pan-
> Prevent compilation of Espressif files on Mbed build

- README.md
- boot/nuttx/include/flash_map_backend/flash_map_backend.h
- boot/nuttx/include/mcuboot_config/mcuboot_config.h
- boot/nuttx/include/mcuboot_config/mcuboot_logging.h
- boot/nuttx/include/os/os_malloc.h
- boot/nuttx/include/sysflash/sysflash.h
- boot/nuttx/include/watchdog/watchdog.h
- boot/nuttx/main.c
- boot/nuttx/src/flash_map_backend/flash_map_backend.c
- boot/nuttx/src/watchdog/watchdog.c
- docs/readme-nuttx.md
This PR intends to add support for the **Apache NuttX RTOS** as a new port to the MCUboot project.
**Apache NuttX** is an RTOS with an emphasis on standards compliance and small footprint:
https://nuttx.apache.org/
https://github.com/apache/incubator-nuttx/
This port enables the following usages for MCUboot on Apache NuttX:
- MCUboot secure boot solution as a Apache NuttX application.
- Apache NuttX application images capable of accessing MCUboot public interfaces for providing support for secure firmware OTA update solutions.
The user is required to follow the Apache NuttX build process for the desired platform and include the MCUboot application during the configuration phase via `make menuconfig`.
MCUboot integration on NuttX build system and some examples: …
> boot: Add support for the Apache NuttX RTOS

- boot/zephyr/CMakeLists.txt
- boot/zephyr/Kconfig
- boot/zephyr/boot_serial_extensions.c
**UPDATE 2021-08-17**
Made the extensions file conditional, via another commit added here.
The commit adds Kconfig option that enables the storage erase mgmt
command.
Addition of the Kconfig option fixes the problem where Zephyr spcyfic
mgmt commands support fails to compile when board does not define
a storage partition.
fixes #1100
> zephyr: Add option for enabling the storage erase command

- boot/boot_serial/src/cbor_encode.c
Change fixes encoding data length and adds support for big endian byte ordering. According to specification, data length can be encoded either on 1, 2, 4 or 8 bytes.
fixes #1104
> boot_serial: cbor_encode: Fix encoding data length

- boot/nuttx/include/mcuboot_config/mcuboot_config.h
This PR intends to enable the NuttX port to select between Mbed TLS and TinyCrypt as the cryptographic backends.
The selection is achieved by means of NuttX `make menuconfig` command.
> boot/nuttx: Enable crypto backend according to configuration from NuttX

- boot/nuttx/include/sysflash/sysflash.h
- boot/nuttx/main.c
This PR intends to provide minor fixes to the NuttX port to prevent compiler warnings.
No functionality changes, should have no impact.
> boot/nuttx: Fix trivial compiler warnings emitted by NuttX port

- .mbedignore
This commit simply adds the new nuttx files to the list of directories for Mbed's legacy build tools to ignore.
Signed-off-by: George Beckstein <george.beckstein@gmail.com>
> Ignore nuttx files for Mbed-OS builds

- boot/zephyr/main.c
So in PR #1089 I misaligned the `#else` used for the `irq_lock` as it
should be aligned with `CONFIG_MCUBOOT_CLEANUP_ARM_CORE`. So that
`irq_lock`is called when we don't call `__disable_irq` from arm core
clean up code.
Signed-off-by: Sigvart Hovland <sigvart.hovland@nordicsemi.no>
> boot: zephyr: Fix misaligned #else for `irq_lock`

- boot/bootutil/include/bootutil/boot_record.h
This commit adds an include clause to "boot_record.h" to include the stddef.h header that contains the declaration of the "size_t" type.
Attempting to include "boot_record.h" in a build for Mbed-OS would throw an error complaining "size_t" was unknown, adding a note to inculde "stddef.h"
Signed-off-by: George Beckstein <george.beckstein@gmail.com>
> Fix unknown type name "size_t" error in "boot_record.h"

- boot/espressif/CMakeLists.txt
- boot/espressif/hal/CMakeLists.txt
Fix unnecessary dependencies caused by toolchain's libc inclusion.
Signed-off-by: Almir Okato <almir.okato@espressif.com>
> boot/espressif: Remove toolchain libc linking

- boot/zephyr/Kconfig
The dependency, in Kconfig,  blocked usage of the ENABLE_MGMT_PERUSER
with other BOOT_SERIAL_ device options.
> zephyr: Remove BOOT_SERIAL_UART dependency from ENABLE_MGMT_PERUSER

- boot/bootutil/zephyr/CMakeLists.txt
- boot/zephyr/CMakeLists.txt
This patch make possible MCUBOOT_BOOTUTIL to integrate the
hook file on their own. This is intended to support hook while
the library is just part of the application.
The hooks file for the MCUboot build is now included in the same manner.
> zephyr: support the hook file by MCUBOOT_BOOTUTIL library

- boot/bootutil/include/bootutil/boot_record.h
- boot/mbed/include/utils/DataShare.cpp
- boot/mbed/include/utils/DataShare.h
- boot/mbed/mbed_lib.json
This PR adds configuration parameters for Mbed-OS to use the shared data feature of mcuboot.
It also introduces an iterator-style utility class for Mbed-OS applications booted by mcuboot to iterate through the TLV-encoded values in the shared data region.
> Mbed add shared data config
